-- Seed codigos_catalogo — parte 1 (800 filas)
-- Generado desde Accessories_List_2026-08-02.xlsx, hoja "List code".
INSERT INTO codigos_catalogo (codigo, familia, descripcion) VALUES
('HI700', 'a. Checkers', 'Ammonia Low Range Checker® HC'),
('HI701', 'a. Checkers', 'Free Chlorine Checker® HC'),
('HI7014', 'a. Checkers', 'Pool Line Free Chlorine Checker® HC'),
('HI702', 'a. Checkers', 'Copper High Range Checker'),
('HI7024', 'a. Checkers', 'Pool Line Copper High Range Checker'),
('HI705', 'a. Checkers', 'Silica Checker'),
('HI706', 'a. Checkers', 'Phosphorous HR Checker HC®'),
('HI707', 'a. Checkers', 'Nitrite LR Checker (0-999 ppb)'),
('HI708', 'a. Checkers', 'Nitrite HR Checker (0-150 ppm)'),
('HI709', 'a. Checkers', 'Manganese High Range Checker'),
('HI711', 'a. Checkers', 'Total chlorine Checker HC® colorimeter: Range 0.00 to 3.50 ppm (mg/L)'),
('HI713', 'a. Checkers', 'Phosphate low range Checker HC® colorimeter: Range 0.00 to 2.50 ppm (mg/L)'),
('HI7134', 'a. Checkers', 'Pool Line Phosphate low range Checker HC® colorimeter: Range 0.00 to 2.50 ppm (mg/L)'),
('HI715', 'a. Checkers', 'Ammonia Medium Range, Checker (0.00 to 9.99 ppm)'),
('HI716', 'a. Checkers', 'Bromine Checker (0.0 to 9.99 ppm)'),
('HI717', 'a. Checkers', 'Phosphate HR Checker HC®, 0.0 to 30.0 ppm (mg/L)'),
('HI718', 'a. Checkers', 'Iodine Checker HC® colorimeter: Range 00.0 to 12.5 ppm (mg/L)'),
('HI719', 'a. Checkers', 'Magnesium Hardness Checker'),
('HI720', 'a. Checkers', 'Calcium Hardness Checker'),
('HI721', 'a. Checkers', 'Iron Checker HC® colorimeter: Range 0.00 to 5.00 ppm (mg/L)'),
('HI7214', 'a. Checkers', 'Pool Line Iron Checker HC® colorimeter: Range 0.00 to 5.00 ppm (mg/L)'),
('HI723', 'a. Checkers', 'Chromium VI High Range Checker HC®, 0 to 999 ppb'),
('HI726', 'a. Checkers', 'Nickel HR Checker HC®, 0.00 to 7.00 g/L'),
('HI727', 'a. Checkers', 'Color of Water Checker HC®, 0 to 500 PCU'),
('HI729', 'a. Checkers', 'Fluoride LR Checker HC®, 0.00 to 2.00 ppm'),
('HI733', 'a. Checkers', 'Ammonia High Range Checker (0.0-99.9 ppm)'),
('HI735', 'a. Checkers', 'Total Hardness Low Range Checker'),
('HI736', 'a. Checkers', 'Phosphorus ultra low range Checker HC® colorimeter: Range 0 to 200 ppb'),
('HI739', 'a. Checkers', 'Fluoride HR Checker HC®, 0.0 to 20.0 ppm'),
('HI746', 'a. Checkers', 'Iron Low Range Checker HC® colorimeter: Range 0 to 999 ppb (ug/l)'),
('HI747', 'a. Checkers', 'Copper Low Range Checker'),
('HI749', 'a. Checkers', 'Chromium Low Range Checker (0-300 ppb)'),
('HI753', 'a. Checkers', 'Chloride Checker (0.0 to 20.0 ppm)'),
('HI755', 'a. Checkers', 'Marine Alkalinity (CaCO3) Checker® HC'),
('HI758', 'a. Checkers', 'Marine calcium Checker HC® colorimeter'),
('HI759', 'a. Checkers', 'Maple Syrup color grading Checker HC® colorimeter'),
('HI761', 'a. Checkers', 'Total Chlorine Checker Ultra Low Range (0 to 500 ppb)'),
('HI762', 'a. Checkers', 'Free Chlorine Ultra Low Range Checker® HC'),
('HI764', 'a. Checkers', 'Nitrite ultra low range Checker HC®: Range 0 to 200 ppb'),
('HI767', 'a. Checkers', 'Marine Nitrite low range Checker HC: Range 0 to 999 ppb'),
('HI770', 'a. Checkers', 'Silica HR Checker HC®, 0 to 200 ppm'),
('HI771', 'a. Checkers', 'Chlorine Checker, Ultra High Range (0-500 ppm)'),
('HI772', 'a. Checkers', 'Marine Alkalinity (dKH) Checker® HC'),
('HI774', 'a. Checkers', 'Marine phosphate - ultra low range Checker HC® colorimeter: Range 0.00 to 0.60 ppm'),
('HI775', 'a. Checkers', 'Alkalinity Checker for drinking water'),
('HI7754', 'a. Checkers', 'Pool Line Alkalinity Checker for drinking water'),
('HI779', 'a. Checkers', 'Pool Line pH Handheld Colorimeter®'),
('HI780', 'a. Checkers', 'Marine pH Checker'),
('HI781', 'a. Checkers', 'Marine nitrate low range Checker'),
('HI782', 'a. Checkers', 'Marine Nitrate High Range'),
('HI783', 'a. Checkers', 'Marine Magnesium Checker'),
('HI784', 'a. Checkers', 'Marine Ammonia Checker'),
('HI700-11', 'a. Checkers - Reagents', 'Ammonia Checker calibration check set (0.00 and 1.00 ppm Ammonia)'),
('HI700-25', 'a. Checkers - Reagents', 'Reagents for LR ammonia Checker'),
('HI701-11', 'a. Checkers - Reagents', 'Free Chlorine Checker HC® Calibration Check set (0.00 and 1.00 ppm Free Cl₂)'),
('HI701-25', 'a. Checkers - Reagents', 'Chlorine, free, DPD method, reagents for 25 tests (free Chlorine)'),
('HI7014-11', 'a. Checkers - Reagents', 'Pool Line Free Chlorine Checker HC® Calibration Check set (0.00 and 1.00 ppm Free Cl?)'),
('HI7014-25', 'a. Checkers - Reagents', 'Pool Line Chlorine, free, DPD method, reagents for 25 tests (free Chlorine)'),
('HI702-11', 'a. Checkers - Reagents', 'Copper High Range Checker calibration check set'),
('HI702-25', 'a. Checkers - Reagents', 'Copper High Range Checker reagents'),
('HI7024-11', 'a. Checkers - Reagents', 'Pool Line Copper High Range Checker calibration check set'),
('HI7024-25', 'a. Checkers - Reagents', 'Pool Line Copper High Range Checker reagents'),
('HI70436M', 'a. Checkers - Reagents', 'Deionized Water, 230 mL bottle'),
('HI705-11', 'a. Checkers - Reagents', 'Silica Low Range Checker HC Calibration Check Set'),
('HI705-25', 'a. Checkers - Reagents', 'Silica Checker (0.00 - 4.00 ppm) spare reagents (25 tests)'),
('HI706-11', 'a. Checkers - Reagents', 'Phosphorus High Range Checker HC® Calibration Check Set (0.0 and 7.5 ppm)'),
('HI706-25', 'a. Checkers - Reagents', 'Checker HC reagents for 40 tests (Phosphorus HR)'),
('HI707-11', 'a. Checkers - Reagents', 'Nitrite Low Range Checker HC Calibration Check Set (0-999 ppb)'),
('HI707-25', 'a. Checkers - Reagents', 'Nitrite LR Checker (0-999 ppb) spare reagents (25 tests)'),
('HI708-11', 'a. Checkers - Reagents', 'Nitrite High Range Checker HC Calibration Check Set (0-150 ppm)'),
('HI708-25', 'a. Checkers - Reagents', 'Nitrite HR Checker (0-150 ppm)spare reagents (25 tests)'),
('HI709-11', 'a. Checkers - Reagents', 'Manganese High Range Checker HC Calibration Check Set'),
('HI709-25', 'a. Checkers - Reagents', 'Manganese High Range Checker reagents'),
('HI711-11', 'a. Checkers - Reagents', 'Total Chlorine Checker HC Calibration Check Set'),
('HI711-25', 'a. Checkers - Reagents', 'Chlorine, total, DPD method, reagents for 25 tests (total Chlorine)'),
('HI713-11', 'a. Checkers - Reagents', 'Phosphate Low Range Checker HC Calibration Check Set'),
('HI713-25', 'a. Checkers - Reagents', 'Phosphate, LR Checker HC, ascorbic acid method, reagents for 25 tests'),
('HI7134-11', 'a. Checkers - Reagents', 'Pool Line Phosphate Low Range Checker HC Calibration Check Set'),
('HI7134-25', 'a. Checkers - Reagents', 'Pool Line Phosphate, LR Checker HC, ascorbic acid method, reagents for 25 tests'),
('HI715-11', 'a. Checkers - Reagents', 'Ammonia Medium Range Checker HC Calibration Check Set'),
('HI715-25', 'a. Checkers - Reagents', 'Ammonia Medium Range, Checker spare reagents'),
('HI716-11', 'a. Checkers - Reagents', 'Bromine Checker HC Calibration Check Set'),
('HI716-25', 'a. Checkers - Reagents', 'Bromine Checker (0.0 to 9.99 ppm) spare reagents'),
('HI717-11', 'a. Checkers - Reagents', 'Phosphate High Range Checker HC Calibration Check Set (0.0 and 15.0 ppm phosphate)'),
('HI717-25', 'a. Checkers - Reagents', 'Phosphate HR Checker HC reagents for 40 tests (Phosphate HR)'),
('HI718-11', 'a. Checkers - Reagents', 'Iodine Checker HC Calibration Check Set'),
('HI718-25', 'a. Checkers - Reagents', 'Iodine, DPD method, reagents for 25 tests'),
('HI719-11', 'a. Checkers - Reagents', 'Magnesium Hardness Checker HC Calibration Check Set'),
('HI719-25', 'a. Checkers - Reagents', 'Magnesium Hardness Checker reagents'),
('HI720-11', 'a. Checkers - Reagents', 'Calcium Hardness Checker HC Calibration Check Set'),
('HI720-25', 'a. Checkers - Reagents', 'Calcium Hardness Checker reagents'),
('HI721-11', 'a. Checkers - Reagents', 'Iron Checker HC Calibration Check Set'),
('HI721-25', 'a. Checkers - Reagents', 'Iron, EPA Phenantroline, reagents for 25 tests'),
('HI7214-11', 'a. Checkers - Reagents', 'Pool Line Iron Checker HC Calibration Check Set'),
('HI7214-25', 'a. Checkers - Reagents', 'Pool Line Iron, EPA Phenantroline, reagents for 25 tests'),
('HI723-11', 'a. Checkers - Reagents', 'Chromium VI High Range Checker HC Calibration Check Set (0 and 300 ppb chromium VI)'),
('HI723-25', 'a. Checkers - Reagents', 'Chromium VI High Range Checker HC reagents for 25 tests'),
('HI726-11', 'a. Checkers - Reagents', 'Nickel High Range Checker HC Calibration Check Set (0 and 3.50 Nickel)'),
('HI726-25', 'a. Checkers - Reagents', 'Nickel HR Checker HC reagents for 25 tests (Nickel HR)'),
('HI727-11', 'a. Checkers - Reagents', 'Color of Water Checker HC Calibration Check Set (0 and 150 PCU)'),
('HI729-11', 'a. Checkers - Reagents', 'Fluoride Low Range Checker HC Calibration Check Set (0 and 1.00 ppm)'),
('HI729-26', 'a. Checkers - Reagents', 'Fluoride LR Checker HC Reagents for 20 tests (Fluoride LR)'),
('HI733-11', 'a. Checkers - Reagents', 'Ammonia High Range Checker HC Calibration Check Set (0.0-99.9 ppm)'),
('HI733-25', 'a. Checkers - Reagents', 'Ammonia High Range Checker (0.0-99.9 ppm) spare reagents'),
('HI735-11', 'a. Checkers - Reagents', 'Total Hardness Low Range certified standard kit'),
('HI735-25', 'a. Checkers - Reagents', 'Reagents for 25 Total Hardness Low Range tests'),
('HI736-11', 'a. Checkers - Reagents', 'Phosphorus Ultra Low Range Calibration Check Set'),
('HI736-25', 'a. Checkers - Reagents', 'Phosphorus, ultra low range, ascorbic acid, reagents for 25 tests'),
('HI739-11', 'a. Checkers - Reagents', 'Fluoride High Range Checker HC Calibration Check Set (0 and 10.0 ppm)'),
('HI739-26', 'a. Checkers - Reagents', 'Fluoride HR Checker HC reagents for 30 tests (Fluoride HR)'),
('HI746-11', 'a. Checkers - Reagents', 'Iron Low Range Checker HC® Cal Check standards'),
('HI746-25', 'a. Checkers - Reagents', 'Iron Low Range Reagnet for Checker HC colorimeter 25 tests'),
('HI747-11', 'a. Checkers - Reagents', 'Copper Low Range Checker HC Calibration Check Set'),
('HI747-25', 'a. Checkers - Reagents', 'Copper Low Range Checker reagents'),
('HI749-11', 'a. Checkers - Reagents', 'Chromium Low Range Checker HC Calibration Check Set (0-300 ppb)'),
('HI749-25', 'a. Checkers - Reagents', 'Chromium Low Range Checker (0-300 ppb) spare reagents'),
('HI753-11', 'a. Checkers - Reagents', 'Chloride Checker HC Calibration Check Set'),
('HI753-25', 'a. Checkers - Reagents', 'Chloride Checker spare reagents (25 tests)'),
('HI755-11', 'a. Checkers - Reagents', 'Marine Alkalinity Checker HC Calibration Check Set'),
('HI755-26', 'a. Checkers - Reagents', 'Alkalinity, colorimetric method, Reagents for 25 tests'),
('HI758-11', 'a. Checkers - Reagents', 'Marine Calcium Checker HC® Calibration Check Set'),
('HI758-26', 'a. Checkers - Reagents', 'Marine calcium Checker HC® colorimeter reagents for 25 tests'),
('HI759-11', 'a. Checkers - Reagents', 'Maple Syrup Digital Grader Glycerol Reference Set'),
('HI761-11', 'a. Checkers - Reagents', 'Total Chlorine Checker HC Ultra Low Range Calibration Check Set'),
('HI761-25', 'a. Checkers - Reagents', 'Total Chlorine Checker Ultra Low Range spare reagents (25 tests)'),
('HI762-11', 'a. Checkers - Reagents', 'Free Chlorine Checker HC Ultra Low Range Calibration Check Set'),
('HI762-25', 'a. Checkers - Reagents', 'Free Chlorine Checker Ultra Low Range spare reagents (25 tests)'),
('HI764-11', 'a. Checkers - Reagents', 'Marine Nitrite Ultra Low Range Calibration Check Set'),
('HI764-25', 'a. Checkers - Reagents', 'Nitrite, ultra low range, EPA Diazotization, reagents for 25 tests'),
('HI767-11', 'a. Checkers - Reagents', 'Marine Nitrite low range certified Calibration Check Set'),
('HI767-25', 'a. Checkers - Reagents', 'Marine Nitrite, low range reagents for 25 tests'),
('HI770-11', 'a. Checkers - Reagents', 'Silica High Range Checker HC Calibration Check Set (0 and 100 ppm)'),
('HI770-25', 'a. Checkers - Reagents', 'Silica HR Checker HC reagents for 25 tests (Silica HR)'),
('HI771-11', 'a. Checkers - Reagents', 'Chlorine Ultra High Range Calibration Check Set'),
('HI771-25', 'a. Checkers - Reagents', 'Chlorine UHR Checker HC reagents for 25 tests'),
('HI772-11', 'a. Checkers - Reagents', 'Marine Alkalinity Checker HC Calibration Check Set'),
('HI772-26', 'a. Checkers - Reagents', 'Marine alkalinity, colorimetric method, Reagents for 25 tests'),
('HI774-11', 'a. Checkers - Reagents', 'Marine phosphate - ultra low range calibration check Set'),
('HI774-25', 'a. Checkers - Reagents', 'Marine phosphate - ultra low range, ascorbic acid, reagents for 25 tests'),
('HI775-11', 'a. Checkers - Reagents', 'Freshwater Alkalinity Checker HC Calibration Check Set'),
('HI775-26', 'a. Checkers - Reagents', 'Reagents for Alkalinity Checker for 25 tests'),
('HI7754-11', 'a. Checkers - Reagents', 'Pool Line Freshwater Alkalinity Checker HC Calibration Check Set'),
('HI7754-26', 'a. Checkers - Reagents', 'Pool Line Reagents for Freshwater Alkalinity Checker for 25 tests'),
('HI779-11', 'a. Checkers - Reagents', 'Pool Line pH Certified Standard Kit'),
('HI779-25', 'a. Checkers - Reagents', 'Pool Line pH Reagent Set for 100 Tests'),
('HI780-11', 'a. Checkers - Reagents', 'Marine pH certified standard kit'),
('HI780-25', 'a. Checkers - Reagents', 'Marine pH Checker refills (100 tests)'),
('HI781-11', 'a. Checkers - Reagents', 'Marine nitrate low range certified standard kit'),
('HI781-25', 'a. Checkers - Reagents', 'Marine LR Nitrate Reagents (25 tests)'),
('HI782-11', 'a. Checkers - Reagents', 'Marine Nitrate HR certified standard kit'),
('HI782-25', 'a. Checkers - Reagents', 'Reagents for 25 Marine Nitrate High Range tests'),
('HI783-11', 'a. Checkers - Reagents', 'Marine Magnesium Certified Standard kit'),
('HI783-25', 'a. Checkers - Reagents', 'Marine Magnesium Reagents for 25 tests'),
('HI784-11', 'a. Checkers - Reagents', 'Marine Ammonia Certified Standard kit'),
('HI784-25', 'a. Checkers - Reagents', 'Marine Ammonia Reagents for 25 tests'),
('HI38000', 'b. CTK', 'Sulfate (as SO₄²-), Range: (20-100 mg/L) Method: Turbidimetric, 100 tests'),
('HI38001', 'b. CTK', 'Sulfate (as SO₄²-), Range: (100-1000 mg/L)(1000-10000 mg/L) Method: titration, 200 tests'),
('HI38015', 'b. CTK', 'Extended Range Chloride Test Kit'),
('HI38017', 'b. CTK', 'Chlorine (as Cl₂, free & total), Range: (0.00-0.70 mg/L)(0.0-3.5 mg/L) Method: checker disc, 200 tests'),
('HI38018', 'b. CTK', 'Chlorine (as Cl₂, free), Range: (0.00-0.70mg/L)(0.0-3.5mg/L) Method: checker disc, 200 tests'),
('HI38020', 'b. CTK', 'Chlorine (as Cl₂, free & total), Range: (0.00-0.70 mg/L)(0.0-3.5 mg/L)(0.0-10.0 mg/L) Method: checker disc, 200 tests'),
('HI38022', 'b. CTK', 'Total Chlorine High Range Test Kit'),
('HI38023', 'b. CTK', 'Chlorine (as Cl₂, total), Range: (10-200 mg/L) Method: titration, 100 tests'),
('HI38033', 'b. CTK', 'Hardness (as CaCO3)Total, Range: (0-30 gpg) Method: titration, 100 tests'),
('HI38039', 'b. CTK', 'Iron (Fe+2 & Fe+3), Range: (0.00-1.00 mg/L) Method: checker disc, 100 tests'),
('HI38040', 'b. CTK', 'Iron (Fe+2 & Fe+3), Range: (0.0-5.0 mg/L) Method: checker disc, 100 tests'),
('HI38041', 'b. CTK', 'Iron (Fe+2 & Fe+3), Range: (0.0-10.0 mg/L) Method: checker disc, 100 tests'),
('HI38049', 'b. CTK', 'Ammonia Test Kit for Fresh Water with Checker Disc'),
('HI38050', 'b. CTK', 'Nitrate (as NO3-N), Irrigation water and soil, Range: (water: 0-50 mg/L)(soil: 0-60 mg/L) Method: colorimetric, 100 tests ea.'),
('HI38054', 'b. CTK', 'Ozone, Range: (0.0-2.3 mg/L) Method: checker disc, 100 tests'),
('HI38058', 'b. CTK', 'Checker Disc pH 4.0 to 10.0 Test Kit'),
('HI38061', 'b. CTK', 'Phosphate (as orthophosphate, PO43-), Range: (0.00-1.00 mg/L) (0.0-5.0 mg/L) (0-50 mg/L) Method: checker disc, 100 tests'),
('HI38067', 'b. CTK', 'Silica, Range: (0-40 mg/L)(0-800 mg/L) Method: checker disc, 100 tests'),
('HI38074', 'b. CTK', 'Boron, Range: (0.0-5.0mg/L) Method: titration, 100 tests'),
('HI3810', 'b. CTK', 'Oxygen, Dissolved, Range: (0.0-10.0 mg/L) Method: titration, approx. 110 tests'),
('HI3811', 'b. CTK', 'Alkalinity (as CaCO3) Phenolphthalein and total acidity, Range: (0-100mg/L)(0-300mg/L) Method: titration, approx. 100 tests'),
('HI3812', 'b. CTK', 'Hardness (as CaCO3)Total, Range: (0.0-30.0 mg/L)(0-300 mg/L) Method: titration, 100 tests'),
('HI3814', 'b. CTK', 'Environmental monitoring test kit; acidity (as CaCO3), alkalinity (as CaCO3), carbon dioxide (as CO2), hardness (as CaCO3), dissolved oxygen, pH'),
('HI3815', 'b. CTK', 'Chloride (as Chlorine), Method: Range: (0-100mg/L)(0-1000mg/L) titration, approx. 110 tests'),
('HI3817', 'b. CTK', 'Water quality test kit; alkalinity (as CaCO3), chloride (as Chlorine-), hardness as (CaCO3), iron, pH, & sulfite (as Na2SO3)'),
('HI3817BP', 'b. CTK', 'Backpack Lab™ Water Quality test kit; acidity (CaCO3), alkalinity (CaCO3) phenolphthalein & total, carbon dioxide (as CO2), dissolved oxygen, hardness (CaCO3), nitrate (NO3-) in saltwater, phosphate (orthophosphate PO4-3)'),
('HI3818', 'b. CTK', 'Carbon Dioxide (as CO2), Range: (0.0-10.0mg/L)(0.0-50mg/L)(0-100mg/L) Method: titration, approx. 110 tests'),
('HI3820', 'b. CTK', 'Acidity (as CaCO3), Range: (0-100mg/L) (0-500mg/L) Method: titration, approx. 110 tests'),
('HI3821', 'b. CTK', 'Cooling and boiler test kit; alkalinity (as CaCO3), chloride (Chlorine-), hardness (as CaCO3), phosphate (as PO43-), dissolved oxygen, & sulfite (as Na2SO3)'),
('HI3822', 'b. CTK', 'Sulfite (as Na2SO3), Range: (0.0-20.0 mg/L)(0-200 mg/L) Method: titration, approx. 110 tests'),
('HI3823', 'b. CTK', 'Combination test kit for aquaculture; alkalinity, CO2, hardness, dissolved oxygen, pH and salinity'),
('HI3824', 'b. CTK', 'Ammonia (as NH3-N), Fresh water, Range: (0.0-2.5 mg/L) Method: colorimetric, approx. 25 tests'),
('HI3826', 'b. CTK', 'Ammonia (as NH3-N), Salt water, Range: (0.0-2.5 mg/L) Method: colorimetric, approx. 25 tests'),
('HI3827', 'b. CTK', 'Boiler test kit; alkalinity (as CaCO3), chloride (as Chlorine-), hardness (as CaCO3), pH, phosphate (as PO43-)and sulfite (as Na2SO3)'),
('HI3829F', 'b. CTK', 'Free chlorine chemical test kit, 0.0 to 2.0 ppm'),
('HI3830', 'b. CTK', 'Bromine (as Br₂), Range: (0.0-3.0mg/L) Method: colorimetric, approx. 60 tests'),
('HI3831F', 'b. CTK', 'Chlorine (as Cl₂, free), Range: (0.0-2.5mg/L) Method: colorimetric, approx. 50 tests'),
('HI3831T', 'b. CTK', 'Chlorine (as Cl₂, total), Range: (0.0-2.5mg/L) Method: colorimetric, 50 tests'),
('HI3833', 'b. CTK', 'Phosphate (as orthophosphate, PO43-), Range: (0-5 mg/L) Method: colorimetric, 50 tests'),
('HI3834', 'b. CTK', 'Iron (Fe+2 & Fe+3), Range: (0-5 mg/L) Method: colorimetric, 50 tests'),
('HI3835', 'b. CTK', 'Salinity, Range: (0.0-40.0 g/kg) Method: titration, approx. 110 tests'),
('HI3838', 'b. CTK', 'Formaldehyde Chemical Test Kit'),
('HI3840', 'b. CTK', 'Hardness, total, EDTA method, Test kit for 50 tests (range 0 to 150 mg/L (ppm)'),
('HI3841', 'b. CTK', 'Hardness, total, EDTA method, Test kit for 50 tests (range 40 to 500 mg/L (ppm)'),
('HI3842', 'b. CTK', 'Hardness, total, EDTA method, Test kit for 50 tests (range 400 to 3000 mg/L (ppm)'),
('HI3843', 'b. CTK', 'Hypochlorite (as Cl₂), Range: (50-150 g/L) Method: titration, approx. 100 tests'),
('HI38434', 'b. CTK', 'Pool Line Hypochlorite (as Cl₂), Range: (50-150 g/L) Method: titration, approx. 100 tests'),
('HI3844', 'b. CTK', 'Hydrogen Peroxide (as H2O2), Range: (0.25 mg/L)(1.0 mg/L) Method: titration, approx. 100 tests'),
('HI38444', 'b. CTK', 'Pool Line Hydrogen Peroxide (as H2O2), Range: (0.25 mg/L)(1.0 mg/L) Method: titration, approx. 100 tests'),
('HI3846', 'b. CTK', 'Chromium VI Chemical Test Kit'),
('HI3847', 'b. CTK', 'Copper Chemical Test Kit'),
('HI3850', 'b. CTK', 'Ascorbic Acid Test Kit'),
('HI3854', 'b. CTK', 'Zinc (as Zn+2), Range: (0.0-3.0 mg/L) Method: colorimetric, 100 tests'),
('HI3859', 'b. CTK', 'Glycol, Range: (Present/Absent) Method: visual, 25 tests'),
('HI3864', 'b. CTK', 'Phenols Test Kit with Checker Disc'),
('HI3873', 'b. CTK', 'Nitrite (as as NO- 2-N), Range: (0.0-1.0 mg/L) Method: colorimetric, 100 tests'),
('HI3874', 'b. CTK', 'Nitrate (as NO3-N), Range: (0-50 mg/L) Method: colorimetric, 100 tests'),
('HI3875', 'b. CTK', 'Chlorine (as Cl₂, free), Range: (0.0-3.5mg/L) Method: checker disc, 100 tests'),
('HI3887', 'b. CTK', 'Chlorine (as Cl₂, free & pH), Range: (Cl₂ 0.0-2.5mg/L)(pH 6.0-8.5) Method: colorimetric, approx. 100 tests'),
('HI3890', 'b. CTK', 'Quick hardness chemical test kit'),
('HI38904', 'b. CTK', 'Pool Line Quick hardness chemical test kit'),
('HI3895', 'b. CTK', 'Agriculture test kit, (10 tests ea.)'),
('HI3896', 'b. CTK', 'Agriculture test kit, (25 tests ea.)'),
('HI3896BP', 'b. CTK', 'Backpack Lab™ Soil Quality test kit; nitrogen, phosphorus, potassium and pH'),
('HI3897', 'b. CTK', 'Acidity of Olive Oil, Range: (0.00 - 1.00 % acidity) Method: titration, kit'),
('HI3899BP', 'b. CTK', 'Backpack Lab™ Marine Science test kit; acidity (CaCO3), alkalinity (CaCO3) phenolphthalein & total, ammonia (NH3/NH4+) in saltwater, carbon dioxide (as CO2), dissolved oxygen, nitrite (NO2-N), nitrate (NO3-) in saltwater, phosphate (orthophosphate PO4-3), & salinity'),
('HI38000-10', 'b. CTK - Reagents', 'Sulfate, barium chloride method, Reagent kit for 100 tests (SO₄²-)'),
('HI38001-10', 'b. CTK - Reagents', 'Sulfate LR / HR, barium chloride method, Reagent kit for 100 tests (SO₄²-)'),
('HI38015-100', 'b. CTK - Reagents', 'Extended Range Chloride Test Kit Replacement Reagents (100 tests)'),
('HI38017-200', 'b. CTK - Reagents', 'Chlorine, free and total, LR / MR, DPD colorimetric method, Reagent kit for 200 tests (free and total Cl)'),
('HI38018-200', 'b. CTK - Reagents', 'Chlorine, free, LR / MR, DPD colorimetric method, Reagent kit for 200 tests (free chlorine)'),
('HI38020-200', 'b. CTK - Reagents', 'Chlorine, free and total, LR / MR / HR, DPD colorimetric method, Reagent kit for 200 tests (free and total Cl)'),
('HI38022-100', 'b. CTK - Reagents', 'Total Chlorine High Range Test Kit Replacement Reagents (100 tests)'),
('HI38023-100', 'b. CTK - Reagents', 'Chlorine, total, extended range, iodometric method, Reagent kit for 100 tests (total chlorine)'),
('HI38033-100', 'b. CTK - Reagents', 'Hardness, total, EDTA method, Reagent kit for 100 test'),
('HI38039-100', 'b. CTK - Reagents', 'Iron LR, phenantroline colorimetric method, Reagent kit for 100 tests (Fe)'),
('HI38040-100', 'b. CTK - Reagents', 'Iron MR, phenantroline colorimetric method, Reagent kit for 100 tests (Fe)'),
('HI38041-100', 'b. CTK - Reagents', 'Iron HR, phenantroline colorimetric method, Reagent kit for 100 tests (Fe)'),
('HI38049-100', 'b. CTK - Reagents', 'Ammonia Test Kit for Fresh Water Replacement Reagents (100 tests)'),
('HI38050-200', 'b. CTK - Reagents', 'Nitrate (soil + irrigation), cadmium reduction method, Reagent kit for 200 tests (NO3--N)'),
('HI38054-100', 'b. CTK - Reagents', 'Ozone, DPD method, Reagent kit for 100 tests (O3)'),
('HI38058-100', 'b. CTK - Reagents', 'Checker Disc pH pH 4.0 to 10.0 Test Kit Replacement Reagents (300 Tests)'),
('HI38061-100', 'b. CTK - Reagents', 'Phosphate, ascorbic acid method, Reagent kit for 100 tests (PO43- orthophosphate)'),
('HI38067-100', 'b. CTK - Reagents', 'Silica HR, Heteropoly Blue method, Reagent kit for 100 tests (SiO2)'),
('HI38074-100', 'b. CTK - Reagents', 'Boron, boric acid method, Reagent kit for 100 tests (B)'),
('HI3810-100', 'b. CTK - Reagents', 'Dissolved Oxygen, Winkler method, Reagent kit for 110 tests (O2)'),
('HI3811-100', 'b. CTK - Reagents', 'Alkalinity, acid titration method, Reagent kit for 110 tests (CaCO3)'),
('HI3812-100', 'b. CTK - Reagents', 'Hardness, total, EDTA titration method, Reagent kit for 100 tests (CaCO3)'),
('HI3815-100', 'b. CTK - Reagents', 'Chloride, mercury nitrate titration method, Reagent kit for 100 tests (Cl-)'),
('HI3818-100', 'b. CTK - Reagents', 'Carbon dioxide, base titration method, Reagent kit for 110 tests (CO2)'),
('HI3820-100', 'b. CTK - Reagents', 'Acidity, methyl orange method, Reagent kit for 110 tests (CaCO3)'),
('HI3822-100', 'b. CTK - Reagents', 'Sulfite, iodometric titration method, Reagent kit for 100 tests (Na2SO3)'),
('HI3824-025', 'b. CTK - Reagents', 'Ammonia (fresh water), Nessler colorimetric method, Reagent kit for 25 tests (NH3-N fresh water)'),
('HI3826-025', 'b. CTK - Reagents', 'Ammonia (sea water), Nessler colorimetric method, Reagent kit for 25 tests (NH3- N sea water)'),
('HI3829F-050', 'b. CTK - Reagents', 'Reagents for HI3829F (50 tests)'),
('HI3830-060', 'b. CTK - Reagents', 'Bromine, DPD colorimetric method, Reagent kit for 60 tests (Br₂)'),
('HI3831F-050', 'b. CTK - Reagents', 'Chlorine, free, DPD colorimetric method, Reagent kit for 50 tests (free chlorine)'),
('HI3831T-050', 'b. CTK - Reagents', 'Chlorine, total, DPD colorimetric method, Reagent kit for 50 tests'),
('HI3833-050', 'b. CTK - Reagents', 'Phosphate, ascorbic acid method, Reagent kit for 50 tests (PO43- orthophosphate)'),
('HI3834-050', 'b. CTK - Reagents', 'Iron, phenantroline colorimetric method, Reagent kit for 50 tests (Fe)'),
('HI3835-100', 'b. CTK - Reagents', 'Salinity, mercuric nitrate titration method, Reagent kit for 110 tests (salinity)'),
('HI3838-100', 'b. CTK - Reagents', 'Formaldehyde, acid titration method, Reagent kit for 110 tests (formaldehyde)'),
('HI3843-100', 'b. CTK - Reagents', 'Hypochlorite (bleach) reagents'),
('HI3844-100', 'b. CTK - Reagents', 'Hydrogen Peroxide reagents'),
('HI3846-100', 'b. CTK - Reagents', 'Chromium VI, diphenylcarbohydrazide method, Reagent kit for 100 tests (Cr VI LR)'),
('HI3847-100', 'b. CTK - Reagents', 'Copper HR, bicinchoninate method, Reagent kit for 100 tests (Cu HR) Copper LR / HR, bicinchoninic acid'),
('HI3850-100', 'b. CTK - Reagents', 'Ascorbic Acid Test Kit Reagents (100 tests)'),
('HI3854-100', 'b. CTK - Reagents', 'Zinc Test Kit Replacement Reagents (100 Tests)'),
('HI3859-025', 'b. CTK - Reagents', 'Glycol, oxidation method, Reagent kit for 25 tests (glycol)'),
('HI3864-100', 'b. CTK - Reagents', 'Phenols Test Kit Replacement Reagents (100 tests)'),
('HI3873-100', 'b. CTK - Reagents', 'Nitrite, chromotropic acid method, Reagent kit for 100 tests (NO2--N)'),
('HI3874-100', 'b. CTK - Reagents', 'Nitrate, cadmium reduction method, Reagent kit for 100 tests (NO3--N)'),
('HI3875-100', 'b. CTK - Reagents', 'Chlorine, free, MR, DPD colorimetric method, Reagent kit for 100 tests (free chlorine)'),
('HI3895-010', 'b. CTK - Reagents', 'Soil analysis, Ned (N), ascorbic acid (P), tetraphenylborate (K), pH indicators (pH) Reagent kit for 10 tests (N, P, K, pH)'),
('HI3896-025', 'b. CTK - Reagents', 'Soil analysis, Ned (N), ascorbic acid (P), tetraphenylborate (K), pH indicators (pH) Reagent kit for 25 tests (N, P, K, pH)'),
('HI3897-010', 'b. CTK - Reagents', 'Acidity, olive oil, titration with hydroxide, Spare kit for 10 tests'),
('HI981413-00', 'c. Growchek EC', 'GroLine Nutrient dosing system with HI30033 conductivity probe'),
('HI981413-10', 'c. Growchek EC', 'GroLine Nutrient dosing system with HI30033 conductivity probe, injection valve fitting and tubing'),
('HI981413-20', 'c. Growchek EC', 'GroLine Nutrient dosing system with HI30033 conductivity probe, panel mounted flow cell, fittings and tubing'),
('HI981412-00', 'c. Growchek pH', 'GroLine pH dosing system with HI10063 pH probe'),
('HI981412-10', 'c. Growchek pH', 'GroLine pH dosing system with HI10063 pH probe, injection fitting and tubing'),
('HI981412-20', 'c. Growchek pH', 'GroLine pH dosing system with HI10063 pH probe, panel mounted flow cell, injection fitting and tubing'),
('HI981420-01', 'c. Growchek pH/EC', 'GroLine pH, EC/TDS and temperature monitor for nutrient solutions 115 VAC'),
('HI981420-02', 'c. Growchek pH/EC', 'GroLine pH, EC/TDS and temperature monitor for nutrient solutions 230 VAC'),
('HI981421-01', 'c. Growchek pH/EC', 'GroLine pH, EC/TDS and temperature monitor for nutrient solutions supplied with HI1285-9 probe with 3/4" threaded connection; 115 VAC'),
('HI981421-02', 'c. Growchek pH/EC', 'GroLine pH, EC/TDS and temperature monitor for nutrient solutions supplied with HI1285-9 probe with 3/4" threaded connection; 230 VAC'),
('HI981520-01', 'c. Growchek pH/EC', 'Marine pH, Salinity and Temperature Monitor with replaceable HI1286 pH Electrode and attached Conductivity / Temperature Probe, 115 VAC'),
('HI981520-02', 'c. Growchek pH/EC', 'Marine pH, Salinity and Temperature Monitor with replaceable HI1286 pH Electrode and attached Conductivity / Temperature Probe, 230 VAC'),
('HI98301', 'c. Testers EC', 'New DiST1, waterproof TDS tester with ATC, 1999 ppm (mg/L)'),
('HI98302', 'c. Testers EC', 'New DiST2, waterproof TDS tester with ATC, 10.00 ppt (g/L)'),
('HI983024', 'c. Testers EC', 'Pool Line DiST® 2 TDS tester with HI73302 probe Range: 10.00 ppt (g/L)'),
('HI98303', 'c. Testers EC', 'New DiST3, waterproof EC tester with ATC, 1999 μS/cm'),
('HI98304', 'c. Testers EC', 'New DiST4, waterproof EC tester with ATC, 19.99 mS/cm'),
('HI983044', 'c. Testers EC', 'Pool Line DiST® 4 EC tester with HI73304 probe Range: 19.99 mS/cm'),
('HI98308', 'c. Testers EC', 'PWT Pure water test Range: 0.0 to 99.9 μS/cm'),
('HI98309', 'c. Testers EC', 'UPW Ultra pure water test Range: 0.000 to 1.999 μS/cm'),
('HI98311', 'c. Testers EC', 'DiST® 5 EC/TDS/Temperature tester; EC resolution: 1 µS/cm, TDS resolution: 1 mg/L (ppm) Range: 0 to 3999 μS/cm'),
('HI98312', 'c. Testers EC', 'DiST® 6 EC/TDS/Temperature tester; EC resolution: 0.01 mS/cm, TDS resolution: 0.01 g/L (ppt) Range: 0.00 to 20.00 mS/cm'),
('HI983124', 'c. Testers EC', 'Pool Line DiST® 6 EC/TDS/Temperature tester; EC resolution: 0.01 mS/cm, TDS resolution: 0.01 g/L (ppt) Range: 0.00 to 20.00 mS/cm'),
('HI98318', 'c. Testers EC', 'GroLine waterproof EC/TDS/Temperature tester; EC resolution: 1 µS/cm, TDS resolution: 1 mg/L (ppm) Range: 0 to 6,000 μS/cm'),
('HI98319', 'c. Testers EC', 'Marine waterproof salinity tester'),
('HI98325', 'c. Testers EC', 'GroLine Waterproof Salinity Tester with ATC, Low Range: 0.00 to 10.00 ppt, High Range: 0.0 to 70.0 ppt'),
('HI98326', 'c. Testers EC', 'DiST® 9 Waterproof Salinity Tester with ATC, Low Range: 0.00 to 10.00 ppt, High Range: 0.0 to 70.0 ppt'),
('HI98331', 'c. Testers EC', 'GroLine direct soil EC tester Range: 0.00 to 4.00 mS/cm'),
('HI98100', 'c. Testers pH', 'Checker® Plus pH Tester with 0.01 pH resolution'),
('HI981004', 'c. Testers pH', 'Pool Line Checker® Plus pH Tester with 0.01 pH resolution'),
('HI981014', 'c. Testers pH', 'Pool Line Checker® pH tester, 0.1pH Resolution with 1271 electrode'),
('HI98103', 'c. Testers pH', 'Checker® pH Tester with 0.1 pH resolution'),
('HI981030', 'c. Testers pH', 'Groline soil pH tester'),
('HI981031', 'c. Testers pH', 'Foodcare Beer pH Tester'),
('HI981032', 'c. Testers pH', 'Foodcare Cheese pH Tester'),
('HI981033', 'c. Testers pH', 'Foodcare Wine pH Tester with CPS Technology'),
('HI981034', 'c. Testers pH', 'Foodcare Milk pH Tester'),
('HI981035', 'c. Testers pH', 'Foodcare Sushi pH Tester'),
('HI981036', 'c. Testers pH', 'Foodcare Meat pH Tester'),
('HI981037', 'c. Testers pH', 'Skin and scalp pH tester'),
('HI981038', 'c. Testers pH', 'Bread and Dough Checker pH Tester'),
('HI981039', 'c. Testers pH', 'Chocolate Checker pH Tester'),
('HI981045', 'c. Testers pH', 'pH Tester for Meat with built-in Specialized Electrode, Compatible with FC097 Meat Blade'),
('HI98107', 'c. Testers pH', 'New pHep®, 0.1 pH, with ATC, waterproof'),
('HI981074', 'c. Testers pH', 'Pool Line Waterproof Pocket pH Tester with 0.1 Resolution - pHep®'),
('HI98108', 'c. Testers pH', 'pHep+®, 0.01 pH, with ATC, waterproof, 3pt. calibration'),
('HI98115', 'c. Testers pH', 'GroLine pH tester with HI1271 pH electrode'),
('HI98118', 'c. Testers pH', 'GroLine waterproof pH tester'),
('HI98120', 'c. Testers pH', 'ORP/Temperature Tester'),
('HI981204', 'c. Testers pH', 'Pool Line ORP/Temperature Tester'),
('HI98121', 'c. Testers pH', 'pH/ORP/Temperature Tester'),
('HI981214', 'c. Testers pH', 'Pool Line ORP/pH/Temperature Tester'),
('HI98127', 'c. Testers pH', 'pHep®4 pH/Temperature Tester with 0.1 pH resolution'),
('HI981274', 'c. Testers pH', 'Pool Line pHep®4 pH/Temperature Tester with 0.1 pH resolution'),
('HI98128', 'c. Testers pH', 'pHep®5 pH/Temperature Tester with 0.01 pH resolution and 3 pt. calibration'),
('HI98129', 'c. Testers pH/EC', 'Combo pH/Conductivity/TDS Tester (Low Range)'),
('HI98130', 'c. Testers pH/EC', 'Combo pH/Conductivity/TDS Tester (High Range)'),
('HI981304', 'c. Testers pH/EC', 'Pool Line Combo pH/Conductivity/TDS Tester (High Range)'),
('HI98131', 'c. Testers pH/EC', 'GroLine Combo waterproof pH/EC/TDS/Temperature tester'),
('HI2004-01', 'd. Bench DO', 'edge dedicated Dissolved Oxygen, with HI764080 probe, 115 V'),
('HI2004-02', 'd. Bench DO', 'edge dedicated Dissolved Oxygen, with HI764080 probe, 230V'),
('HI2004-03', 'd. Bench DO', 'edge dedicated DO - w/o Electrode'),
('HI2040-01', 'd. Bench DO', 'edge Oxygen kit, with HI764080 probe, 115 V'),
('HI2040-02', 'd. Bench DO', 'edge Oxygen kit,with HI764080 probe, 230V'),
('HI2640-01', 'd. Bench DO', 'Dissolved Oxygen Benchtop Meter includes HI764080 Dissolved Oxygen Electrode, HI7041S refill Electrolyte Solution, DO membrane caps (2), O-rings (2), Electrode Holder, USB C Power Adapter, USB C to C Cable 1.5 m, 115V'),
('HI2640-02', 'd. Bench DO', 'Dissolved Oxygen Benchtop Meter includes HI764080 Dissolved Oxygen Electrode, HI7041S refill Electrolyte Solution, DO membrane caps (2), O-rings (2), Electrode Holder, USB C Power Adapter, USB C to C Cable 1.5 m, 230V'),
('HI2641-01', 'd. Bench DO', 'Dissolved Oxygen + Logging Benchtop Meter includes HI764080 Dissolved Oxygen Electrode, HI7041S refill Electrolyte Solution, DO membrane caps (2), O-rings (2), Electrode Holder, USB C Power Adapter, USB C to C Cable 1.5 m, 115V'),
('HI2641-02', 'd. Bench DO', 'Dissolved Oxygen + Logging Benchtop Meter includes HI764080 Dissolved Oxygen Electrode, HI7041S refill Electrolyte Solution, DO membrane caps (2), O-rings (2), Electrode Holder, USB C Power Adapter, USB C to C Cable 1.5 m, 230V'),
('HI6421-01', 'd. Bench DO', 'Advanced Dissolved Oxygen Benchtop Meter with HI7641133 Optical DO Probe , 7-inch Color Display, 800 x 480p Resolution, Capacitive Multi-touch Screen and Keys, Ethernet and Wi-Fi Connection, USB type A & type C, 115V'),
('HI6421-02', 'd. Bench DO', 'Advanced Dissolved Oxygen Benchtop Meter with HI7641133 Optical DO Probe , 7-inch Color Display, 800 x 480p Resolution, Capacitive Multi-touch Screen and Keys, Ethernet and Wi-Fi Connection, USB type A & type C, 230V'),
('HI6421-03', 'd. Bench DO', 'Advanced Dissolved Oxygen Benchtop Meter - w/o Electrode'),
('HI6421P-01', 'd. Bench DO', 'Advanced Dissolved Oxygen Benchtop Meter with HI764833 Polarographic DO Probe , 7-inch Color Display, 800 x 480p Resolution, Capacitive Multi-touch Screen and Keys, Ethernet and Wi-Fi Connection, USB type A & type C, 115V'),
('HI6421P-02', 'd. Bench DO', 'Advanced Dissolved Oxygen Benchtop Meter with HI764833 Polarographic DO Probe , 7-inch Color Display, 800 x 480p Resolution, Capacitive Multi-touch Screen and Keys, Ethernet and Wi-Fi Connection, USB type A & type C, 230V'),
('HI6421P-03', 'd. Bench DO', 'Advanced Dissolved Oxygen Benchtop Meter - w/o Electrode'),
('HI6542-01', 'd. Bench DO', '1 pH, 1 optical (opdo®) DO kit: HI6542-01 (US power plug, main unit only) and HI6542-02 (EU power plug, main unit only) is supplied with one HI6000-2 pH/ISE module and one HI6000-4 DO module; HI1131B pH electrode; HI7662-TW temperature probe; pH calibration starter kit consisting of: pH 4.01 buffer solution (2 sachets), pH 7.01 buffer solution sachet (4 sachets), pH 10.01 buffer solution sachet (2 sachets); HI700601 electrode cleaning solution sachet (2 sachets); HI70300S storage solution for pH & ORP electrodes (25 mL); HI7082 3.5M KCl electrolyte solution (30 mL); HI7641133 optical DO probe (opdo®); HI764113‑1 Smart Cap™ with O‑ring; calibration / storage vessel; syringe, lens wipe, silicone grease (6 g sachet); DO Smart Cap quality certificate; HI764060 electrode holder with following accessories: base plate (integrated pivot pin) and screw (requires installation), cable holder clip (attached), electrode holder with adapter, attached, capillary pipette; 24 VDC power adapter; USB-C to USB-A cable; probe quality certificate; quick reference guide with instrument quality certificate. 115V'),
('HI6542-02', 'd. Bench DO', '1 pH, 1 optical (opdo®) DO kit: HI6542-01 (US power plug, main unit only) and HI6542-02 (EU power plug, main unit only) is supplied with one HI6000-2 pH/ISE module and one HI6000-4 DO module; HI1131B pH electrode; HI7662-TW temperature probe; pH calibration starter kit consisting of: pH 4.01 buffer solution (2 sachets), pH 7.01 buffer solution sachet (4 sachets), pH 10.01 buffer solution sachet (2 sachets); HI700601 electrode cleaning solution sachet (2 sachets); HI70300S storage solution for pH & ORP electrodes (25 mL); HI7082 3.5M KCl electrolyte solution (30 mL); HI7641133 optical DO probe (opdo®); HI764113‑1 Smart Cap™ with O‑ring; calibration / storage vessel; syringe, lens wipe, silicone grease (6 g sachet); DO Smart Cap quality certificate; HI764060 electrode holder with following accessories: base plate (integrated pivot pin) and screw (requires installation), cable holder clip (attached), electrode holder with adapter, attached, capillary pipette; 24 VDC power adapter; USB-C to USB-A cable; probe quality certificate; quick reference guide with instrument quality certificate. 230V'),
('HI6542P-01', 'd. Bench DO', '1 pH, 1 polarographic DO kit: HI6542P-01 (US power plug, main unit only) and HI6542P-02 (EU power plug, main unit only) is supplied with one HI6000-2 pH/ISE module and one HI6000-4 DO module; HI1131B pH electrode; HI7662-TW temperature probe; pH calibration starter kit consisting of: pH 4.01 buffer solution (2 sachets), pH 7.01 buffer solution sachet (4 sachets), pH 10.01 buffer solution sachet (2 sachets); HI700601 electrode cleaning solution sachet (2 sachets); HI70300S storage solution for pH & ORP electrodes (25 mL); HI7082 3.5M KCl electrolyte solution (30 mL); HI764833 polarographic DO probe; membrane cap with O‑ring (2 pcs.); HI7041S electrolyte solution (30 mL); HI764060 electrode holder with following accessories: base plate (integrated pivot pin) and screw (requires installation), cable holder clip (attached), electrode holder with adapter, attached, capillary pipette; 24 VDC power adapter; USB-C to USB-A cable; probe quality certificate; quick reference guide with instrument quality certificate. 115V'),
('HI6542P-02', 'd. Bench DO', '1 pH, 1 polarographic DO kit: HI6542P-01 (US power plug, main unit only) and HI6542P-02 (EU power plug, main unit only) is supplied with one HI6000-2 pH/ISE module and one HI6000-4 DO module; HI1131B pH electrode; HI7662-TW temperature probe; pH calibration starter kit consisting of: pH 4.01 buffer solution (2 sachets), pH 7.01 buffer solution sachet (4 sachets), pH 10.01 buffer solution sachet (2 sachets); HI700601 electrode cleaning solution sachet (2 sachets); HI70300S storage solution for pH & ORP electrodes (25 mL); HI7082 3.5M KCl electrolyte solution (30 mL); HI764833 polarographic DO probe; membrane cap with O‑ring (2 pcs.); HI7041S electrolyte solution (30 mL); HI764060 electrode holder with following accessories: base plate (integrated pivot pin) and screw (requires installation), cable holder clip (attached), electrode holder with adapter, attached, capillary pipette; 24 VDC power adapter; USB-C to USB-A cable; probe quality certificate; quick reference guide with instrument quality certificate. 230V'),
('HI2640', 'd. Bench DO', 'Dissolved Oxygen Benchtop Meter includes HI764080 Dissolved Oxygen Electrode, USB C to C Cable 1.5 m'),
('HI2003-01', 'd. Bench EC', 'edge dedicated EC, 115V'),
('HI2003-02', 'd. Bench EC', 'edge dedicated EC, 230V'),
('HI2003-03', 'd. Bench EC', 'edge dedicated EC - w/o Electrode'),
('HI2030-01', 'd. Bench EC', 'edge EC, 115V'),
('HI2030-02', 'd. Bench EC', 'edge EC, 230V'),
('HI2630-01', 'd. Bench EC', 'Conductivity Benchtop Meter includes HI763100 Conductivity Probe, 1413 μS/cm Conductivity Standard Sachets (4), 12880 μS/cm Conductivity Standard Sachets (2), 5000 μS/cm Conductivity Standard Sachets (2), Electrode Rinse Solution Sachets (2), Electrode Holder, USB C Power Adapter, USB C to C Cable 1.5 m, 115V'),
('HI2630-02', 'd. Bench EC', 'Conductivity Benchtop Meter includes HI763100 Conductivity Probe, 1413 μS/cm Conductivity Standard Sachets (4), 12880 μS/cm Conductivity Standard Sachets (2), 5000 μS/cm Conductivity Standard Sachets (2), Electrode Rinse Solution Sachets (2), Electrode Holder, USB C Power Adapter, USB C to C Cable 1.5 m, 230V'),
('HI2631-01', 'd. Bench EC', 'Conductivity + Logging Benchtop Meter includes HI763100 Conductivity Probe, 1413 μS/cm Conductivity Standard Sachets (4), 12880 μS/cm Conductivity Standard Sachets (2), 5000 μS/cm Conductivity Standard Sachets (2), Electrode Rinse Solution Sachets (2), Electrode Holder, USB C Power Adapter, USB C to C Cable 1.5 m, 115V'),
('HI2631-02', 'd. Bench EC', 'Conductivity + Logging Benchtop Meter includes HI763100 Conductivity Probe, 1413 μS/cm Conductivity Standard Sachets (4), 12880 μS/cm Conductivity Standard Sachets (2), 5000 μS/cm Conductivity Standard Sachets (2), Electrode Rinse Solution Sachets (2), Electrode Holder, USB C Power Adapter, USB C to C Cable 1.5 m, 230V'),
('HI6321-01', 'd. Bench EC', 'Advanced Conductivity/Resistivity/TDS/Salinity/Temperature Benchtop Meter with HI7631233 EC Probe, 7-inch Color Display, 800 x 480p Resolution, Capacitive Multi-touch Screen and Keys, Ethernet and Wi-Fi Connection, USB type A & type C, 115V'),
('HI6321-02', 'd. Bench EC', 'Advanced Conductivity/Resistivity/TDS/Salinity/Temperature Benchtop Meter with HI7631233 EC Probe, 7-inch Color Display, 800 x 480p Resolution, Capacitive Multi-touch Screen and Keys, Ethernet and Wi-Fi Connection, USB type A & type C, 230V'),
('HI6321-03', 'd. Bench EC', 'Advanced Conductivity/Resistivity/TDS/Salinity/Temperature Benchtop Meter - w/o Electrode'),
('HI2630', 'd. Bench EC', 'Conductivity Benchtop Meter includes HI763100 Conductivity Probe, USB C to C Cable 1.5 m'),
('HI122-01', 'd. Bench pH', 'Professional Benchtop pH/mV Meter with Built-in Printer, 115V'),
('HI122-02', 'd. Bench pH', 'Wide screen printing pH benchtop meter, CAL Check™, 5 point automatic calibration, range: -2.00 to 16.00 pH / -2.000 to 16.000 pH, mV ±999.9 and ±2000 mV, 230V'),
('HI2002-01', 'd. Bench pH', 'edge dedicated pH, 115V'),
('HI2002-02', 'd. Bench pH', 'edge dedicated pH, 230V'),
('HI2002-03', 'd. Bench pH', 'edge dedicated pH - w/o Electrode'),
('HI2020-01', 'd. Bench pH', 'edge® Multiparameter pH Meter, 115V'),
('HI2020-02', 'd. Bench pH', 'edge® Multiparameter pH Meter, 230V'),
('HI2020-03', 'd. Bench pH', 'edge dedicated pH/EC/DO - w/o Electrode'),
('HI2600-01', 'd. Bench pH', 'pH/EC/DO Benchtop Meter includes HI11310 Glass Body Refillable pH Electrode, pH 4 Buffer Solution Sachets (2), pH 7 Buffer Solution Sachets (4), pH 10 Buffer Solution Sachets (2), Electrode Cleaning Solution Sachets (2), Electrode Holder, USB C Power Adapter, USB C to C Cable 1.5 m, 115V'),
('HI2600-02', 'd. Bench pH', 'pH/EC/DO Benchtop Meter includes HI11310 Glass Body Refillable pH Electrode, pH 4 Buffer Solution Sachets (2), pH 7 Buffer Solution Sachets (4), pH 10 Buffer Solution Sachets (2), Electrode Cleaning Solution Sachets (2), Electrode Holder, USB C Power Adapter, USB C to C Cable 1.5 m, 230V'),
('HI2620-01', 'd. Bench pH', 'pH Benchtop Meter includes HI11310 Glass Body Refillable pH Electrode, pH 4 Buffer Solution Sachets (2), pH 7 Buffer Solution Sachets (4), pH 10 Buffer Solution Sachets (2), Electrode Cleaning Solution Sachets (2), Electrode Holder, USB C Power Adapter, USB C to C Cable 1.5 m, 115V'),
('HI2620-02', 'd. Bench pH', 'pH Benchtop Meter includes HI11310 Glass Body Refillable pH Electrode, pH 4 Buffer Solution Sachets (2), pH 7 Buffer Solution Sachets (4), pH 10 Buffer Solution Sachets (2), Electrode Cleaning Solution Sachets (2), Electrode Holder, USB C Power Adapter, USB C to C Cable 1.5 m, 230V'),
('HI2621-01', 'd. Bench pH', 'pH + Logging Benchtop Meter includes HI11310 Glass Body Refillable pH Electrode, pH 4 Buffer Solution Sachets (2), pH 7 Buffer Solution Sachets (4), pH 10 Buffer Solution Sachets (2), Electrode Cleaning Solution Sachets (2), Electrode Holder, USB C Power Adapter, USB C to C Cable 1.5 m, 115V'),
('HI2621-02', 'd. Bench pH', 'pH + Logging Benchtop Meter includes HI11310 Glass Body Refillable pH Electrode, pH 4 Buffer Solution Sachets (2), pH 7 Buffer Solution Sachets (4), pH 10 Buffer Solution Sachets (2), Electrode Cleaning Solution Sachets (2), Electrode Holder, USB C Power Adapter, USB C to C Cable 1.5 m, 230V'),
('HI6221-01', 'd. Bench pH', 'Advanced pH/ORP/Temperature Benchtop Meter, 7-inch Color Display, 800 x 480p Resolution, Capacitive Multi-touch Screen and Keys, Ethernet and Wi-Fi Connection, USB type A & type C, 115V'),
('HI6221-02', 'd. Bench pH', 'Advanced pH/ORP/Temperature Benchtop Meter, 7-inch Color Display, 800 x 480p Resolution, Capacitive Multi-touch Screen and Keys, Ethernet and Wi-Fi Connection, USB type A & type C, 230V'),
('HI6221-03', 'd. Bench pH', 'Advanced pH/ORP/Temperature Benchtop Meter- w/o Electrode'),
('HI6222-01', 'd. Bench pH', 'Kit supplied with two HI6000-2 pH/ISE modules; HI1131B pH electrode; HI7662-TW temperature probe; pH calibration starter kit consisting of: pH 4.01 buffer solution (2 sachets), pH 7.01 buffer solution sachet (4 sachets), pH 10.01 buffer solution sachet (2 sachets); HI700601 electrode cleaning solution sachet (2 sachets); HI70300S storage solution for pH & ORP electrodes (25 mL); HI7082 3.5M KCl electrolyte solution (30 mL); HI7631233 EC and resistivity probe; EC calibration starter kit consisting of: 1413 μS/cm standard solution (4 sachets), 12880 μS/cm standard solution (2 sachets), 5000 μS/cm standard solution (2 sachets); electrode rinse solution (2 sachets); HI764060 electrode holder with following accessories: base plate (integrated pivot pin) and screw (requires installation), cable holder clip (attached), electrode holder with adapter, attached, capillary pipette; 24 VDC power adapter; USB-C to USB-A cable; probe quality certificate; quick reference guide with instrument quality certificate. 115V'),
('HI6222-02', 'd. Bench pH', 'Kit supplied with two HI6000-2 pH/ISE modules; HI1131B pH electrode; HI7662-TW temperature probe; pH calibration starter kit consisting of: pH 4.01 buffer solution (2 sachets), pH 7.01 buffer solution sachet (4 sachets), pH 10.01 buffer solution sachet (2 sachets); HI700601 electrode cleaning solution sachet (2 sachets); HI70300S storage solution for pH & ORP electrodes (25 mL); HI7082 3.5M KCl electrolyte solution (30 mL); HI7631233 EC and resistivity probe; EC calibration starter kit consisting of: 1413 μS/cm standard solution (4 sachets), 12880 μS/cm standard solution (2 sachets), 5000 μS/cm standard solution (2 sachets); electrode rinse solution (2 sachets); HI764060 electrode holder with following accessories: base plate (integrated pivot pin) and screw (requires installation), cable holder clip (attached), electrode holder with adapter, attached, capillary pipette; 24 VDC power adapter; USB-C to USB-A cable; probe quality certificate; quick reference guide with instrument quality certificate. 230V'),
('HI2620', 'd. Bench pH', 'pH Benchtop Meter includes HI11310 Glass Body Refillable pH Electrode, USB C to C Cable 1.5 m'),
('HI6000-01', 'd. Bench pH/EC', 'HI6000-01 is supplied with HI764060 electrode holder, 24 VDC power adapter, USB-C to USB-A cable, instrument quality certificate, quick reference with QR code for manual download. 115V'),
('HI6000-02', 'd. Bench pH/EC', 'HI6000-01 is supplied with HI764060 electrode holder, 24 VDC power adapter, USB-C to USB-A cable, instrument quality certificate, quick reference with QR code for manual download. 230V'),
('HI6522-01', 'd. Bench pH/EC', 'Kit supplied with one HI6000-2 pH/ISE module and one HI6000-3 EC module; HI1131B pH electrode; HI7662-TW temperature probe; pH calibration starter kit consisting of: pH 4.01 buffer solution (2 sachets), pH 7.01 buffer solution sachet (4 sachets), pH 10.01 buffer solution sachet (2 sachets); HI700601 electrode cleaning solution sachet (2 sachets); HI70300S storage solution for pH & ORP electrodes (25 mL); HI7082 3.5M KCl electrolyte solution (30 mL); HI7631233 EC and resistivity probe; EC calibration starter kit consisting of: 1413 μS/cm standard solution (4 sachets), 12880 μS/cm standard solution (2 sachets), 5000 μS/cm standard solution (2 sachets); electrode rinse solution (2 sachets); HI764060 electrode holder with following accessories: base plate (integrated pivot pin) and screw (requires installation), cable holder clip (attached), electrode holder with adapter, attached, capillary pipette; 24 VDC power adapter; USB-C to USB-A cable; probe quality certificate; quick reference guide with instrument quality certificate. 115V'),
('HI6522-02', 'd. Bench pH/EC', 'Kit supplied with one HI6000-2 pH/ISE module and one HI6000-3 EC module; HI1131B pH electrode; HI7662-TW temperature probe; pH calibration starter kit consisting of: pH 4.01 buffer solution (2 sachets), pH 7.01 buffer solution sachet (4 sachets), pH 10.01 buffer solution sachet (2 sachets); HI700601 electrode cleaning solution sachet (2 sachets); HI70300S storage solution for pH & ORP electrodes (25 mL); HI7082 3.5M KCl electrolyte solution (30 mL); HI7631233 EC and resistivity probe; EC calibration starter kit consisting of: 1413 μS/cm standard solution (4 sachets), 12880 μS/cm standard solution (2 sachets), 5000 μS/cm standard solution (2 sachets); electrode rinse solution (2 sachets); HI764060 electrode holder with following accessories: base plate (integrated pivot pin) and screw (requires installation), cable holder clip (attached), electrode holder with adapter, attached, capillary pipette; 24 VDC power adapter; USB-C to USB-A cable; probe quality certificate; quick reference guide with instrument quality certificate. 230V'),
('HI6553-01', 'd. Bench pH/EC', 'Kit supplied with one HI6000-2 pH/ISE module, one HI6000-3 EC module and one HI6000-4 DO module; HI1131B pH electrode; HI7662-TW temperature probe; pH calibration starter kit consisting of: pH 4.01 buffer solution (2 sachets), pH 7.01 buffer solution sachet (2 sachets), pH 10.01 buffer solution sachet (2 sachets); HI700601 electrode cleaning solution sachet (2 sachets); HI70300S storage solution for pH & ORP electrodes (25 mL); HI7082 3.5M KCl electrolyte solution (30 mL); HI7631233 EC and resistivity probe; EC calibration starter kit consisting of: 1413 μS/cm standard solution (2 sachets), 12880 μS/cm standard solution (2 sachets), 5000 μS/cm standard solution (2 sachets); electrode rinse solution (2 sachets); HI7641133 optical DO probe (opdo®); HI764113‑1 Smart Cap™ with O‑ring; calibration / storage vessel; syringe, lens wipe, silicone grease (6 g sachet); DO Smart Cap quality certificate; HI764060 electrode holder with following accessories: base plate (integrated pivot pin) and screw (requires installation), cable holder clip (attached), electrode holder with adapter, attached, capillary pipette; 24 VDC power adapter; USB-C to USB-A cable; probe quality certificate; quick reference guide with instrument quality certificate. 115V'),
('HI6553-02', 'd. Bench pH/EC', 'Kit supplied with one HI6000-2 pH/ISE module, one HI6000-3 EC module and one HI6000-4 DO module; HI1131B pH electrode; HI7662-TW temperature probe; pH calibration starter kit consisting of: pH 4.01 buffer solution (2 sachets), pH 7.01 buffer solution sachet (2 sachets), pH 10.01 buffer solution sachet (2 sachets); HI700601 electrode cleaning solution sachet (2 sachets); HI70300S storage solution for pH & ORP electrodes (25 mL); HI7082 3.5M KCl electrolyte solution (30 mL); HI7631233 EC and resistivity probe; EC calibration starter kit consisting of: 1413 μS/cm standard solution (2 sachets), 12880 μS/cm standard solution (2 sachets), 5000 μS/cm standard solution (2 sachets); electrode rinse solution (2 sachets); HI7641133 optical DO probe (opdo®); HI764113‑1 Smart Cap™ with O‑ring; calibration / storage vessel; syringe, lens wipe, silicone grease (6 g sachet); DO Smart Cap quality certificate; HI764060 electrode holder with following accessories: base plate (integrated pivot pin) and screw (requires installation), cable holder clip (attached), electrode holder with adapter, attached, capillary pipette; 24 VDC power adapter; USB-C to USB-A cable; probe quality certificate; quick reference guide with instrument quality certificate. 230V'),
('HI6553P-01', 'd. Bench pH/EC', 'Kit supplied with one HI6000-2 pH/ISE module, one HI6000-3 EC module and one HI6000-4 DO module; HI1131B pH electrode; HI7662-TW temperature probe; pH calibration starter kit consisting of: pH 4.01 buffer solution (2 sachets), pH 7.01 buffer solution sachet (2 sachets), pH 10.01 buffer solution sachet (2 sachets); HI700601 electrode cleaning solution sachet (2 sachets); HI70300S storage solution for pH & ORP electrodes (25 mL); HI7082 3.5M KCl electrolyte solution (30 mL); HI7631233 EC and resistivity probe; EC calibration starter kit consisting of: 1413 μS/cm standard solution (2 sachets), 12880 μS/cm standard solution (2 sachets), 5000 μS/cm standard solution (2 sachets); electrode rinse solution (2 sachets); HI764833 polarographic DO probe; membrane cap with O‑ring (2 pcs.); HI7041S electrolyte solution (30 mL); HI764060 electrode holder with following accessories: base plate (integrated pivot pin) and screw (requires installation), cable holder clip (attached), electrode holder with adapter, attached, capillary pipette; 24 VDC power adapter; USB-C to USB-A cable; probe quality certificate; quick reference guide with instrument quality certificate, 115V'),
('HI6553P-02', 'd. Bench pH/EC', 'Kit supplied with one HI6000-2 pH/ISE module, one HI6000-3 EC module and one HI6000-4 DO module; HI1131B pH electrode; HI7662-TW temperature probe; pH calibration starter kit consisting of: pH 4.01 buffer solution (2 sachets), pH 7.01 buffer solution sachet (2 sachets), pH 10.01 buffer solution sachet (2 sachets); HI700601 electrode cleaning solution sachet (2 sachets); HI70300S storage solution for pH & ORP electrodes (25 mL); HI7082 3.5M KCl electrolyte solution (30 mL); HI7631233 EC and resistivity probe; EC calibration starter kit consisting of: 1413 μS/cm standard solution (2 sachets), 12880 μS/cm standard solution (2 sachets), 5000 μS/cm standard solution (2 sachets); electrode rinse solution (2 sachets); HI764833 polarographic DO probe; membrane cap with O‑ring (2 pcs.); HI7041S electrolyte solution (30 mL); HI764060 electrode holder with following accessories: base plate (integrated pivot pin) and screw (requires installation), cable holder clip (attached), electrode holder with adapter, attached, capillary pipette; 24 VDC power adapter; USB-C to USB-A cable; probe quality certificate; quick reference guide with instrument quality certificate, 230V'),
('HI9142', 'e. Portables DO', 'Manual calibration dissolved oxygen meter, Range 0.0 to 19.9 mg/L'),
('HI9146-04', 'e. Portables DO', 'Microprocessor dissolved oxygen meter; probe w/ 4 m cable, Range: O2 0.00 to 45.00 mg/L % Saturation O2 0.0 to 300.0% Temp 0.0 to 50.0°C'),
('HI9146-10', 'e. Portables DO', 'Microprocessor dissolved oxygen meter; probe w/ 10 m cable, Range: O2 0.00 to 45.00 mg/L % Saturation O2 0.0 to 300.0% Temp 0.0 to 50.0°C'),
('HI9147-04', 'e. Portables DO', 'Dissolved oxygen meter for aquaculture; 4 m probe cable, Range: O2: 0.0 to 50.0 mg/L; % Saturation O2: 0 to 600 %; Temp: -5.0 to 50.0°C'),
('HI9147-10', 'e. Portables DO', 'Dissolved oxygen meter for aquaculture; 10 m probe cable, Range: O2: 0.0 to 50.0 mg/L; % Saturation O2: 0 to 600 %; Temp: -5.0 to 50.0°C'),
('HI9147-15', 'e. Portables DO', 'Dissolved oxygen meter for aquaculture; 15 m probe cable, Range: O2: 0.0 to 50.0 mg/L; % Saturation O2: 0 to 600 %; Temp: -5.0 to 50.0°C'),
('HI98193', 'e. Portables DO', 'Waterproof portable dissolved oxygen and BOD meter; Range: DO 0.00 to 50.00 ppm; 0.0 to 600.0 % Saturation; Barometric Pressure 450 to 850 mmHg; Salinity Compensation 0 to 70 ppt (g/L); Temp -20.0 to 120.0°C (-4.0 to 248.0°F)'),
('HI98193/10', 'e. Portables DO', 'Waterproof portable dissolved oxygen and BOD meter supplied with HI764073/10 probe with 10 meter cable'),
('HI98193-03', 'e. Portables DO', 'Waterproof portable dissolved oxygen and BOD Meter - w/o Electrode'),
('HI98198', 'e. Portables DO', 'OPDO Portable Optical Dissolved Oxygen Meter with probe'),
('HI98198/10', 'e. Portables DO', 'OPDO portable optical DO meter with 10m Cable'),
('HI98198-03', 'e. Portables DO', 'OPDO Portable Optical Dissolved Oxygen Meter- w/o Probe'),
('HI740211', 'e. Portables DO Spares', 'Cap (transparent) for DO probes'),
('HI76407/10', 'e. Portables DO Spares', 'Dissolved oxygen probe with 10 m cable for use with HI9142, HI9143, HI9145, HI9141, HI91410'),
('HI76407/10F', 'e. Portables DO Spares', 'DO probe with protective sheath, 10 m cable, for use with HI9146'),
('HI76407/2', 'e. Portables DO Spares', 'Dissolved oxygen probe with 2 m cable for use with HI2400'),
('HI76407/20', 'e. Portables DO Spares', 'Dissolved oxygen probe with 20 m cable for use with HI9142, HI9143, HI9145, HI9141, HI91410'),
('HI76407/20F', 'e. Portables DO Spares', 'DO probe with protective sheath, 20 m cable, for use with HI9146'),
('HI76407/4', 'e. Portables DO Spares', 'Dissolved oxygen probe with 4 m cable for use with HI9142, HI9143, HI9145, HI9141, HI91410'),
('HI76407/4F', 'e. Portables DO Spares', 'DO probe with protective sheath, 4 m cable, for use with HI9146'),
('HI764073', 'e. Portables DO Spares', 'Dissolved oxygen probe with 4 m cable for use with HI98193'),
('HI764073/10', 'e. Portables DO Spares', 'Dissolved oxygen probe with 10 m cable for use with HI98193'),
('HI76407A/P', 'e. Portables DO Spares', 'Membrane for DO Probes; this kit contains 5 ready-to-use, replacement PTFE membranes.'),
('HI76408', 'e. Portables DO Spares', 'Dissolved oxygen probe for laboratories, 1 m cable, for use with HI2400'),
('HI764080', 'e. Portables DO Spares', 'Digital DO probe for edge'),
('HI764080A/P', 'e. Portables DO Spares', 'Spare membranes (2 pcs) for HI764080'),
('HI76408W', 'e. Portables DO Spares', 'Dissolved Oxygen Probe, BOD Test for HI2400 .'),
('HI76409/10', 'e. Portables DO Spares', 'Galvanic Dissolved Oxygen probe with built-in Temperature sensor, 10 m cable for HI9147'),
('HI76409/4', 'e. Portables DO Spares', 'Galvanic Dissolved Oxygen probe with built-in Temperature sensor, 4 m cable for HI9147'),
('HI76409-0', 'e. Portables DO Spares', 'Sleeve, protective sleeve for HI76409, xx Dissolved Oxygen probe series'),
('HI76409A/P', 'e. Portables DO Spares', 'Membrane, 5 pcs'),
('HI764103', 'e. Portables DO Spares', 'Digital dissolved oxygen probe for HI98199'),
('HI764103/10', 'e. Portables DO Spares', 'Digital galvanic dissolved oxygen probe for HI98199, 10 m cable'),
('HI764113', 'e. Portables DO Spares', 'Optical DO probe with built-in temperature sensor, shield and 4 m (13’4) cable'),
('HI764113/10', 'e. Portables DO Spares', 'Optical DO probe with built-in temperature sensor, shield and 10 m (32.8'') cable'),
('HI764113/20', 'e. Portables DO Spares', 'Optical DO probe with built-in temperature sensor, shield and 20 m (65.6'') cable'),
('HI764113-1', 'e. Portables DO Spares', 'Smart Cap with O-ring for HI764113 optical DO probe'),
('HI764113-2', 'e. Portables DO Spares', 'Calibration/Storage vessel for HI764113 optical DO probe'),
('HI7641133', 'e. Portables DO Spares', 'Optical Dissolved Oxygen Probe for HI6421'),
('HI764113-3', 'e. Portables DO Spares', 'Stainless Steel Protective Shield for HI764113 optical DO probe'),
('HI76483', 'e. Portables DO Spares', 'Dissolved oxygen probe for HI5421'),
('HI764833', 'e. Portables DO Spares', 'Polarographic Dissolved Oxygen Probe for HI6421P'),
('HI76483A/P', 'e. Portables DO Spares', 'Spare membrane caps (5 pcs) for HI76483 DO Probe'),
('HI8733', 'e. Portables EC', 'Multi-range EC meter with HI76302W probe, Range: 0.0 to 199.9 mS/cm w/ATC'),
('HI8734', 'e. Portables EC', 'TDS meter, Range: 0.0 to 199.9 mg/L (ppm); 0 to 1999 mg/L (ppm); 0.00 to 19.99 g/L (ppt)'),
('HI98192', 'e. Portables EC', 'Waterproof portable EC/resistivity/TDS/NaCl auto ranging meter with graphic display'),
('HI98192-03', 'e. Portables EC', 'Waterproof portable EC/resistivity/TDS/NaCl Meter - w/o Electrode'),
('HI98197', 'e. Portables EC', 'Professional Resistivity meter with flow through cell'),
('HI99300', 'e. Portables EC', 'EC/TDS/Temperature meter; EC unit: µS/cm, TDS unit: ppm, Range: 0 to 3999 μS/cm, TDS 0 to 2000 ppm (mg/L), Temp 0.0 to 60.0°C / 32.0 to 140.0°F'),
('HI99301', 'e. Portables EC', 'EC/TDS/Temperature meter; EC unit: mS/cm, TDS unit: ppt, Range: EC 0.00 to 20.00 mS/cm, TDS 0.00 to 10.00 ppt (g/L), Temp 0.0 to 60.0°C / 32.0 to 140.0°F'),
('HI8314-1', 'e. Portables pH', 'Analog pH/mV/°C meter with HI1217-1 electrode, range: pH 0.00 to 14.00 pH, mV ±1999 mV, Temperature 0.0 to 100.0°C'),
('HI83141-1', 'e. Portables pH', 'Analog pH/mV/°C meter with HI1230B electrode, range: pH 0.00 to 14.00 pH, mV ±1999 mV, Temperature 0.0 to 100.0°C'),
('HI8424', 'e. Portables pH', 'Microprocessor pH/mV meter, automatic calibration, ATC, range: pH -2.00 to 16.00 pH, mV ±699.9 mV; ±1999 mV'),
('HI931001', 'e. Portables pH', 'pH and mV precision simulator with a pH resolution of ±0.01 and an mV resolution of 1, range: pH 0.00 to 14.00 pH, mV -1000 to 1000'),
('HI9310014', 'e. Portables pH', 'Pool Line pH and mV precision simulator with a pH resolution of ±0.01 and an mV resolution of 1, range: pH 0.00 to 14.00 pH, mV -1000 to 1000'),
('HI98161', 'e. Portables pH', 'Professional Foodcare Portable pH Meter'),
('HI98161-03', 'e. Portables pH', 'Professional Foodcare Portable pH Meter - w/o Electrode'),
('HI98162', 'e. Portables pH', 'Professional Portable Milk pH Meter'),
('HI98163', 'e. Portables pH', 'Professional Portable Meat pH Meter'),
('HI98164', 'e. Portables pH', 'Professional Portable Yogurt pH Meter'),
('HI98165', 'e. Portables pH', 'Professional Portable Cheese pH Meter'),
('HI98167', 'e. Portables pH', 'Professional Portable Beer pH Meter'),
('HI98168', 'e. Portables pH', 'Professional Portable Soil pH Meter'),
('HI98169', 'e. Portables pH', 'Professional portable pH meter for wine analysis'),
('HI98190', 'e. Portables pH', 'Professional Waterproof Portable pH/ORP Meter'),
('HI98190-03', 'e. Portables pH', 'Professional Waterproof Portable pH/ORP Meter - w/o Electrode'),
('HI98191', 'e. Portables pH', 'Professional Waterproof Portable pH/ORP/ISE Meter'),
('HI98191-03', 'e. Portables pH', 'Professional Waterproof Portable pH/ORP/ISE Meter - w/o Electrode'),
('HI981914', 'e. Portables pH', 'Pool Line Professional Waterproof Portable pH/ORP/ISE Meter'),
('HI98199', 'e. Portables pH', 'Digital pH,EC,DO portable meter with HI829113 pH electrode'),
('HI98199-03', 'e. Portables pH', 'Digital pH,EC,DO portable meter - w/o Electrode'),
('HI98263', 'e. Portables pH', 'Professional Bluetooth Portable Meat pH Meter'),
('HI991001', 'e. Portables pH', 'Waterproof Portable pH/Temperature Meter'),
('HI991001-03', 'e. Portables pH', 'Waterproof Portable pH/Temperature Meter - w/o Electrode'),
('HI991001-30', 'e. Portables pH', 'Extended Range Waterproof Portable pH/Temperature Meter with HI12303 Probe'),
('HI991003', 'e. Portables pH', 'Waterproof Portable pH/pH-mV/ORP/Temperature Meter with Sensor Check™'),
('HI99111', 'e. Portables pH', 'pH meter for wine analysis, range pH -2.00 to 16.00 pH, with FC10483 pH electrode'),
('HI99121', 'e. Portables pH', 'Direct Soil Measurement pH Portable Meter'),
('HI99131', 'e. Portables pH', 'Plating pH Portable Meter'),
('HI99141', 'e. Portables pH', 'Boiler and Cooling Tower pH Portable Meter'),
('HI99151', 'e. Portables pH', 'Beer Analysis pH Portable Meter'),
('HI99161', 'e. Portables pH', 'Food and Dairy pH Portable Meter (HACCP)'),
('HI99161-03', 'e. Portables pH', 'Food and Dairy pH Portable Meter - w/o Electrode'),
('HI99162', 'e. Portables pH', 'Milk pH Portable Meter (HACCP)'),
('HI99163', 'e. Portables pH', 'Meat pH Portable Meter (HACCP)'),
('HI99164', 'e. Portables pH', 'Yogurt pH Portable Meter (HACCP)'),
('HI99165', 'e. Portables pH', 'Cheese pH Portable Meter (HACCP)'),
('HI99171', 'e. Portables pH', 'Leather and Paper pH Portable Meter'),
('HI99181', 'e. Portables pH', 'Skin pH Portable Meter'),
('HI99192', 'e. Portables pH', 'Drinking Water pH Portable Meter'),
('HI4002', 'f. ISE''s', 'Bromide Half-Cell Ion Selective Electrode, Solid State'),
('HI4003', 'f. ISE''s', 'Cadmium Half-Cell Ion Selective Electrode, Solid State'),
('HI4004', 'f. ISE''s', 'Calcium Half-Cell Ion Selective Electrode, Polymer Membrane'),
('HI4007', 'f. ISE''s', 'Chloride Half-Cell Ion Selective Electrode, Solid State'),
('HI4008', 'f. ISE''s', 'Cupric Half-Cell Ion Selective Electrode, Solid State'),
('HI4009', 'f. ISE''s', 'Cyanide Half-Cell Ion Selective Electrode, Solid State'),
('HI4010', 'f. ISE''s', 'Fluoride Half-Cell Ion Selective Electrode, Solid State'),
('HI4011', 'f. ISE''s', 'Iodide Half-Cell Ion Selective Electrode, Solid State'),
('HI4012', 'f. ISE''s', 'Lead/Sulfate Half-Cell Ion Selective Electrode, Solid State'),
('HI4013', 'f. ISE''s', 'Nitrate Half-Cell Ion Selective Electrode, Polymer Membrane'),
('HI4014', 'f. ISE''s', 'Potassium Half-Cell Ion Selective Electrode, Polymer Membrane'),
('HI4015', 'f. ISE''s', 'Silver/Sulfide Half-Cell Ion Selective Electrode, Solid State'),
('HI4101', 'f. ISE''s', 'Ammonia Combination Ion Selective Electrode, Gas Sensing'),
('HI4102', 'f. ISE''s', 'Bromide Combination Ion Selective Electrode, Solid State'),
('HI4103', 'f. ISE''s', 'Cadmium Combination Ion Selective Electrode, Solid State'),
('HI4104', 'f. ISE''s', 'Calcium Combination Ion Selective Electrode, Polymer Membrane'),
('HI4105', 'f. ISE''s', 'Carbon Dioxide Combination Ion Selective Electrode, Gas Sensing'),
('HI4107', 'f. ISE''s', 'Chloride Combination Ion Selective Electrode, Solid State'),
('HI4108', 'f. ISE''s', 'Cupric Combination Ion Selective Electrode, Solid State'),
('HI4109', 'f. ISE''s', 'Cyanide Combination Ion Selective Electrode, Solid State'),
('HI4110', 'f. ISE''s', 'Fluoride Combination Ion Selective Electrode, Solid State'),
('HI4111', 'f. ISE''s', 'Iodide Combination Ion Selective Electrode, Solid State'),
('HI4112', 'f. ISE''s', 'Lead/Sulfate Combination Ion Selective Electrode, Solid State'),
('HI4113', 'f. ISE''s', 'Nitrate Combination Ion Selective Electrode, Polymer Membrane'),
('HI4114', 'f. ISE''s', 'Potassium Combination Ion Selective Electrode, Polymer Membrane'),
('HI4115', 'f. ISE''s', 'Silver/Sulfide Combination Ion Selective Electrode, Solid State'),
('HI5315', 'f. ISE''s', 'Reference Electrode for ISE Half-Cells'),
('HI4000-00', 'f. ISE''s Accessories', 'Ionic Strength Adjuster (ISA) for Halide ISEs'),
('HI4000-47', 'f. ISE''s Accessories', 'ISE Slope Check Buffers with Chloride Background'),
('HI4000-50', 'f. ISE''s Accessories', 'Liquid Membrane ISE Sensor Handle'),
('HI4000-51', 'f. ISE''s Accessories', 'Replacement pH Assembly for Ammonia ISE'),
('HI4000-52', 'f. ISE''s Accessories', 'Replacement Membrane Cap for Ammonia ISE'),
('HI4000-54', 'f. ISE''s Accessories', 'Replacement pH Assembly for Carbon Dioxide ISE'),
('HI4000-70', 'f. ISE''s Accessories', 'Halide Polishing Strips (24 pcs)'),
('HI4001-00', 'f. ISE''s Accessories', 'Ionic Strength Adjuster (ISA) for Ammonia and Cyanide ISEs'),
('HI4001-01', 'f. ISE''s Accessories', 'Ammonia ISE 0.1M Standard (500 mL)'),
('HI4001-02', 'f. ISE''s Accessories', 'Ammonia ISE 100 ppm Standard (500 mL)'),
('HI4001-03', 'f. ISE''s Accessories', 'Ammonia ISE 1000 ppm Standard (500 mL)'),
('HI4001-40', 'f. ISE''s Accessories', 'Ammonia ISE Filling Solution (4 x 30 mL Bottles)'),
('HI4001-45', 'f. ISE''s Accessories', 'Ammonia ISE Conditioning and Storage Solution'),
('HI4001-51', 'f. ISE''s Accessories', 'Ammonia ISE Membrane Kit (20 pcs)'),
('HI4002-01', 'f. ISE''s Accessories', 'Bromide ISE 0.1M Standard (500 mL)'),
('HI4003-01', 'f. ISE''s Accessories', 'Cadmium ISE 0.1M Standard (500 mL)'),
('HI4004-00', 'f. ISE''s Accessories', 'Ionic Strength Adjuster (ISA) for Calcium ISEs'),
('HI4004-01', 'f. ISE''s Accessories', 'Calcium ISE 0.1M Standard (500 mL)'),
('HI4004-45', 'f. ISE''s Accessories', 'Calcium ISE Conditioning and Storage Solution'),
('HI4004-51', 'f. ISE''s Accessories', 'Calcium Module for Half-Cell ISE'),
('HI4005-00', 'f. ISE''s Accessories', 'Ionic Strength Adjuster (ISA) for Carbon Dioxide ISEs'),
('HI4005-01', 'f. ISE''s Accessories', 'Carbon Dioxide ISE 0.1M Standard (500 mL)'),
('HI4005-03', 'f. ISE''s Accessories', 'Carbon Dioxide ISE 1000 ppm Standard (500 mL)'),
('HI4005-40', 'f. ISE''s Accessories', 'Carbon Dioxide ISE Filling Solution (4 x 30 mL Bottles)'),
('HI4005-45', 'f. ISE''s Accessories', 'Carbon Dioxide ISE Conditioning and Storage Solution'),
('HI4005-53', 'f. ISE''s Accessories', 'Carbon Dioxide ISE Membrane Kit (3 pcs)'),
('HI4007-01', 'f. ISE''s Accessories', 'Chloride ISE 0.1M Standard (500 mL)'),
('HI4007-02', 'f. ISE''s Accessories', 'Chloride ISE 100 ppm Standard (500 mL)'),
('HI4007-03', 'f. ISE''s Accessories', 'Chloride ISE 1000 ppm Standard (500 mL)'),
('HI4008-01', 'f. ISE''s Accessories', 'Cupric ISE 0.1M Standard (500 mL)'),
('HI4010-00', 'f. ISE''s Accessories', 'TISAB II for Fluoride ISEs (500 mL)'),
('HI4010-01', 'f. ISE''s Accessories', 'Fluoride ISE 0.1M Standard 0.1M (500 mL)'),
('HI4010-02', 'f. ISE''s Accessories', 'Fluoride ISE 100 ppm Standard (500 mL)'),
('HI4010-03', 'f. ISE''s Accessories', 'Fluoride ISE 1000 ppm Standard (500 mL)'),
('HI4010-05', 'f. ISE''s Accessories', 'TISAB II for Fluoride ISEs (1 gallon)'),
('HI4010-06', 'f. ISE''s Accessories', 'TISAB III Concentrate for Fluoride ISEs'),
('HI4010-10', 'f. ISE''s Accessories', 'Fluoride ISE 10 ppm Standard with TISAB II (500 mL)'),
('HI4010-11', 'f. ISE''s Accessories', 'Fluoride ISE 1 ppm Standard with TISAB II (500 mL)'),
('HI4010-12', 'f. ISE''s Accessories', 'Fluoride ISE 2 ppm Standard with TISAB II (500 mL)'),
('HI4010-30', 'f. ISE''s Accessories', 'Fluoride Calibration Solution Kit (1 ppm with TISAB II, 10 ppm with TISAB II, TISAB II) (4 bottles of 500 mL each)'),
('HI4011-01', 'f. ISE''s Accessories', 'Iodide ISE 0.1M Standard (500 mL)'),
('HI4012-00', 'f. ISE''s Accessories', 'Ionic Strength Adjuster (ISA) for Lead/Sulfate ISEs'),
('HI4012-01', 'f. ISE''s Accessories', 'Lead ISE 0.1M Standard (500 mL)'),
('HI4012-21', 'f. ISE''s Accessories', 'Sulfate ISE 0.1M Standard (500 mL)'),
('HI4013-00', 'f. ISE''s Accessories', 'Ionic Strength Adjuster (ISA) for Nitrate ISEs'),
('HI4013-01', 'f. ISE''s Accessories', 'Nitrate ISE 0.1M Standard (500 mL)'),
('HI4013-02', 'f. ISE''s Accessories', 'Nitrate ISE 100 ppm Standard (500 mL)'),
('HI4013-03', 'f. ISE''s Accessories', 'Nitrate ISE 1000 ppm Standard (500 mL)'),
('HI4013-06', 'f. ISE''s Accessories', 'Interferent Suppressant ISA (ISISA) for Nitrate ISEs'),
('HI4013-13', 'f. ISE''s Accessories', 'Nitrate standard 1000 ppm, 500 mL, regular bottle'),
('HI4013-51', 'f. ISE''s Accessories', 'Nitrate Module for Half-Cell ISE (1 piece)'),
('HI4013-53', 'f. ISE''s Accessories', 'Nitrate Module for Half-Cell ISE (3 pcs)'),
('HI4014-00', 'f. ISE''s Accessories', 'Ionic Strength Adjuster (ISA) for Potassium ISEs'),
('HI4014-01', 'f. ISE''s Accessories', 'Potassium ISE 0.1M Standard (500 mL)'),
('HI4014-51', 'f. ISE''s Accessories', 'Potassium Module for Half-Cell ISE'),
('HI4015-00', 'f. ISE''s Accessories', 'Sulfide Antioxidant Buffer (SAOB) for Sulfide ISEs'),
('HI4015-01', 'f. ISE''s Accessories', 'Silver ISE 0.1M Standard (500 mL)'),
('HI4016-00', 'f. ISE''s Accessories', 'Ionic Strength Adjuster (ISA) for Sodium ISEs'),
('HI4016-01', 'f. ISE''s Accessories', 'Sodium ISE 0.1M Standard (500 mL)'),
('HI4016-02', 'f. ISE''s Accessories', 'Sodium ISE 100 ppm Standard (500 mL)'),
('HI4016-03', 'f. ISE''s Accessories', 'Sodium ISE 1000 ppm Standard (500 mL)'),
('HI4016-10', 'f. ISE''s Accessories', 'Sodium ISE 10 ppm Standard (500 mL)'),
('HI4016-45', 'f. ISE''s Accessories', 'Sodium ISE Storage Solution'),
('HI4016-46', 'f. ISE''s Accessories', 'Sodium ISE Conditioning Solution'),
('HI4104-51', 'f. ISE''s Accessories', 'Calcium Module for Combination ISE'),
('HI4110-51', 'f. ISE''s Accessories', 'Fluoride Module for Combination ISE'),
('HI4113-51', 'f. ISE''s Accessories', 'Nitrate Module for Combination ISE (1 piece)'),
('HI4113-53', 'f. ISE''s Accessories', 'Nitrate Module for Combination ISE (3 pcs)'),
('HI4114-51', 'f. ISE''s Accessories', 'Potassium Module for Combination ISE'),
('FC2020', 'g. Electrodes digital', 'Digital PVDF Body Foodcare pH Electrode for Dairy Products'),
('FC2100', 'g. Electrodes digital', 'Digital Glass Body Foodcare pH Electrode for Dairy Products'),
('FC2320', 'g. Electrodes digital', 'Digital PVDF Body Foodcare pH Electrode for Meat Products'),
('HI10430', 'g. Electrodes digital', 'Digital Glass Body pH Electrode for Hydrocarbons and Solvents'),
('HI10480', 'g. Electrodes digital', 'Digital Glass Body pH Electrode with Clogging Prevention System (CPS™)'),
('HI10530', 'g. Electrodes digital', 'Digital Glass Body pH Electrode for Semi-Solids and Emulsions'),
('HI11310', 'g. Electrodes digital', 'Digital Glass Body pH Electrode for General Purpose'),
('HI11311', 'g. Electrodes digital', 'Digital Glass Body pH Electrode with Matching Pin for General Purpose'),
('HI12300', 'g. Electrodes digital', 'Digital PEI Body pH Electrode for Field Applications'),
('HI12301', 'g. Electrodes digital', 'Digital PEI Body pH Electrode with Matching Pin for Field Applications'),
('HI14140', 'g. Electrodes digital', 'Digital pH/temperature flat tip electrode for surface measurement'),
('HI36180', 'g. Electrodes digital', 'Digital Glass Body ORP Electrode for General Purpose'),
('HI36200', 'g. Electrodes digital', 'Digital PEI body, gel filled, ORP electrode'),
('HI763093', 'g. Electrodes digital', 'Digital conductivity/temprature probe for HI98199'),
('HI763093/10', 'g. Electrodes digital', 'Digital Conductivity/temperature probe for HI98199, 10 m cable'),
('HI763100', 'g. Electrodes digital', 'Digital EC probe for edge'),
('HI829113', 'g. Electrodes digital', 'Digital pH/Temp electrode for HI98199'),
('HI829113/10', 'g. Electrodes digital', 'Digital pH/Temp electrode for HI98199, 10 m cable'),
('HI10433', 'g. pH Electrodes', 'Refillable, Combination pH Electrode with Double Junction'),
('HI1043B', 'g. pH Electrodes', 'Refillable Double Junction pH Electrode with BNC Connector'),
('HI1043P', 'g. pH Electrodes', 'Refillable Double Junction pH Electrode with BNC and Pin connectors'),
('HI1048B', 'g. pH Electrodes', 'pH Electrode with Clogging Prevention System (CPS™) and BNC Connector'),
('HI1048B/50', 'g. pH Electrodes', 'Mini Titrator pH electrode, BNC, 0.5 m cable'),
('HI1048P', 'g. pH Electrodes', 'pH Electrode with Clogging Prevention System (CPS™) and BNC + Pin Connector'),
('HI1048S', 'g. pH Electrodes', 'pH electrode with CPS™ (Clogging Prevention System); Use for wine, must, screw connector'),
('HI1048Y', 'g. pH Electrodes', 'pH/Temp Electrode with Clogging Prevention System (CPS™) and BNC and RCA Connector'),
('HI1049B', 'g. pH Electrodes', 'pH electrode with sleeve junction and increased chemcial resistance for non-aqeous ttirations'),
('HI10533', 'g. pH Electrodes', 'pH Electrode with Conical Tip and Quick Connect DIN Connector'),
('HI1053B', 'g. pH Electrodes', 'pH Electrode with Conical Tip and BNC Connector'),
('HI1053P', 'g. pH Electrodes', 'pH Electrode with Conical Tip and BNC + Pin Connector'),
('HI1083B', 'g. pH Electrodes', 'pH Electrode with Micro Bulb and BNC Connector'),
('HI1083P', 'g. pH Electrodes', 'pH Electrode with Micro Bulb and BNC + Pin Connector'),
('HI1093B', 'g. pH Electrodes', 'Extended Length pH Electrode with Micro Bulb and BNC Connector'),
('HI1093P', 'g. pH Electrodes', 'Refillable, combination pH electrode w/ extended length and micro bulb; Use for NMR tubes, BNC + Pin connector'),
('HI11103', 'g. pH Electrodes', 'Gel Filled pH Electrode with Quick Connect DIN Connector'),
('HI1110B', 'g. pH Electrodes', 'Spare electrode, gel electrolyte; Use for general laboratory purposes, BNC connector'),
('HI1110S', 'g. pH Electrodes', 'Glass pH electrode, single junction, screw cap'),
('HI1110T', 'g. pH Electrodes', 'Glass pH electrode, double junction PG13.5 thread'),
('HI11313', 'g. pH Electrodes', 'Refillable Glass Body pH Electrode with Quick Connect DIN Connector'),
('HI1131B', 'g. pH Electrodes', 'Refillable Combination pH Electrode with BNC Connector'),
('HI1131P', 'g. pH Electrodes', 'Refillable Combination pH Electrode with BNC + Pin Connector'),
('HI1131S', 'g. pH Electrodes', 'Refillable, combination pH electrode; Use for general laboratory purposes and beer, screw cap connector'),
('HI1131Y', 'g. pH Electrodes', 'Refillable Combination pH/Temp Electrode with BNC and RCA Connector'),
('HI1135B', 'g. pH Electrodes', 'Refillable pH Electrode with Side Arm Construction and BNC Connector'),
('HI1144B', 'g. pH Electrodes', 'Refillable pH Electrode with Calomel References and BNC Connector'),
('HI1151B', 'g. pH Electrodes', 'Refillable, combination pH electrode for non-aqueous titration applications, BNC connector'),
('HI1192T', 'g. pH Electrodes', 'T-Type electrode, glass body, double junction, polymer electrolyte, -15 to 80°C (5 to 176ºF), 8 bar'),
('HI1210B/5', 'g. pH Electrodes', 'Combination PEI-body pH Electrode, 5 m cable'),
('HI1217-1', 'g. pH Electrodes', 'pH electrode, NTC sensor, gel electrolyte; Use for general purpose, DIN connector'),
('HI1217D', 'g. pH Electrodes', 'pH electrode, gel electrolyte; Use for general purpose, DIN connector'),
('HI12303', 'g. pH Electrodes', 'Gel Filled PEI Body pH Electrode with Quick Connect DIN Connector'),
('HI1230B', 'g. pH Electrodes', 'Gel Filled PEI Body pH Electrode with BNC Connector'),
('HI1230S', 'g. pH Electrodes', 'Combination pH electrode, gel electrolyte; Use for field applications, screw type connector'),
('HI1230Y', 'g. pH Electrodes', 'Gel Filled PEI Body pH/Temp Electrode with BNC and RCA Connector'),
('HI1271', 'g. pH Electrodes', 'HI98100 Checker Plus spare pH electrode with screw connector'),
('HI1286', 'g. pH Electrodes', 'Spare electrode for general purpose, water treatment and agriculture'),
('HI1286/50', 'g. pH Electrodes', 'PoolLine pH Electrode, 50 mm long with 2 m Cable'),
('HI1286T', 'g. pH Electrodes', 'pH electrode, plastic body, double junction, poly, tefrod, 110 mm body length, BNC connector, UNFCAP1R (PG13.5)'),
('HI1291D', 'g. pH Electrodes', 'Gel filled, PEI body pH electrode with DIN connector for HI208'),
('HI12923', 'g. pH Electrodes', 'pH Electrode for Direct Soil Measurement'),
('HI1292D', 'g. pH Electrodes', 'pH Electrode for Direct Soil Measurement'),
('HI1293', 'g. pH Electrodes', 'Spare pH electrode for Hydroponics and greenhouses , DIN connector, for HI991401,HI991404,HI991405'),
('HI12943', 'g. pH Electrodes', 'GroLine Direct Soil and Soiless Media pH electrode with quick connect DIN connector for use with HI9814'),
('HI1295', 'g. pH Electrodes', 'Spare Electrode for PICCOLO® plus pH Tester'),
('HI12963', 'g. pH Electrodes', 'Titanium Body pH Electrode for Wastewater with Quick Connect DIN Connector'),
('HI1296D', 'g. pH Electrodes', 'Titanium Body pH Electrode for Wastewater with DIN Connector'),
('HI12973', 'g. pH Electrodes', 'Ttitanium body pH/ORP electrode with quick connect DIN Connector'),
('HI1297D', 'g. pH Electrodes', 'Titanium Body pH/ORP Electrode for Water Treatment Analysis with DIN Connector'),
('HI1312S', 'g. pH Electrodes', 'pH electrode, KCl 3.5M electrolyte; Use for chemicals, field applications, quality control, screw type connector'),
('HI1330B', 'g. pH Electrodes', 'Combination pH electrode, KCl 3.5M + AgCl electrolyte; Specific for vials and test tubes, BNC connector'),
('HI1330P', 'g. pH Electrodes', 'Combination pH electrode, KCl 3.5M + AgCl electrolyte; Specific for vials and test tubes, BNC + PIN connector'),
('HI1331B', 'g. pH Electrodes', 'Refillable pH Electrode for Flasks with BNC Connector'),
('HI1332B', 'g. pH Electrodes', 'Refillable PEI Body pH Electrode with BNC Connector'),
('HI1332D', 'g. pH Electrodes', 'pH combination electrode PEI body, double-junction, refillable, DIN, 1 m cable'),
('HI1332P', 'g. pH Electrodes', 'Refillable PEI Body pH Electrode with BNC + Pin Connector'),
('HI1333B', 'g. pH Electrodes', 'Spare pH electrode, gel electrolyte; Use for field applications, BNC connector'),
('HI1343B', 'g. pH Electrodes', 'PEI Body pH Electrode with Calomel References with BNC Connector'),
('HI1413B', 'g. pH Electrodes', 'Flat Tip pH Electrode for Skin and Surfaces with BNC Connector'),
('HI1413B/50', 'g. pH Electrodes', 'pH electrode, viscolene electrolyte; Use for skin and scalp, BNC connector'),
('HI1413S/50', 'g. pH Electrodes', 'pH electrode, viscolene electrolyte; Use for skin and scalp, screw type connector'),
('HI14143', 'g. pH Electrodes', 'Pulp & Paper flat tip pH electrode with quick connect DIN connector'),
('HI14143/50', 'g. pH Electrodes', 'Skin & Scalp flat tip pH electrode with quick connect DIN connector'),
('HI1414D', 'g. pH Electrodes', 'Flat Tip pH Electrode for Skin and Surfaces with DIN Connector'),
('HI1610D', 'g. pH Electrodes', 'pH Electrode with Built-In Temperature Sensor and DIN Connector'),
('HI2031B', 'g. pH Electrodes', 'Spear Tip pH Electrode for Semi-Solid Samples with BNC Connector'),
('HI2111B', 'g. pH Electrodes', 'Glass Body pH Half-Cell Electrode with BNC Connector'),
('HI2112B', 'g. pH Electrodes', 'PEI Body pH Half-Cell Electrode with BNC Connector'),
('HI2114P', 'g. pH Electrodes', 'Spare electrode for general purpose and agriculture'),
('HI2114P/5', 'g. pH Electrodes', 'Spare electrode for general purpose and agriculture, 5 m cable'),
('HI3131B', 'g. pH Electrodes', 'Refillable Combination ORP Electrode with BNC Connector'),
('HI3133B', 'g. pH Electrodes', 'Platinum ORP Half-Cell Electrode with BNC Connector'),
('HI3148B', 'g. pH Electrodes', 'ORP Electrode with Clogging Prevention System (CPS™) and BNC Connector'),
('HI3148B/50', 'g. pH Electrodes', 'ORP Electrode with CPS (Clogging Prevention System)'),
('HI3149B', 'g. pH Electrodes', 'ORP electrode with sleeve junction and increased chemcial resistance for non-aqeous ttirations'),
('HI3214P', 'g. pH Electrodes', 'Spare electrode for general purpose, agriculture and disinfection'),
('HI3214T', 'g. pH Electrodes', 'ORP Platinum electrode, plastic body, double junction, gel, cloth, 110 mm body length, BNC connector, UNFCAP1Y (PG13.5)'),
('HI3214T/2', 'g. pH Electrodes', 'ORP Platinum electrode, plastic body, double junction, gel, cloth, 110 mm body length, BNC connector, UNFCAP1Y (PG13.5) and 2 meters (6’6’’) Cable'),
('HI3230B', 'g. pH Electrodes', 'Gel Filled PEI Body ORP Electrode with BNC Connector'),
('HI3286/50', 'g. pH Electrodes', 'PoolLine ORP Electrode, 50 mm long with Platinum Sensor and 2 m Cable'),
('HI36183', 'g. pH Electrodes', 'Glass Body ORP Electrode with Quick Connect DIN Connector'),
('HI3618D', 'g. pH Electrodes', 'Glass Body ORP Electrode with DIN Connector'),
('HI3618D-1', 'g. pH Electrodes', 'Glass Body ORP Electrode with DIN Connector for HI8314-1'),
('HI36203', 'g. pH Electrodes', 'PEI body, single junction, gel filled, ORP/temperature probe with quick connect'),
('HI4211T', 'g. pH Electrodes', 'ORP Au pin, plastic (PEI) body, screw cap S7 ( PG13.5), gel filled, ref. double junction, cloth junction'),
('HI4430B', 'g. pH Electrodes', 'Gel Filled ORP Electrode with Gold Contact and BNC Connector'),
('HI4430B/3', 'g. pH Electrodes', 'Gel Filled ORP Electrode with Gold Contact and 3 meter cable with BNC Connector'),
('HI4486/50', 'g. pH Electrodes', 'PoolLine ORP Electrode, 50 mm long with Golden Sensor and 2 m Cable'),
('HI5110B', 'g. pH Electrodes', 'Silver ORP Half-Cell Electrode for argentometric titration with BNC Connector'),
('HI5311', 'g. pH Electrodes', 'Glass Body General Purpose Reference Electrode, Use for general purpose, and titration, 4mm banana connector'),
('HI5312', 'g. pH Electrodes', 'Reference Electrode for Samples with Suspended Solids, 4mm banana connector'),
('HI5313', 'g. pH Electrodes', 'PEI Body Reference Electrode for FC301B'),
('HI5314', 'g. pH Electrodes', 'Glass Body Reference Electrode for Measurements with Remote Filling'),
('HI5412', 'g. pH Electrodes', 'Glass Body Calomel Reference Electrode, 4mm banana connector'),
('HI5413', 'g. pH Electrodes', 'Glass Body Calomel Reference Electrode for ISE and Samples with Suspended Solids, 4mm banana connector'),
('HI5414', 'g. pH Electrodes', 'Glass Body Calomel Reference Electrode for Measurements with Remote Filling, 4mm banana connector'),
('HI629113', 'g. pH Electrodes', 'Plating Bath titanium body pH Electrode with quick connect DIN connector'),
('HI629113/2', 'g. pH Electrodes', 'Plating Bath Titanium Body pH Electrode with Quick Connect DIN Connector and 2 meters (6’6’’) Cable'),
('HI62911D', 'g. pH Electrodes', 'Titanium Body pH Electrode for Plating Baths with DIN Connector'),
('HI729113', 'g. pH Electrodes', 'Boiler and Cooling Tower titanium body pH electrode with quick connect DIN connector'),
('HI72911B', 'g. pH Electrodes', 'Titanium Body pH Electrode with BNC + Phono Connector'),
('HI72911D', 'g. pH Electrodes', 'Titanium Body pH Electrode for Boilers and Cooling Towers with DIN Connector'),
('HI73120', 'g. pH Electrodes', 'Electrode (spare) for HI98120'),
('HI73127', 'g. pH Electrodes', 'Electrode (spare) for HI 98121, HI 98127, HI 98128, HI 98129 and HI 98130'),
('FC2022', 'g. pH Electrodes Bluetooth', 'HALO Foodcare pH Electrode with Bluetooth®'),
('FC2142', 'g. pH Electrodes Bluetooth', 'HALO - glass pH/temperature electrode for beer testing, with high temperature glass'),
('HI10482', 'g. pH Electrodes Bluetooth', 'HALO Glass Body pH Electrode with Clogging Prevention System (CPS) and Bluetooth®'),
('HI10532', 'g. pH Electrodes Bluetooth', 'HALO Bluetooth conical tip, refillable pH electrode for semi-solids'),
('HI10832', 'g. pH Electrodes Bluetooth', 'HALO - micro pH electrode, refillable, no temperature, with Bluetooth® Smart Technology'),
('HI11102', 'g. pH Electrodes Bluetooth', 'HALO Glass Body Gel Filled pH Electrode with Bluetooth®'),
('HI11312', 'g. pH Electrodes Bluetooth', 'HALO Glass Body Refillable pH Electrode with Bluetooth®'),
('HI12302', 'g. pH Electrodes Bluetooth', 'HALO PEI Body Gel Filled pH Electrode with Bluetooth®'),
('HI12922', 'g. pH Electrodes Bluetooth', 'HALO - pH/temperature electrode for direct soil pH measurement'),
('HI13302', 'g. pH Electrodes Bluetooth', 'HALO - Glass body pH/Temperature electrode for flasks, with 3 mm tip'),
('HI14142', 'g. pH Electrodes Bluetooth', 'HALO - pH/temperature flat tip electrode for surface measurement'),
('HI9810302', 'g. pH Electrodes Bluetooth', 'HALO2 Wireless pH Tester for Soil with built-in specialized electrode'),
('HI9810312', 'g. pH Electrodes Bluetooth', 'HALO2 Wireless pH Tester for Beer with built-in specialized electrode'),
('HI9810322', 'g. pH Electrodes Bluetooth', 'HALO2 Wireless pH Tester for Cheese with built-in specialized electrode'),
('HI9810332', 'g. pH Electrodes Bluetooth', 'HALO2 Wireless Refillable pH Tester for Wine with built-in specialized electrode'),
('HI9810342', 'g. pH Electrodes Bluetooth', 'HALO2 Wireless pH Tester for Milk with built-in specialized electrode'),
('HI9810352', 'g. pH Electrodes Bluetooth', 'HALO2 Wireless pH Tester for Sushi with built-in specialized electrode'),
('HI9810362', 'g. pH Electrodes Bluetooth', 'HALO2 Wireless pH Tester for Meat with built-in specialized electrode'),
('HI9810372', 'g. pH Electrodes Bluetooth', 'HALO2 Wireless pH Tester for Skin & Scalp with built-in specialized electrode'),
('HI9810382', 'g. pH Electrodes Bluetooth', 'HALO2 Wireless pH Tester for Bread and Dough with built-in specialized electrode'),
('HI9810392', 'g. pH Electrodes Bluetooth', 'HALO2 Wireless pH Tester for Chocolate with built-in specialized electrode'),
('HI9810402', 'g. pH Electrodes Bluetooth', 'HALO2 Wireless Refillable pH Tester for Lab with built-in general purpose electrode'),
('HI9810412', 'g. pH Electrodes Bluetooth', 'HALO2 Wireless pH Tester for Lab with built-in general purpose electrode'),
('HI9810422', 'g. pH Electrodes Bluetooth', 'HALO2 Wireless pH Tester for Field with built-in general purpose electrode'),
('HI9810432', 'g. pH Electrodes Bluetooth', 'HALO2 Wireless Refillable pH Tester for Cosmetic Creams with built-in specialized electrode'),
('HI9810442', 'g. pH Electrodes Bluetooth', 'HALO2 Wireless pH Tester for Leather & Paper with built-in specialized electrode'),
('HI9810452', 'g. pH Electrodes Bluetooth', 'HALO2 Wireless pH Tester for Meat with built-in Specialized Electrode, Compatible with FC097 Meat Blade'),
('HI9810462', 'g. pH Electrodes Bluetooth', 'HALO2 Wireless Refillable pH Tester for Lab with Built-in Specialized Electrode'),
('HI9810472', 'g. pH Electrodes Bluetooth', 'HALO2 Wireless Refillable pH Tester for Juice with Built-in Specialized Electrode'),
('FC100B', 'g. pH Electrodes FoodCare', 'PVDF Body Refillable Foodcare pH Electrode for Dairy Products'),
('FC1013', 'g. pH Electrodes FoodCare', 'pH/temperature electrode for milk with quick connect DIN connector, PVDF body, refillable'),
('FC10483', 'g. pH Electrodes FoodCare', 'Wine Juice & Must Clogging Prevention System (CPS™) pH electrode with quick connect DIN connector'),
('FC200B', 'g. pH Electrodes FoodCare', 'PVDF Body Foodcare pH Electrode for Dairy Products and Semi-Solid Foods'),
('FC200B/1.5', 'g. pH Electrodes FoodCare', 'PVDF Body Foodcare pH Electrode for Dairy Products and Semi-Solid Foods with BNC connector and 1.5 m cable'),
('FC200B/2.5', 'g. pH Electrodes FoodCare', 'PVDF Body Foodcare pH Electrode for Dairy Products and Semi-Solid Foods with BNC connector and 2.5 m cable'),
('FC200B/3', 'g. pH Electrodes FoodCare', 'PVDF Body Foodcare pH Electrode for Dairy Products and Semi-Solid Foods with BNC connector and 3 m cable'),
('FC200D', 'g. pH Electrodes FoodCare', 'PVDF Body Foodcare pH Electrode for Dairy Products and Semi-Solid Foods'),
('FC200S', 'g. pH Electrodes FoodCare', 'pH electrode; Use for milk, yogurt, dairy products, and semi solid foods, BNC connector, 1 mt cable'),
('FC2023', 'g. pH Electrodes FoodCare', 'Foodcare pH Electrode for Dairy Products and Semi-Solid Foods with Quick Connect DIN Connector'),
('FC202D', 'g. pH Electrodes FoodCare', 'Foodcare pH Electrode for Dairy Products and Semi-Solid Foods with DIN Connector'),
('FC2053', 'g. pH Electrodes FoodCare', 'Foodcare pH electrode with replaceble gel bridge electrolyte'),
('FC210B', 'g. pH Electrodes FoodCare', 'Foodcare pH Electrode for Yogurt and Creams with BNC Connector'),
('FC210Y', 'g. pH Electrodes FoodCare', 'Foodcare pH / Temperature Electrode for Dairy Products, Conical tip with BNC and RCA Connector'),
('FC2133', 'g. pH Electrodes FoodCare', 'pH/temperature electrode for yogurt with quick connect DIN connector, glass body, gel filled'),
('FC2143', 'g. pH Electrodes FoodCare', 'pH Electrode for Beer Analysis'),
('FC214D', 'g. pH Electrodes FoodCare', 'pH Electrode for Beer Analysis'),
('FC2153', 'g. pH Electrodes FoodCare', 'Portable Drinking Water pH meter with high flow rate pH electrode and quick connect DIN connector'),
('FC215D', 'g. pH Electrodes FoodCare', 'Low Ionic strength water pH electrode'),
('FC2163', 'g. pH Electrodes FoodCare', 'Foodcare pH / Temperature Electrode for Dairy Products, Conical tip High Temperature with Quick Connect DIN Connector'),
('FC220B', 'g. pH Electrodes FoodCare', 'Glass Body Foodcare pH Electrode for Creams, Sauces and Fruit Juices with BNC Connector'),
('FC230B', 'g. pH Electrodes FoodCare', 'Foodcare pH Electrode for Meat and Semi-Frozen Products with BNC Connector'),
('FC2323', 'g. pH Electrodes FoodCare', 'Foodcare pH Electrode for Meat Products with Quick Connect DIN Connector'),
('FC232D', 'g. pH Electrodes FoodCare', 'Foodcare pH Electrode for Meat Products with DIN Connector'),
('FC240B', 'g. pH Electrodes FoodCare', 'Foodcare pH Electrode with Small Diameter Stainless Steel Body and BNC Connector'),
('FC2423', 'g. pH Electrodes FoodCare', 'pH/temperature electrode for cheese with quick connect DIN connector, stainless steel body, gel filled'),
('FC2423-1', 'g. pH Electrodes FoodCare', 'pH/temperature electrode for milk&cheese with quick connect DIN connector, 1m titanium body, conical tip, single junction, viscolene electrolyte'),
('FC242D', 'g. pH Electrodes FoodCare', 'HI99165 replacement pH/temperature electrode for cheese with DIN connector, stainless steel body, gel filled'),
('FC250B', 'g. pH Electrodes FoodCare', 'Combination pH electrode with long thin body; Use for dairy products, and semi mature cheese, BNC connector'),
('FC260B', 'g. pH Electrodes FoodCare', 'Foodcare pH Half-Cell Electrode with BNC Connector'),
('FC300B', 'g. pH Electrodes FoodCare', 'Sodium Combination Ion Selective Electrode'),
('FC301B', 'g. pH Electrodes FoodCare', 'Solid-state, half-cell ion selective electrode for fluoride'),
('FC400B', 'g. pH Electrodes FoodCare', 'Foodcare pH Electrode for Meat Products with BNC Connector'),
('FC911B', 'g. pH Electrodes FoodCare', 'PVDF Body Foodcare pH Electrode for Creams, Sauces and Fruit Juices with BNC Connector'),
('BL123-70', 'h. Solutions', 'Swimming pools/SPAs maintenance and calibration kit for pH and ORP electrodes'),
('BL123-70-30', 'h. Solutions', 'Swimming pools/SPAs maintenance and calibration kit for pH and ORP electrodes 30 pcs/pack'),
('BL136-70', 'h. Solutions', 'Pool Line Maintenance and Calibration Kit for Chlorine, pH and ORP Probes used in BL135 and BL136'),
('BL136-70-30', 'h. Solutions', 'Pool Line Maintenance and Calibration Kit for Chlorine, pH and ORP Probes used in BL135 and BL136 (30 pcs/pack)'),
('HI50001-02', 'h. Solutions', 'pH 1.00 @ 25°C Technical Calibration Buffer Sachets, (25 x 20mL)'),
('HI50002-02', 'h. Solutions', 'pH 2.00 @ 25°C Technical Calibration Buffer Sachets, (25 x 20mL)'),
('HI50003-02', 'h. Solutions', 'pH 3.00 @ 25°C Technical Calibration Buffer Sachets, (25 x 20mL)'),
('HI50004-02', 'h. Solutions', 'pH 4.01 @ 25°C Technical Calibration Buffer Sachets, (25 x 20mL)'),
('HI50005-02', 'h. Solutions', 'pH 5.00 @ 25°C Technical Calibration Buffer Sachets, (25 x 20mL)'),
('HI50007-02', 'h. Solutions', 'pH 7.01 @ 25°C Technical Calibration Buffer Sachets, (25 x 20mL)'),
('HI50009-02', 'h. Solutions', 'pH 9.00 @ 25°C Technical Calibration Buffer Sachets, (25 x 20mL)'),
('HI5001', 'h. Solutions', 'pH 1.00 @ 25°C Technical Calibration Buffer, 500 mL'),
('HI50010-02', 'h. Solutions', 'pH 10.01 @ 25°C Technical Calibration Buffer Sachets, (25 x 20mL)'),
('HI50011-02', 'h. Solutions', 'pH 11.00 @ 25°C Technical Calibration Buffer Sachets, (25 x 20mL)'),
('HI50012-01', 'h. Solutions', '12.00 pH Value @25°C, (10) 20 mL sachets'),
('HI50012-02', 'h. Solutions', 'pH 12.00 @ 25°C Technical Calibration Buffer Sachets, (25 x 20mL)'),
('HI50013-02', 'h. Solutions', 'pH 13.00 @ 25°C Technical Calibration Buffer Sachets, (25 x 20mL)'),
('HI50016-02', 'h. Solutions', 'pH 1.68 @ 25°C Technical Calibration Buffer Sachets, (25 x 20mL)'),
('HI5002', 'h. Solutions', 'pH 2.00 @ 25°C Technical Calibration Buffer, 500 mL'),
('HI5002-01', 'h. Solutions', 'pH 2.00 @ 25°C Technical Calibration Buffer, 1 L'),
('HI50021P', 'h. Solutions', 'CAL Check solution for HI9813-6, (25 x 20mL)'),
('HI5003', 'h. Solutions', 'pH 3.00 @ 25°C Technical Calibration Buffer, 500 mL'),
('HI50036P', 'h. Solutions', 'Quick Cal solution sachets for single point pH/EC calibration, (25 x 20mL)'),
('HI5004', 'h. Solutions', 'pH 4.01 @ 25°C Technical Calibration Buffer, 500 mL'),
('HI5004-01', 'h. Solutions', 'pH 4.01 @ 25°C Technical Calibration Buffer, 1 L'),
('HI5004-R', 'h. Solutions', 'pH 4.01 @ 25°C Red Technical Calibration Buffer, 500 mL'),
('HI5004-R08', 'h. Solutions', 'pH 4.01 @ 25°C Red Technical Calibration Buffer, (2) 1 Gal. (3.78 L)'),
('HI5005', 'h. Solutions', 'pH 5.00 @ 25°C Technical Calibration Buffer, 500 mL'),
('HI5005-01', 'h. Solutions', 'pH 5.00 @ 25°C Technical Calibration Buffer, 1 L'),
('HI5006', 'h. Solutions', 'pH 6.00 @ 25°C Technical Calibration Buffer, 500 mL'),
('HI50068-02', 'h. Solutions', 'pH 6.86 @ 25°C Technical Calibration Buffer Sachets, (25 x 20mL)'),
('HI5007', 'h. Solutions', 'pH 7.01 @ 25°C Technical Calibration Buffer, 500 mL'),
('HI5007-01', 'h. Solutions', 'pH 7.01 @ 25°C Technical Calibration Buffer, 1 L'),
('HI5007-G', 'h. Solutions', 'pH 7.01 @ 25°C Green Technical Calibration Buffer, 500 mL bottle'),
('HI5007-G08', 'h. Solutions', 'pH 7.01 @ 25°C Green Technical Calibration Buffer, (2) 1 Gal. (3.78 L)'),
('HI5008', 'h. Solutions', 'pH 8.00 @ 25°C Technical Calibration Buffer, 500 mL'),
('HI5008-01', 'h. Solutions', 'pH 8.00 @ 25°C Technical Calibration Buffer, 1 L')
ON CONFLICT (codigo) DO NOTHING;