-- Seed codigos_catalogo — parte 4 (702 filas)
-- Generado desde Accessories_List_2026-08-02.xlsx, hoja "List code".
INSERT INTO codigos_catalogo (codigo, familia, descripcion) VALUES
('HI7632', 'q. Minicontrollers - Probes', 'Conductivity/TDS probe, with 2 m (6.6’) cable'),
('HI7632-00', 'q. Minicontrollers - Probes', 'EC/TDS probe for high range Mini Controllers, 2 m cable'),
('HI7632-00/6', 'q. Minicontrollers - Probes', 'EC/TDS probe for high range Mini Controllers, 6m cable'),
('HI7634', 'q. Minicontrollers - Probes', 'EC/TDS probe for HI983301, HI983303 and HI983306'),
('HI7634-00', 'q. Minicontrollers - Probes', 'EC/TDS probe for low range Mini Controllers, 2 m cable'),
('HI7634-00/4', 'q. Minicontrollers - Probes', 'EC/TDS probe for low range Mini Controllers, 4 m cable'),
('HI7634-00/5', 'q. Minicontrollers - Probes', 'EC/TDS probe for low range Mini Controllers, 5 m cable'),
('HI7871/115', 'q. Minicontrollers - Probes', 'Mini Level Controller, control relay: high and low, 110, 115V'),
('HI7871/220', 'q. Minicontrollers - Probes', 'Mini Level Controller, control relay: high and low, 220, 240V'),
('HI7873/115', 'q. Minicontrollers - Probes', 'Mini Level Controller, control relay: high, low and overflow, 110, 115V'),
('HI7873/220', 'q. Minicontrollers - Probes', 'Mini Level Controller, control relay: high, low and overflow, 220, 240V'),
('HI7874', 'q. Minicontrollers - Probes', 'Holder for level controller bars, bar holder and level transmitter'),
('BL100-300', 'r. Process - BL Accessories', 'Peristaltic pump tubing kit'),
('BL100-302', 'r. Process - BL Accessories', 'Pump cover with screw'),
('BL100-400', 'r. Process - BL Accessories', 'Probe Adapter kit (contains adapter, fixing nut, O-ring'),
('BL100-421', 'r. Process - BL Accessories', 'Flow cell panel using BL120-410 Flow cell'),
('BL120-150', 'r. Process - BL Accessories', 'Fittings Kit for 50 mm pipe diameter (saddle for injectors-2 pcs, saddle for probe-1pc)'),
('BL120-163', 'r. Process - BL Accessories', 'Fittings Kit for 63 mm pipe diameter (saddle for injectors-2 pcs, saddle for probe-1 pc)'),
('BL120-175', 'r. Process - BL Accessories', 'Fittings Kit for 75 mm pipe diameter (saddle for injectors-2 pcs, saddle for probe-1 pc)'),
('BL120-200', 'r. Process - BL Accessories', 'Aspiration filter'),
('BL120-201', 'r. Process - BL Accessories', 'Injector, 1/2" thread'),
('BL120-202', 'r. Process - BL Accessories', 'Aspiration and dispensing tubing (10 m)'),
('BL120-203', 'r. Process - BL Accessories', 'Aspiration filter weight for BL12X pH/ORP/temperature pool controllers'),
('BL120-204', 'r. Process - BL Accessories', 'Aspiration PVC tubing (100 m)'),
('BL120-205', 'r. Process - BL Accessories', 'Injection PE tubing (100 m)'),
('BL120-206', 'r. Process - BL Accessories', 'Set of O-Rings for BL120-201 Injector (100 pcs)'),
('BL120-250', 'r. Process - BL Accessories', 'Injector saddle for 50 mm pipe diameter, 1/2" thread'),
('BL120-263', 'r. Process - BL Accessories', 'Injector saddle for 63 mm pipe diameter, 1/2" thread'),
('BL120-275', 'r. Process - BL Accessories', 'Injector saddle for 75 mm pipe diameter, 1/2" thread'),
('BL120-300', 'r. Process - BL Accessories', 'Pool controller peristaltic pump tubing Kit (2 pcs)'),
('BL120-301', 'r. Process - BL Accessories', 'Peristaltic pump rotor'),
('BL120-302', 'r. Process - BL Accessories', 'Pool controller pump cover with screw'),
('BL120-400', 'r. Process - BL Accessories', 'Flow cell probe adapter Kit (O-ring, nut, adapter)'),
('BL120-401', 'r. Process - BL Accessories', 'Flow cell Valve'),
('BL120-402', 'r. Process - BL Accessories', 'Flow cell tubing (10 m)'),
('BL120-410', 'r. Process - BL Accessories', 'Flow cell'),
('BL120-411', 'r. Process - BL Accessories', 'Flow cell panel spare part'),
('BL120-450', 'r. Process - BL Accessories', 'Flow cell Kit for 50 mm pipe diameter'),
('BL120-463', 'r. Process - BL Accessories', 'Flow cell Kit for 63 mm pipe diameter'),
('BL120-475', 'r. Process - BL Accessories', 'Flow cell Kit for 75 mm pipe diameter'),
('BL120-500', 'r. Process - BL Accessories', 'Probe fitting Kit (O-ring, nut, adapter)'),
('BL120-501', 'r. Process - BL Accessories', 'Protective saddle cap, 1-1/4" thread'),
('BL120-550', 'r. Process - BL Accessories', 'Probe saddle for 50 mm pipe diameter, 1-1/4" thread'),
('BL120-563', 'r. Process - BL Accessories', 'Probe saddle for 63 mm pipe diameter, 1-1/4" thread'),
('BL120-575', 'r. Process - BL Accessories', 'Probe saddle for 75 mm pipe diameter, 1-1/4" thread'),
('BL120-601', 'r. Process - BL Accessories', 'Plastic nipple 2x1/2” with O-Rings'),
('BL120-602', 'r. Process - BL Accessories', 'Metal nipple 12 x 1/2”'),
('BL120-603', 'r. Process - BL Accessories', 'Elbow for calibration glass of BL121'),
('BL120-604', 'r. Process - BL Accessories', 'O-ring for glass calibration of BL121'),
('BL120-605', 'r. Process - BL Accessories', 'Metal Nipple 12X1/4’ for BL120-410 Flowcell'),
('BL120-901', 'r. Process - BL Accessories', 'BL121 Simulator'),
('BL120-902', 'r. Process - BL Accessories', 'USB protective CAP'),
('BL120-903', 'r. Process - BL Accessories', 'Cable gland protective Kit (6 pcs)'),
('BL130-300', 'r. Process - BL Accessories', 'Pool Controller Peristaltic Pump Tubing Kit for BL13x series Pool Controllers (2 pcs.)'),
('BL130-301', 'r. Process - BL Accessories', 'Peristaltic Pump Rotor for BL13x series Pool Controllers'),
('BL130-408', 'r. Process - BL Accessories', 'Paddle Flow Switch for BL12X and BL13X Main Circuit'),
('BL130-409', 'r. Process - BL Accessories', 'Flow Cell Sensor for BL130-410'),
('BL130-410', 'r. Process - BL Accessories', 'Flow Cell for HI1040-1801 Probe used in BL135 and BL136'),
('BL130-411', 'r. Process - BL Accessories', 'Flow Cell Panel Accessory for BL132'),
('BL130-415', 'r. Process - BL Accessories', 'Flow Cell Panel Accessory for BL135 and BL136'),
('BL130-710', 'r. Process - BL Accessories', 'Chlorine Generator 10 g/h Output'),
('BL130-711', 'r. Process - BL Accessories', 'Chlorine Generator Core 10 g/h Output'),
('BL130-712', 'r. Process - BL Accessories', 'Chlorine Generator Cable Assembly for 10 g/h Generator'),
('BL130-713', 'r. Process - BL Accessories', 'Chlorine Generator Body Housing'),
('BL130-714', 'r. Process - BL Accessories', 'Chlorine Generator Lock Ring'),
('BL130-715', 'r. Process - BL Accessories', 'Chlorine Generator Sealing Gasket'),
('BL130-720', 'r. Process - BL Accessories', 'Chlorine Generator 20 g/h Output'),
('BL130-721', 'r. Process - BL Accessories', 'Chlorine Generator Core 20 g/h Output'),
('BL130-722', 'r. Process - BL Accessories', 'Chlorine Generator Cable Assembly for 20 g/h Generator'),
('BL130-730', 'r. Process - BL Accessories', 'Chlorine Generator 30 g/h Output'),
('BL130-731', 'r. Process - BL Accessories', 'Chlorine Generator Core 30 g/h Output'),
('BL130-732', 'r. Process - BL Accessories', 'Chlorine Generator Cable Assembly for 30 g/h Generator'),
('BL130-900', 'r. Process - BL Accessories', 'Ambient Temperature Probe for BL13x series Pool Controllers with 1 meter Cable'),
('BL130-901', 'r. Process - BL Accessories', 'BL131, BL132 Simulator'),
('BL130-905', 'r. Process - BL Accessories', 'Simulator for BL135 and BL136'),
('BL100-00', 'r. Process - BL Controllers', 'Pool Line pH controller and dosing pump with HI10053 pH probe'),
('BL100-10', 'r. Process - BL Controllers', 'Pool Line pH controller and dosing pump with HI10053 pH probe, injection valve fitting and tubing'),
('BL100-20', 'r. Process - BL Controllers', 'Pool Line pH controller and dosing pump with HI10053 pH probe, panel mounted flow cell, fittings and tubing'),
('BL101-00', 'r. Process - BL Controllers', 'Pool Line ORP controller and dosing pump with HI20083 ORP probe'),
('BL101-10', 'r. Process - BL Controllers', 'Pool Line ORP controller and dosing pump with HI20083 ORP probe, injection valve fitting and tubing'),
('BL101-20', 'r. Process - BL Controllers', 'Pool Line ORP controller and dosing pump with HI20083 ORP probe, panel mounted flow cell, fittings and tubing'),
('BL120-10', 'r. Process - BL Controllers', 'pH/ORP/Temperature pool controller, no analog outputs, 115/230V'),
('BL120-20', 'r. Process - BL Controllers', 'pH/ORP/Temperature pool controller with flow cell mounted on panel, no analog outputs, 115/230V'),
('BL121-10', 'r. Process - BL Controllers', 'pH/ORP/Temperature pool controller with anolog outputs, 115/230V'),
('BL121-20', 'r. Process - BL Controllers', 'pH/ORP/Temperature pool controller with flow cell mounted on panel with analog outputs, 115/230V'),
('BL122-10', 'r. Process - BL Controllers', 'pH/ORP/Temperature pool controller with ethernet for remote cloud monitoring, no analog outputs, 115/230V'),
('BL122-20', 'r. Process - BL Controllers', 'Panel mounted flow cell pH/ORP/Temperature pool controller with ethernet for remote cloud monitoring, no analog outputs, 1115/230V'),
('BL123-10', 'r. Process - BL Controllers', 'pH/ORP/Temperature pool controller with ethernet for remote cloud monitoring and analog outputs, 115/230V'),
('BL123-20', 'r. Process - BL Controllers', 'Panel mounted flow cell pH/ORP/Temperature pool controller with ethernet for remote cloud monitoring and analog outputs, 1115/230V'),
('BL131-10', 'r. Process - BL Controllers', 'pH/ORP/Temperature pool controller with external dosing and analog outputs, 115/230V'),
('BL131-20', 'r. Process - BL Controllers', 'pH/ORP/Temperature pool controller with external dosing, flow cell mounted on panel and analog outputs, 115/230V'),
('BL132-10', 'r. Process - BL Controllers', 'pH/ORP/Temperature pool controller with external dosing and remote cloud connectivity, 115/230V'),
('BL132-20', 'r. Process - BL Controllers', 'pH/ORP/Temperature pool controller with external dosing, flow cell mounted on panel and remote cloud connectivity, 115/230V'),
('BL135-20110', 'r. Process - BL Controllers', 'Salt Pool Controller with Chlorine Generator 10 g/h Output, External Dosing and Analog Outputs, including HI701 Free Chlorine Checker, 115/230V'),
('BL135-20120', 'r. Process - BL Controllers', 'Salt Pool Controller with Chlorine Generator 20 g/h Output, External Dosing and Analog Outputs, including HI701 Free Chlorine Checker, 115/230V'),
('BL135-20130', 'r. Process - BL Controllers', 'Salt Pool Controller with Chlorine Generator 30 g/h Output, External Dosing and Analog Outputs, including HI701 Free Chlorine Checker, 115/230V'),
('BL136-20110', 'r. Process - BL Controllers', 'Salt Pool Controller with Chlorine Generator 10 g/h Output, External Dosing and Remote Cloud Connectivity, including HI701 Free Chlorine Checker, 115/230V'),
('BL136-20120', 'r. Process - BL Controllers', 'Salt Pool Controller with Chlorine Generator 20 g/h Output, External Dosing and Remote Cloud Connectivity, including HI701 Free Chlorine Checker, 115/230V'),
('BL136-20130', 'r. Process - BL Controllers', 'Salt Pool Controller with Chlorine Generator 30 g/h Output, External Dosing and Remote Cloud Connectivity, including HI701 Free Chlorine Checker, 115/230V'),
('HI10053', 'r. Process - BL Probes', 'Pool Line pH/Temperature Probe with quick connect DIN connector for BL100'),
('HI10053/10', 'r. Process - BL Probes', 'Pool Line pH/Temperature Probe with Quick connect DIN Connector for BL100, 10 m Cable'),
('HI10063', 'r. Process - BL Probes', 'GroLine amplified pH/Temperature probe with quick connect DIN connector for HI981412'),
('HI1036-1802', 'r. Process - BL Probes', 'Industrial pH/ORP/Temperature/Matching Pin combined probe, 2 m cable'),
('HI1036-1805', 'r. Process - BL Probes', 'Industrial pH/ORP/Temperature/Matching Pin combined probe, 5 m cable'),
('HI1036-1810', 'r. Process - BL Probes', 'Industrial pH/ORP/Temperature/Matching Pin combined probe, 10 m cable'),
('HI1036-1815', 'r. Process - BL Probes', 'Industrial pH/ORP/Temperature/Matching Pin combined probe, 15 m cable'),
('HI1036-1820', 'r. Process - BL Probes', 'Industrial pH/ORP/Temperature/Matching Pin combined probe, 20 m cable'),
('HI1038-2802', 'r. Process - BL Probes', 'Industrial pH/ORP Gold Ring/Salinity/Temperature Probe with Matching pin for BL135 and BL136, 2 m cable'),
('HI1038-2805', 'r. Process - BL Probes', 'Industrial pH/ORP Gold Ring/Salinity/Temperature Probe with Matching pin for BL135 and BL136, 5 m cable'),
('HI1038-2810', 'r. Process - BL Probes', 'Industrial pH/ORP Gold Ring/Salinity/Temperature Probe with Matching pin for BL135 and BL136, 10 m cable'),
('HI1038-2815', 'r. Process - BL Probes', 'Industrial pH/ORP Gold Ring/Salinity/Temperature Probe with Matching pin for BL135 and BL136, 15 m cable'),
('HI1038-2820', 'r. Process - BL Probes', 'Industrial pH/ORP Gold Ring/Salinity/Temperature Probe with Matching pin for BL135 and BL136, 20 m cable'),
('HI1040-1801', 'r. Process - BL Probes', 'Free Chlorine Probe for BL135 and BL136, 1 m cable'),
('HI1040A', 'r. Process - BL Probes', 'Membrane for HI1040-1801 Probe, 1 pc.'),
('HI20083', 'r. Process - BL Probes', 'Pool Line ORP/Temperature probe with quick connect DIN connector for BL101'),
('HI20083/10', 'r. Process - BL Probes', 'Pool Line ORP/Temperature Probe with Quick Connect DIN Connector, 10 meters Cable for BL101'),
('HI30033', 'r. Process - BL Probes', 'GroLine EC/Temperature probe with quick connect DIN connector for HI981413'),
('BL7916-1', 'r. Process - Controllers', 'pH Controller and Pump, range: 0.00 to 14.00 pH, 110/115V ±15%; 50/60Hz (40W) power supply'),
('BL7916-2', 'r. Process - Controllers', 'pH Controller and Pump, range: 0.00 to 14.00 pH, 220/240V ±15%; 50/60Hz (40W) power supply'),
('BL7917-1', 'r. Process - Controllers', 'ORP Controller and Pump, range: +/-1999 mV, 110/115V ±15%; 50/60Hz (40W) power supply'),
('BL7917-2', 'r. Process - Controllers', 'ORP Controller and Pump, range: +/-1999 mV, 220/240V ±15%; 50/60Hz (40W) power supply'),
('HI8410', 'r. Process - Controllers Analog', 'Panel Mounted Dissolved Oxygen Controller with Extended Range and Analog Output, range: 0.0 to 50.0 mg/L (ppm) O2, 0 to 600 % O2, Temperature -5.0 to 50.0 °C'),
('HI8510', 'r. Process - Controllers Analog', 'Panel Mounted pH Analog Indicator with Self-diagnostic test, range: 0.00 to 14.00 pH'),
('HI8512', 'r. Process - Controllers Analog', 'Panel Mounted ORP Analog Indicator with Self-diagnostic test, range: +/-1999 mV'),
('HI8614LN', 'r. Process - Controllers Analog', 'pH Transmitter with 4-20 mA Galvanically Isolated output; with LCD display, range: 0.00 to 14.00 pH'),
('HI8614N', 'r. Process - Controllers Analog', 'pH Transmitter with 4-20 mA Galvanically Isolated output, range: 0.00 to 14.00 pH'),
('HI8615LN', 'r. Process - Controllers Analog', 'ORP Transmitter with 4-20 mA Galvanically Isolated output; with LCD display, HI8615(L): ±1000 mV / 4-20 mA, HI8615(L)-01: ±1999 mV / 4-20 mA'),
('HI8615N', 'r. Process - Controllers Analog', 'ORP Transmitter with 4-20 mA Galvanically Isolated output, HI8615(L): ±1000 mV / 4-20 mA, HI8615(L)-01: ±1999 mV / 4-20 mA'),
('HI8710', 'r. Process - Controllers Analog', 'Panel Mounted pH Analog Controller with Self-diagnostic test, range: 0.00 to 14.00 pH'),
('HI8711', 'r. Process - Controllers Analog', 'Panel Mounted pH Analog Controller with Dual Output and Self-diagnostic test, range: 0.00 to 14.00 pH'),
('HI8720', 'r. Process - Controllers Analog', 'Panel Mounted ORP Analog Controller with Self-diagnostic test, range: +/-1999 mV'),
('HI8931AN', 'r. Process - Controllers Analog', 'Panel mounted conductivity controller 0.0-199.9 mS/cm'),
('HI8931BN', 'r. Process - Controllers Analog', 'Panel mounted conductivity controller 0.00-19.99 mS/cm'),
('HI8931CN', 'r. Process - Controllers Analog', 'Panel mounted conductivity controller 0-1999 µS/cm'),
('HI8931DN', 'r. Process - Controllers Analog', 'Panel mounted conductivity controller 0.0-199.9 µS/cm'),
('HI8936ALN', 'r. Process - Controllers Analog', 'Conductivity Transmitter Using 4-Ring Technology, range: 0.0 to 199.9 mS/cm; with LCD display'),
('HI8936AN', 'r. Process - Controllers Analog', 'Conductivity Transmitter Using 4-Ring Technology, range: 0.0 to 199.9 mS/cm'),
('HI8936BLN', 'r. Process - Controllers Analog', 'Conductivity Transmitter Using 4-Ring Technology, range: 0.00 to 19.99 mS/cm; with LCD display'),
('HI8936BN', 'r. Process - Controllers Analog', 'Conductivity Transmitter Using 4-Ring Technology, range: 0.00 to 19.99 mS/cm'),
('HI8936CLN', 'r. Process - Controllers Analog', 'Conductivity Transmitter Using 4-Ring Technology, range: 0 to 1999 µS/cm; with LCD display'),
('HI8936CN', 'r. Process - Controllers Analog', 'Conductivity Transmitter Using 4-Ring Technology, range: 0 to 1999 µS/cm'),
('HI8936DLN', 'r. Process - Controllers Analog', 'Conductivity Transmitter Using 4-Ring Technology, range: 0.0 to 199.9 µS/cm; with LCD display'),
('HI8936DN', 'r. Process - Controllers Analog', 'Conductivity Transmitter Using 4-Ring Technology, range: 0.0 to 199.9 µS/cm'),
('HI943500A', 'r. Process - Controllers Analog', 'Conductivity Analog Controller with Direct Input from Potentiometric Probe, range: 0.0 to 199.9 mS/cm'),
('HI943500B', 'r. Process - Controllers Analog', 'Conductivity Analog Controller with Direct Input from Potentiometric Probe, range: 0.00 to 19.99 mS/cm'),
('HI943500C', 'r. Process - Controllers Analog', 'Conductivity Analog Controller with Direct Input from Potentiometric Probe, range: 0 to 1999 µS/cm'),
('HI943500D', 'r. Process - Controllers Analog', 'Conductivity Analog Controller with Direct Input from Potentiometric Probe, range: 0.0 to 199.9 µS/cm'),
('HI98143-01', 'r. Process - Controllers Analog', 'pH and EC transmitter with isolated output; range: 0 to 14 pH; 0 to 10 mS/cm, 0-1 V output'),
('HI98143-04', 'r. Process - Controllers Analog', 'pH and EC transmitter with isolated range: 0 to 14 pH; 0 to 10 mS/cm, output; 0-4 V output'),
('HI98143-20', 'r. Process - Controllers Analog', 'pH and EC transmitter with isolated range: 0 to 14 pH; 0 to 10 mS/cm, output; 4-20 mA output (passive)'),
('HI98143-22', 'r. Process - Controllers Analog', 'pH and EC transmitter with isolated range: 0 to 14 pH; 0 to 10 mS/cm, output; 4-20 mA output (active)'),
('HI510-0320', 'r. Process - Controllers Digital', 'HI510 Universal Controller with Digital Probe Inputs, 3 relays, 2 analog outputs'),
('HI510-0540', 'r. Process - Controllers Digital', 'HI510 Universal Controller with Digital Probe Inputs, 5 relays, 4 analog outputs'),
('HI520-0320', 'r. Process - Controllers Digital', 'Dual-Channel Universal Process Controller with Digital Probe Inputs, 3 Relays, 2 Analog Outputs, RS-485 / Modbus serial communication protocol, 100-240 Vac'),
('HI520-0540', 'r. Process - Controllers Digital', 'Dual-Channel Universal Process Controller with Digital Probe Inputs, 5 Relays, 4 Analog Outputs, RS-485 / Modbus serial communication protocol, 100-240 Vac'),
('PCA310-1', 'r. Process - PCA', 'Free & Total Chlorine Analyzer, range: Free & Total Chlorine 0.00 to 5.00 mg/L, Sampling Rate Free & Total Chlorine adjustable from 3 to 90 minutes, 115V'),
('PCA310-2', 'r. Process - PCA', 'Free & Total Chlorine Analyzer, range: Free & Total Chlorine 0.00 to 5.00 mg/L, Sampling Rate Free & Total Chlorine adjustable from 3 to 90 minutes, 230V'),
('PCA320-1', 'r. Process - PCA', 'Free & Total Chlorine/pH/Temperature Analyzer, range: Free & Total Chlorine 0.00 to 5.00 mg/L, 0.00 to 14.00 pH, Temperature 5.0 to 75.0°C Sampling Rate Free & Total Chlorine adjustable from 3 to 90 minutes, 115V'),
('PCA320-2', 'r. Process - PCA', 'Free & Total Chlorine/pH/Temperature Analyzer, range: Free & Total Chlorine 0.00 to 5.00 mg/L, 0.00 to 14.00 pH, Temperature 5.0 to 75.0°C, Sampling Rate Free & Total Chlorine adjustable from 3 to 90 minutes, 230V'),
('PCA330-1', 'r. Process - PCA', 'Free & Total Chlorine/pH/ORP/Temperature Analyzer, range: Free & Total Chlorine 0.00 to 5.00 mg/L, 0.00 to 14.00 pH, Temperature 5.0 to 75.0°C, mV 0 to 2000 mV, Sampling Rate Free & Total Chlorine adjustable from 3 to 90 minutes, 115V'),
('PCA330-2', 'r. Process - PCA', 'Free & Total Chlorine/pH/ORP/Temperature Analyzer, range: Free & Total Chlorine 0.00 to 5.00 mg/L, 0.00 to 14.00 pH, Temperature 5.0 to 75.0°C, mV 0 to 2000 mV, Sampling Rate Free & Total Chlorine adjustable from 3 to 90 minutes, 230V'),
('PCA340-1', 'r. Process - PCA', 'Free & Total Chlorine/pH/Temperature Analyzer, range: Free & Total Chlorine 0.00 to 5.00 mg/L, 0.00 to 14.00 pH, Temperature 5.0 to 75.0°C. Dual analog outputs. Sampling Rate Free & Total Chlorine adjustable from 3 to 90 minutes, 115V'),
('PCA340-2', 'r. Process - PCA', 'Free & Total Chlorine/pH/Temperature Analyzer, range: Free & Total Chlorine 0.00 to 5.00 mg/L, 0.00 to 14.00 pH, Temperature 5.0 to 75.0°C. Dual analog outputs. Sampling Rate Free & Total Chlorine adjustable from 3 to 90 minutes, 230V'),
('HI70473', 'r. Process - PCA Accessories', 'PCA tubing kit, pressure regulator to drain (2 pcs). Each kit includes: transparent Tygon tubes 86L x 3.2ID mm (3.4 x 0.1”) (Length x Internal Diameter) (1, 2) and 105 x 9.5 mm (4.1 x 0.4”) (3)'),
('HI70474', 'r. Process - PCA Accessories', 'PCA peristaltic pump tubing kit (6 pcs). Each kit includes: non-transparent C-flex tubes 55L x 0.8ID mm (2.1 x 0.03’’) (5)'),
('HI70475', 'r. Process - PCA Accessories', 'PCA peristaltic pump tubing kit (2 pcs). Each kit includes: non-transparent C-flex tubes 55L x 0.8ID mm (2.1 x 0.03’’) (5)'),
('HI70476', 'r. Process - PCA Accessories', 'PCA reagent bottle tubing kit (6 pcs). Each kit includes: non-transparent C-flex tubes 155L x 0.8ID mm (6.1 x 0.03’’) (11)'),
('HI70477', 'r. Process - PCA Accessories', 'PCA tubing set for measuring cell (2 pcs). Each set includes: non-transparent C-flex tube 50L x 0.8ID mm (2.0 x 0.03’’) (8) andY strainer (7)'),
('HI70478', 'r. Process - PCA Accessories', 'PCA tubing kit, bottle to pump (6 pcs). Each kit includes: non-transparent C-flex tube 150L x 0.8ID mm (5.9 x 0.03’’) (4)'),
('HI70479', 'r. Process - PCA Accessories', 'PCA tubing kit, pump to Y strainer (6 pcs). Each kit includes: non-transparent C-flex tube 150L x 0.8ID mm (5.9 x 0.03’’) (6)'),
('HI70482', 'r. Process - PCA Accessories', 'PCA filters. The kit includes 0.5 µm and 50 µm filters (13)'),
('HI70483', 'r. Process - PCA Accessories', 'PCA complete tubing kit. The kit includes: non-transparent C-flex tubes (4, 6) 150L x 0.8ID (5.9 x 0.03’’) (4 pcs), non-transparent C-flex tubes (5) 55L x 0.8ID (2.1 x 0.03’’) (2 pcs), non-transparent C-flex tubes (8) 50L x 0.8ID (2.0 x 0.03’’) and Y strainer (7)'),
('HI70484', 'r. Process - PCA Accessories', 'PCA complete tubing kit (3 pcs). Each kit includes: non-transparent C-flex tubes (4, 6) 150L x 0.8ID (5.9 x 0.03’’) (4 pcs), non-transparent C-flex tubes (5) 55L x 0.8ID (2.1 x 0.03’’) (2 pcs), non-transparent C-flex tubes (8) 50L x 0.8ID (2.0 x 0.03’’), Y strainer (7)'),
('HI70485', 'r. Process - PCA Accessories', 'PCA Spare Parts, magnetic stirrer motor'),
('HI70486', 'r. Process - PCA Accessories', 'Magnetic Stirring Bar for PCA3XX Series, 5.8 mm x 3 mm (2 pcs)'),
('HI704871', 'r. Process - PCA Accessories', 'PCA Spare Parts, measuring cell'),
('HI70488', 'r. Process - PCA Accessories', 'PCA Spare Parts, electrovalve, 60 Hz'),
('HI70489', 'r. Process - PCA Accessories', 'PCA Spare Parts, electrovalve, 50 Hz'),
('HI70491', 'r. Process - PCA Accessories', 'PCA Spare Parts, total chlorine reagent kit'),
('HI70492', 'r. Process - PCA Accessories', 'Electrode holder'),
('HI70493', 'r. Process - PCA Accessories', 'Closing cap for electrode holder'),
('HI70495', 'r. Process - PCA Accessories', 'PCA Spare Parts, incoming pressure regulator'),
('HI70496', 'r. Process - PCA Accessories', 'PCA Spare Parts, 0.45 µm filter'),
('HI70497', 'r. Process - PCA Accessories', 'PCA Spare Parts, 50 µm filter'),
('HI70430', 'r. Process - PCA Reagents', 'DPD reagent for PCA series'),
('HI70431', 'r. Process - PCA Reagents', 'Total Chlorine reagent for PCA series'),
('HI70450', 'r. Process - PCA Reagents', 'PCA Spare Parts, indicator solution'),
('HI70451', 'r. Process - PCA Reagents', 'PCA Spare Parts, buffer solution'),
('HI70452', 'r. Process - PCA Reagents', 'PCA Spare Parts, DPD reagents'),
('HI70460', 'r. Process - PCA Reagents', 'PCA Spare Parts, Indicator solution for PCA 310, PCA 320 and PCA 330'),
('HI70461', 'r. Process - PCA Reagents', 'PCA Spare Parts, buffer solution for PCA 310, PCA 320 and PCA 330'),
('HI70480', 'r. Process - PCA Reagents', 'PCA free chlorine reagent kit (for fresh water). The kit includes buffer solution, indicator and DPD powder.'),
('HI70481', 'r. Process - PCA Reagents', 'PCA total chlorine reagent kit (for fresh water). The kit includes buffer solution, indicator and DPD powder reagent.'),
('HI70490', 'r. Process - PCA Reagents', 'PCA Spare Parts, free chlorine reagent kit'),
('HI1006-1005', 'r. Process - Probes', 'Industrial Flat Tip pH Electrode, PTFE junction, low Temperature glass bulb, BNC connector, 5 m cable'),
('HI1006-1007', 'r. Process - Probes', 'Industrial Flat Tip pH Electrode, PTFE junction, low Temperature glass bulb, BNC connector, 7 m cable'),
('HI1006-1010', 'r. Process - Probes', 'Industrial Flat Tip pH Electrode, PTFE junction, low Temperature glass bulb, BNC connector, 10 m cable'),
('HI1006-1205', 'r. Process - Probes', 'Industrial Flat Tip pH Electrode, PTFE junction, low Temperature glass bulb, BNC connector, Pt100, 5 m cable'),
('HI1006-3005', 'r. Process - Probes', 'Industrial Flat Tip pH Electrode, PTFE junction, HIgh Temperature glass bulb, BNC connector, 5 m cable'),
('HI1006-3007', 'r. Process - Probes', 'Industrial Flat Tip pH Electrode, PTFE junction, HIgh Temperature glass bulb, BNC connector, 7 m cable'),
('HI1006-3010', 'r. Process - Probes', 'Industrial Flat Tip pH Electrode, PTFE junction, HIgh Temperature glass bulb, BNC connector, 10 m cable'),
('HI1006-3205', 'r. Process - Probes', 'Industrial Flat Tip pH Electrode, PTFE junction, HIgh Temperature glass bulb, BNC connector, Pt100, 5 m cable'),
('HI1006-3505', 'r. Process - Probes', 'Industrial Flat Tip pH Electrode, PTFE junction, High Temperature glass bulb, wire, Pt1000, 5 m cable'),
('HI1006-3715', 'r. Process - Probes', 'Amplified Industrial Flat Tip pH Electrode, PTFE junction, HIgh Temperature glass bulb, wire, BNC connector, Pt100, 15 m cable'),
('HI1006-4005', 'r. Process - Probes', 'Industrial Flat Tip pH Electrode, PTFE junction, with glass bulb for acid samples with Fluoride, BNC connector, 5 m cable'),
('HI1006-4205', 'r. Process - Probes', 'Industrial Flat Tip pH Electrode, PTFE junction, with glass bulb for acid samples with Fluoride, BNC connector, Pt100, 5 m cable'),
('HI101', 'r. Process - Probes', 'Submersible pH electrode with PVC body & BNC'),
('HI101/3', 'r. Process - Probes', 'Adapter 3 meters (9.9´) cable for HI101,HI102,HI201 immersion in-line electrodes'),
('HI101/5', 'r. Process - Probes', 'Adapter 5 meters cable for HI101,HI102,HI201 immersion in-line electrodes'),
('HI102', 'r. Process - Probes', 'In-line pH electrode with PVC body and BNC connector'),
('HI1090B/5', 'r. Process - Probes', 'Combination glass body pH electrode (High Temperature), 5 m cable'),
('HI1090B/6', 'r. Process - Probes', 'Combination glass body pH electrode (High Temperature), 6 m cable'),
('HI1090T', 'r. Process - Probes', 'Glass body combination pH electrode, double junction, T-type connector'),
('HI1143B', 'r. Process - Probes', 'Refillable, combination pH electrode for fluoride applications, BNC connector'),
('HI1190T', 'r. Process - Probes', 'T-Type electrode, glass body, double junction, polymer electrolyte, -15 to 80°C (5 to 176ºF), 3 bar'),
('HI1191T', 'r. Process - Probes', 'T-Type electrode, glass body, double junction, polymer electrolyte, -15 to 80°C (5 to 176ºF), 8 bar'),
('HI1210T', 'r. Process - Probes', 'T-type, PEI body pH Electrode, Double cloth junction, gel electrolyte, -5 to 80°C (23 to 176ºF), 3 bar'),
('HI1211T', 'r. Process - Probes', 'T-type, PEI body pH Electrode, Double PTFE junction, polymer electrolyte, -5 to 80°C (23 to 176ºF), 3 bar'),
('HI2004-1005', 'r. Process - Probes', 'Industrial Flat Tip ORP electrode, PTFE junction, Pt sensor, BNC connector, 5 m cable'),
('HI2004-1007', 'r. Process - Probes', 'Industrial Flat Tip ORP electrode, PTFE junction, Pt sensor, BNC connector, 7 m cable'),
('HI2004-1010', 'r. Process - Probes', 'Industrial Flat Tip ORP electrode, PTFE junction, Pt sensor, BNC connector, 10 m cable'),
('HI2004-1015', 'r. Process - Probes', 'Industrial Flat Tip ORP electrode, PTFE junction, Pt sensor, BNC connector, 15 m cable'),
('HI2004-2005', 'r. Process - Probes', 'Industrial Flat Tip ORP electrode, PTFE junction, Gold sensor, BNC connector, 5 m cable'),
('HI2004-2007', 'r. Process - Probes', 'Industrial Flat Tip ORP electrode, PTFE junction, Gold sensor, BNC connector, 7 m cable'),
('HI201', 'r. Process - Probes', 'Submersible ORP electrode with PVC body & BNC'),
('HI2910B', 'r. Process - Probes', 'PEI body pH electrode with built-in amplifier, double junction, gel-filled, external thread & BNC, 3 m cable'),
('HI2910B/10', 'r. Process - Probes', 'PEI body pH electrode with built-in amplifier, double junction, gel-filled, external thread & BNC,10 m cable'),
('HI2910B/15', 'r. Process - Probes', 'PEI body pH electrode with built-in amplifier, double junction, gel-filled, external thread & BNC, 15 m cable'),
('HI2910B/5', 'r. Process - Probes', 'AmpHel® pH Electrode with Internal Battery, PEI body, gel electrolyte'),
('HI2911B/5', 'r. Process - Probes', 'AmpHel® pH Electrode with Internal Battery, PEI body, polymer electrolyte'),
('HI2930B/5', 'r. Process - Probes', 'AmpHel® ORP Electrode with internal battery, PEI body, platinum glass type'),
('HI2931B/5', 'r. Process - Probes', 'AmpHel® ORP Electrode with internal battery, PEI body, platinum glass type'),
('HI3001', 'r. Process - Probes', 'Flow-thru conductivity probe with automatic Temperature compensation'),
('HI3001D', 'r. Process - Probes', 'Flow-thru conductivity probe with automatic Temperature compensation with DIN connector'),
('HI3001D/10', 'r. Process - Probes', 'Flow-through 4-ring conductivity probe for 6 BAR with platinum sensor, NTC temp sensor and DIN connector, 10 m cable'),
('HI3001D/5', 'r. Process - Probes', 'Flow-through 4-ring conductivity probe for 6 BAR with platinum sensor, NTC temp sensor and DIN connector, 5 m cable'),
('HI3002', 'r. Process - Probes', 'Submersion probe with automatic Temperature compensation'),
('HI3003/D', 'r. Process - Probes', 'Flow-thru conductivity probe with automatic Temperature compensation, PEI/PVDF body, 6 bar DIN, 3 m cable'),
('HI3011', 'r. Process - Probes', 'Flow-thru conductivity probe'),
('HI3090T', 'r. Process - Probes', 'Glass body platinum, ORP electrode, double junction, T-type connector'),
('HI3190T', 'r. Process - Probes', 'Glass body ORP electrode with platinum sensor, double PTFE junction, polymer electrolyte, -15 to 100°C (5 to 212ºF), 6 bar'),
('HI3210B/5', 'r. Process - Probes', 'Combination PEI-body ORP Electrode with Platinum Sensor, 5 m cable'),
('HI3211T', 'r. Process - Probes', 'Glass body ORP electrode with platinum sensor, double cloth junction, gel electrolyte, -5 to 80°C (23 to 176ºF), 3 bar'),
('HI6050', 'r. Process - Probes', 'Submersible Electrode Holder, 605 mm (23.8”), 475 mm (18.7”) submersion length'),
('HI60501', 'r. Process - Probes', 'Immersion Electrode Holders for Tanks, Vessels, Baths and Open Channels, PVC body'),
('HI60501-0', 'r. Process - Probes', 'O-ring set for HI60501'),
('HI605011', 'r. Process - Probes', 'PVC mounting flange for HI60501 and HI60503'),
('HI60501-1', 'r. Process - Probes', 'Spare external cap for electrode holder'),
('HI60501-2', 'r. Process - Probes', 'PVC Protective End Cap, inside Height 68 mm (2.6")'),
('HI60503', 'r. Process - Probes', 'Immersion Electrode Holders for Tanks, Vessels, Baths and Open Channels, PVDF body'),
('HI60503-2', 'r. Process - Probes', 'PVDF Protective End Cap, inside Height 68 mm (2.6")'),
('HI6051', 'r. Process - Probes', 'Submersible Electrode Holder, 1105 mm (43.5”), 975 mm (38.4”) submersion length'),
('HI605101', 'r. Process - Probes', 'Industrial Probes Rail Mount Holder'),
('HI6052', 'r. Process - Probes', 'Submersible Electrode Holder, 1605 mm (63.2”), 1500 mm (59.1”) submersion length'),
('HI60542', 'r. Process - Probes', 'Electrode holder for in-line direct pipe installation, PG 13.5 thread'),
('HI60542-0', 'r. Process - Probes', 'O-ring set for HI60542'),
('HI60545', 'r. Process - Probes', 'Electrode holder for by-pass loop configurations'),
('HI60545-0', 'r. Process - Probes', 'O-ring set for HI60545'),
('HI6054B', 'r. Process - Probes', 'Electrode holder for in-line installation, 3/4x16UNF thread'),
('HI6054T', 'r. Process - Probes', 'Electrode holder for in-line installation, PG 13.5 thread'),
('HI6100205', 'r. Process - Probes', 'Industrial pH Electrode for Acid samples with Fluoride ions F-, PVDF body, double junction PTFE, -5 to 60 °C, 6 bar, BNC 5m'),
('HI6100405', 'r. Process - Probes', 'Industrial pH Electrode,general purpose, PVDF body, double junction PTFE, -5 to 80 °C, 6 bar, BNC 5m'),
('HI6100410', 'r. Process - Probes', 'Industrial pH Electrode,general purpose, PVDF body, double junction PTFE, -5 to 80 °C, 6 bar, BNC 10 m'),
('HI6100805', 'r. Process - Probes', 'Industrial pH Electrode for high Temperatures, PVDF body, double junction PTFE, 0to 100 °C, 6 bar, BNC 5m'),
('HI6101205', 'r. Process - Probes', 'Industrial pH Electrode for Acid samples with Fluoride ions F-, PVDF body, double junction PTFE, -5 to 60 °C, 6 bar, BNC 5m,PT100'),
('HI6101405', 'r. Process - Probes', 'Industrial pH Electrode,general purpose, PVDF body, double junction PTFE, -5 to 80 °C, 6 bar, BNC 5m,PT100'),
('HI6101415', 'r. Process - Probes', 'Industrial pH Electrode,general purpose, PVDF body, double junction PTFE, -5 to 80 °C, 6 bar, BNC 15m,PT100'),
('HI6101605', 'r. Process - Probes', 'Industrial pH Electrode for low Temperatures, PVDF body, double junction PTFE, -10 to 80 °C, 6 bar, BNC 5m,PT100'),
('HI6101805', 'r. Process - Probes', 'Industrial pH Electrode for high Temperatures, PVDF body, double junction PTFE, 0to 100 °C, 6 bar, BNC 5m,PT100'),
('HI6200405', 'r. Process - Probes', 'Industrial Platinum ORP Electrode, PVDF body, double junction PTFE, -5 to 100 °C, 6 bar, BNC 5m,'),
('HI6200505', 'r. Process - Probes', 'Industrial Gold ORP Electrode, PVDF body, double junction PTFE, -5 to 100 °C, 6 bar, BNC 5m,PT100'),
('HI6291005', 'r. Process - Probes', 'AmpHel® pH electrode with replaceable battery, for general purpose'),
('HI6293005', 'r. Process - Probes', 'AmpHel® ORP Electrode with replaceable battery, PEI body, platinum glass type'),
('HI6493005', 'r. Process - Probes', 'AmpHel® ORP Electrode with replaceable battery, PEI body, gold glass type'),
('HI7610', 'r. Process - Probes', 'Stainless steel Temperature probe, Pt. 100'),
('HI7635', 'r. Process - Probes', 'In-line conductivity probe with automatic Temperature compensation'),
('HI7638', 'r. Process - Probes', 'EC/TDS probe with NTC sensor for immersion installation'),
('HI7638/10', 'r. Process - Probes', '4-ring EC probe with Pt rings, Temperature NTC sensor for ATC, 10 m cable'),
('HI7638/20', 'r. Process - Probes', '4-ring EC probe with Pt rings, Temperature NTC sensor for ATC, 20 m cable'),
('HI7639', 'r. Process - Probes', 'EC/TDS probe with PT100 sensor for immersion installation'),
('HI76410/10', 'r. Process - Probes', 'Galvanic DO probe for HI8410 process, 10 mt cable'),
('HI76410/4', 'r. Process - Probes', 'Galvanic DO probe for HI8410 process, 4 m cable'),
('HI76410A', 'r. Process - Probes', 'Spare membranes for HI76410 probe, 1 pc.'),
('HI7650-1005', 'r. Process - Probes', 'Inductive conductivity probe, ABS body, no ATC, 5 m cable'),
('HI7650-1010', 'r. Process - Probes', 'Inductive conductivity probe, ABS body, no ATC, 10 m cable'),
('HI7650-1015', 'r. Process - Probes', 'Inductive conductivity probe, ABS body, no ATC,15 m cable'),
('HI7650-1105', 'r. Process - Probes', 'Inductive conductivity probe, ABS body, Pt100 Temperature sensor, 5 m cable'),
('HI7650-1110', 'r. Process - Probes', 'Inductive conductivity probe, ABS body, Pt100 Temperature sensor, 10 m cable'),
('HI7650-1115', 'r. Process - Probes', 'Inductive conductivity probe, polypropylene body, Pt100 Temperature sensor, 15 m cable'),
('HI7650-1125', 'r. Process - Probes', 'Inductive conductivity probe, polypropylene body, Pt100 Temperature sensor, 25 m cable'),
('HI8299505', 'r. Process - Probes', 'AmpHel® pH electrode with replaceable battery, for high Temperatures'),
('HI1006-1800', 'r. Process - Probes Digital', 'Flat tip pH process smart probe with LT (Low Temperature) glass, PTFE junction, supplied with DIN connector (without cable)'),
('HI1006-1805', 'r. Process - Probes Digital', 'Flat tip pH process smart probe with LT (Low Temperature) glass, PTFE junction, and 5 meters of cable'),
('HI1006-1810', 'r. Process - Probes Digital', 'Flat tip pH process smart probe with LT (Low Temperature) glass, PTFE junction, and 10 meters of cable'),
('HI1006-1815', 'r. Process - Probes Digital', 'Flat tip pH process smart probe with LT (Low Temperature) glass, PTFE junction, and 15 meters of cable'),
('HI1006-1825', 'r. Process - Probes Digital', 'Flat tip pH process smart probe with LT (Low Temperature) glass, PTFE junction, and 25 meters of cable'),
('HI1006-1850', 'r. Process - Probes Digital', 'Flat tip pH process smart probe with LT (Low Temperature) glass, PTFE junction, and 50 meters of cable'),
('HI1006-3800', 'r. Process - Probes Digital', 'Flat tip pH process smart probe with HT (High Temperature) glass, PTFE junction, supplied with DIN connector (without cable)'),
('HI1006-3805', 'r. Process - Probes Digital', 'Flat tip pH process smart probe with HT (High Temperature) glass, PTFE junction, and 5 meters of cable'),
('HI1006-3810', 'r. Process - Probes Digital', 'Flat tip pH process smart probe with HT (High Temperature) glass, PTFE junction, and 10 meters of cable'),
('HI1006-3815', 'r. Process - Probes Digital', 'Flat tip pH process smart probe with HT (High Temperature) glass, PTFE junction, and 15 meters of cable'),
('HI1006-3825', 'r. Process - Probes Digital', 'Flat tip pH process smart probe with HT (High Temperature) glass, PTFE junction, and 25 meters of cable'),
('HI1006-3850', 'r. Process - Probes Digital', 'Flat tip pH process smart probe with HT (High Temperature) glass, PTFE junction, and 50 meters of cable'),
('HI1006-4800', 'r. Process - Probes Digital', 'Flat tip pH process smart probe wifh HF (Fluoride-resistant) glass, PTFE junction, supplied with DIN connector (without cable)'),
('HI1006-4805', 'r. Process - Probes Digital', 'Flat tip pH process smart probe wifh HF (Fluoride-resistant) glass, PTFE junction, and 5 meters of cable'),
('HI1006-4810', 'r. Process - Probes Digital', 'Flat tip pH process smart probe wifh HF (Fluoride-resistant) glass, PTFE junction, and 10 meters of cable'),
('HI1006-4815', 'r. Process - Probes Digital', 'Flat tip pH process smart probe wifh HF (Fluoride-resistant) glass, PTFE junction, and 15 meters of cable'),
('HI1006-4825', 'r. Process - Probes Digital', 'Flat tip pH process smart probe wifh HF (Fluoride-resistant) glass, PTFE junction, and 25 meters of cable'),
('HI1006-4850', 'r. Process - Probes Digital', 'Flat tip pH process smart probe wifh HF (Fluoride-resistant) glass, PTFE junction, and 50 meters of cable'),
('HI1006-6805', 'r. Process - Probes Digital', 'Spheric bulb pH Process Smart Probe, Fluoride-resistant max 2 g/L , HF Glass Sensor, Platinum Matching Pin, 0.0 to 100 °C ( 23.0 to 212.0 °F) 4.00 to 10.00 pH, PTFE junction, 5m (16.5'') Cable'),
('HI1016-1800', 'r. Process - Probes Digital', 'Flat tip pH process smart probe with LT (Low Temperature) glass, ceramic junction, supplied with DIN connector (without cable)'),
('HI1016-1805', 'r. Process - Probes Digital', 'Flat tip pH process smart probe with LT (Low Temperature) glass, ceramic junction, and 5 meters of cable'),
('HI1016-1810', 'r. Process - Probes Digital', 'Flat tip pH process smart probe with LT (Low Temperature) glass, ceramic junction, and 10 meters of cable'),
('HI1016-1815', 'r. Process - Probes Digital', 'Flat tip pH process smart probe with LT (Low Temperature) glass, ceramic junction, and 15 meters of cable'),
('HI1016-1825', 'r. Process - Probes Digital', 'Flat tip pH process smart probe with LT (Low Temperature) glass, ceramic junction, and 25 meters of cable'),
('HI1016-1850', 'r. Process - Probes Digital', 'Flat tip pH process smart probe with LT (Low Temperature) glass, ceramic junction, and 50 meters of cable'),
('HI1016-3800', 'r. Process - Probes Digital', 'Flat tip pH process smart probe with HT (High Temperature) glass, ceramic junction, supplied with DIN connector (without cable)'),
('HI1016-3805', 'r. Process - Probes Digital', 'Flat tip pH process smart probe with HT (High Temperature) glass, ceramic junction, and 5 meters of cable'),
('HI1016-3810', 'r. Process - Probes Digital', 'Flat tip pH process smart probe with HT (High Temperature) glass, ceramic junction, and 10 meters of cable'),
('HI1016-3815', 'r. Process - Probes Digital', 'Flat tip pH process smart probe with HT (High Temperature) glass, ceramic junction, and 15 meters of cable'),
('HI1016-3825', 'r. Process - Probes Digital', 'Flat tip pH process smart probe with HT (High Temperature) glass, ceramic junction, and 25 meters of cable'),
('HI1016-3850', 'r. Process - Probes Digital', 'Flat tip pH process smart probe with HT (High Temperature) glass, ceramic junction, and 50 meters of cable'),
('HI1016-4800', 'r. Process - Probes Digital', 'Flat tip pH process smart probe wifh HF (Fluoride-resistant) glass, ceramic junction, supplied with DIN connector (without cable)'),
('HI1016-4805', 'r. Process - Probes Digital', 'Flat tip pH process smart probe wifh HF (Fluoride-resistant) glass, ceramic junction, and 5 meters of cable'),
('HI1016-4810', 'r. Process - Probes Digital', 'Flat tip pH process smart probe wifh HF (Fluoride-resistant) glass, ceramic junction, and 10 meters of cable'),
('HI1016-4815', 'r. Process - Probes Digital', 'Flat tip pH process smart probe wifh HF (Fluoride-resistant) glass, ceramic junction, and 15 meters of cable'),
('HI1016-4825', 'r. Process - Probes Digital', 'Flat tip pH process smart probe wifh HF (Fluoride-resistant) glass, ceramic junction, and 25 meters of cable'),
('HI1016-4850', 'r. Process - Probes Digital', 'Flat tip pH process smart probe wifh HF (Fluoride-resistant) glass, ceramic junction, and 50 meters of cable'),
('HI1026-1803', 'r. Process - Probes Digital', 'Conic tip pH process smart probe for Meat Products with LT (Low Temperature) glass, Open junction, Stainless Steel piercing blade and 3 meters of cable'),
('HI1106-3800', 'r. Process - Probes Digital', 'Round tip pH Electrode pH Process Smart Probe with HT (High Temperature) Sterilizable glass, PTFE junction, 6 Bar, supplied with DIN connector (without cable)'),
('HI1106-3805', 'r. Process - Probes Digital', 'Round tip pH Electrode pH Process Smart probe with HT (High Temperature) Sterilizable glass, PTFE junction, 6 Bar, 5 meters Cable'),
('HI1106-3810', 'r. Process - Probes Digital', 'Round tip pH Electrode pH Process Smart Probe with HT (High Temperature) Sterilizable glass, PTFE junction, 6 Bar, 10 meters Cable'),
('HI1106-3815', 'r. Process - Probes Digital', 'Round tip pH Electrode pH Process Smart Probe with HT (High Temperature) Sterilizable glass, PTFE junction, 6 Bar, 15 meters Cable'),
('HI1106-3825', 'r. Process - Probes Digital', 'Round tip pH Electrode pH Process Smart Probe with HT (High Temperature) Sterilizable glass, PTFE junction, 6 Bar, 25 meters Cable'),
('HI1106-3850', 'r. Process - Probes Digital', 'Round tip pH Electrode pH Process Smart Probe with HT (High Temperature) Sterilizable glass, PTFE junction, 6 Bar, 50 meters Cable'),
('HI1126-1805', 'r. Process - Probes Digital', 'Conic tip pH process smart probe for Food with LT (Low Temperature) glass, Open junction, and 5 meters of cable'),
('HI2004-1800', 'r. Process - Probes Digital', 'Flat tip ORP process smart probe with platinum sensor, PTFE junction, supplied with DIN connector (without cable)'),
('HI2004-1805', 'r. Process - Probes Digital', 'Flat tip ORP process smart probe with platinum sensor, PTFE junction, and 5 meters of cable'),
('HI2004-1810', 'r. Process - Probes Digital', 'Flat tip ORP process smart probe with platinum sensor, PTFE junction, and 10 meters of cable'),
('HI2004-1815', 'r. Process - Probes Digital', 'Flat tip ORP process smart probe with platinum sensor, PTFE junction, and 15 meters of cable'),
('HI2004-1825', 'r. Process - Probes Digital', 'Flat tip ORP process smart probe with platinum sensor, PTFE junction, and 25 meters of cable'),
('HI2004-1850', 'r. Process - Probes Digital', 'Flat tip ORP process smart probe with platinum sensor, PTFE junction, and 50 meters of cable'),
('HI2004-2800', 'r. Process - Probes Digital', 'Flat tip ORP process smart probe with gold sensor, PTFE junction, supplied with DIN connector (without cable)'),
('HI2004-2805', 'r. Process - Probes Digital', 'Flat tip ORP process smart probe with gold sensor, PTFE junction, and 5 meters of cable'),
('HI2004-2810', 'r. Process - Probes Digital', 'Flat tip ORP process smart probe with gold sensor, PTFE junction, and 10 meters of cable'),
('HI2004-2815', 'r. Process - Probes Digital', 'Flat tip ORP process smart probe with gold sensor, PTFE junction, and 15 meters of cable'),
('HI2004-2825', 'r. Process - Probes Digital', 'Flat tip ORP process smart probe with gold sensor, PTFE junction, and 25 meters of cable'),
('HI2004-2850', 'r. Process - Probes Digital', 'Flat tip ORP process smart probe with gold sensor, PTFE junction, and 50 meters of cable'),
('HI2014-1800', 'r. Process - Probes Digital', 'Flat tip ORP process smart probe with platinum sensor, ceramic junction, supplied with DIN connector (without cable)'),
('HI2014-1805', 'r. Process - Probes Digital', 'Flat tip ORP process smart probe with platinum sensor, ceramic junction, and 5 meters of cable'),
('HI2014-1810', 'r. Process - Probes Digital', 'Flat tip ORP process smart probe with platinum sensor, ceramic junction, and 10 meters of cable'),
('HI2014-1815', 'r. Process - Probes Digital', 'Flat tip ORP process smart probe with platinum sensor, ceramic junction, and 15 meters of cable'),
('HI2014-1825', 'r. Process - Probes Digital', 'Flat tip ORP process smart probe with platinum sensor, ceramic junction, and 25 meters of cable'),
('HI2014-1850', 'r. Process - Probes Digital', 'Flat tip ORP process smart probe with platinum sensor, ceramic junction, and 50 meters of cable'),
('HI2014-2800', 'r. Process - Probes Digital', 'Flat tip ORP process smart probe with gold sensor, ceramic junction, supplied with DIN connector (without cable)'),
('HI2014-2805', 'r. Process - Probes Digital', 'Flat tip ORP process smart probe with gold sensor, ceramic junction, and 5 meters of cable'),
('HI2014-2810', 'r. Process - Probes Digital', 'Flat tip ORP process smart probe with gold sensor, ceramic junction, and 10 meters of cable'),
('HI2014-2815', 'r. Process - Probes Digital', 'Flat tip ORP process smart probe with gold sensor, ceramic junction, and 15 meters of cable'),
('HI2014-2825', 'r. Process - Probes Digital', 'Flat tip ORP process smart probe with gold sensor, ceramic junction, and 25 meters of cable'),
('HI2014-2850', 'r. Process - Probes Digital', 'Flat tip ORP process smart probe with gold sensor, ceramic junction, and 50 meters of cable'),
('HI7630-2800', 'r. Process - Probes Digital', '2-ring cell conductivity, inox, process smart probe, supplied with DIN connector (without cable)'),
('HI7630-2805', 'r. Process - Probes Digital', '2-ring cell conductivity, inox, process smart probe with 5 meters cable'),
('HI7630-2810', 'r. Process - Probes Digital', '2-ring cell conductivity, inox, process smart probe with 10 meters cable'),
('HI7630-2815', 'r. Process - Probes Digital', '2-ring cell conductivity, inox, process smart probe with 15 meters cable'),
('HI7630-2825', 'r. Process - Probes Digital', '2-ring cell conductivity, inox, process smart probe with 25 meters cable'),
('HI7630-2850', 'r. Process - Probes Digital', '2-ring cell conductivity, inox, process smart probe with 50 meters cable'),
('HI7630-4800', 'r. Process - Probes Digital', '4-ring conductivity, platinum on glass, process smart probe, supplied with DIN connector (without cable)'),
('HI7630-4805', 'r. Process - Probes Digital', '4-ring conductivity, platinum on glass, process smart probe with 5 meters cable'),
('HI7630-4810', 'r. Process - Probes Digital', '4-ring conductivity, platinum on glass, process smart probe with 10 meters cable'),
('HI7630-4815', 'r. Process - Probes Digital', '4-ring conductivity, platinum on glass, process smart probe with 15 meters cable'),
('HI7630-4825', 'r. Process - Probes Digital', '4-ring conductivity, platinum on glass, process smart probe with 25 meters cable'),
('HI7630-4850', 'r. Process - Probes Digital', '4-ring conductivity, platinum on glass, process smart probe with 50 meters cable'),
('HI7640-1800', 'r. Process - Probes Digital', 'Galvanic Dissolved Oxygen process smart probe, supplied with DIN connector (without cable)'),
('HI7640-1805', 'r. Process - Probes Digital', 'Galvanic Dissolved Oxygen process smart probe with 5 meters cable'),
('HI7640-1810', 'r. Process - Probes Digital', 'Galvanic Dissolved Oxygen process smart probe with 10 meters cable'),
('HI7640-1815', 'r. Process - Probes Digital', 'Galvanic Dissolved Oxygen process smart probe with 15 meters cable'),
('HI7640-1825', 'r. Process - Probes Digital', 'Galvanic Dissolved Oxygen process smart probe with 25 meters cable'),
('HI7640-1850', 'r. Process - Probes Digital', 'Galvanic Dissolved Oxygen process smart probe with 50 meters cable'),
('HI7640-5800', 'r. Process - Probes Digital', 'Optical DO process smart probe, supplied with DIN connector (without cable)'),
('HI7640-5805', 'r. Process - Probes Digital', 'Optical DO process smart probe with 5 meters cable'),
('HI7640-5810', 'r. Process - Probes Digital', 'Optical DO process smart probe with 10 meters cable'),
('HI7640-5815', 'r. Process - Probes Digital', 'Optical DO process smart probe with 15 meters cable'),
('HI7640-5825', 'r. Process - Probes Digital', 'Optical DO process smart probe with 25 meters cable'),
('HI7640-5850', 'r. Process - Probes Digital', 'Optical DO process smart probe with 50 meters cable'),
('HI7660-2802', 'r. Process - Probes Digital', 'Low Range Turbidity Probe (400 NTU), 2m (6.7'') Cable'),
('HI7660-2805', 'r. Process - Probes Digital', 'Low Range Turbidity Probe (400 NTU), 5m (16.5'') Cable'),
('HI7660-2810', 'r. Process - Probes Digital', 'Low Range Turbidity Probe (400 NTU), 10m (33'') Cable'),
('BL1.5-1', 'r. Process - Pumps', 'BlackStone Series Dosing Pump, 1.5 lph (0.4 gph) @13 bar (188.5 psi), 115V'),
('BL1.5-2', 'r. Process - Pumps', 'BlackStone Series Dosing Pump, 1.5 lph (0.4 gph) @13 bar (188.5 psi), 220V'),
('BL10-1', 'r. Process - Pumps', 'BlackStone Series Dosing Pump, 10.8 lph (2.9 gph) @ 3 bar (43.5 psi), 115V'),
('BL10-2', 'r. Process - Pumps', 'BlackStone Series Dosing Pump, 10.8 lph (2.9 gph) @ 3 bar (43.5 psi), 220V'),
('BL15-1', 'r. Process - Pumps', 'BlackStone Series Dosing Pump, 15.2 lph (4.0 gph)@ 1 bar (14.5 psi), 115V'),
('BL15-2', 'r. Process - Pumps', 'BlackStone Series Dosing Pump, 15.2 lph (4.0 gph)@ 1 bar (14.5 psi), 220V'),
('BL20-1', 'r. Process - Pumps', 'BlackStone Series Dosing Pump, 18.3 lph (4.8 gph) @ 0.5 bar (7.4 psi), 115V'),
('BL20-2', 'r. Process - Pumps', 'BlackStone Series Dosing Pump, 18.3 lph (4.8 gph) @ 0.5 bar (7.4 psi), 220V'),
('BL3-1', 'r. Process - Pumps', 'BlackStone Series Dosing Pump, 2.9 lph (0.8 gph) @ 8 bar (116 psi), 115V'),
('BL3-2', 'r. Process - Pumps', 'BlackStone Series Dosing Pump, 2.9 lph (0.8 gph) @ 8 bar (116 psi), 220V'),
('BL5-1', 'r. Process - Pumps', 'BlackStone Series Dosing Pump, 5.0 lph (1.3 gph) @ 7 bar (101.5 psi), 115V'),
('BL5-2', 'r. Process - Pumps', 'BlackStone Series Dosing Pump, 5.0 lph (1.3 gph) @ 7 bar (101.5 psi), 220V'),
('BL7-1', 'r. Process - Pumps', 'BlackStone Series Dosing Pump, 7.6 lph (2.0 gph) @ 3 bar (43.5 psi), 115V'),
('BL7-2', 'r. Process - Pumps', 'BlackStone Series Dosing Pump, 7.6 lph (2.0 gph) @ 3 bar (43.5 psi), 220V'),
('HI720029', 'r. Process - Pumps Spares', 'Pump spare part, LDPE hose, 3 m (9.9’)'),
('HI720030', 'r. Process - Pumps Spares', 'Pump spare part, LDPE hose, 10 m (33’)'),
('HI720031', 'r. Process - Pumps Spares', 'Pump spare part, LDPE hose, 50 m (165’)'),
('HI720032', 'r. Process - Pumps Spares', 'Pump spare part, LDPE hose, 100 m (333’)'),
('HI721003', 'r. Process - Pumps Spares', 'Pump spare part, Glass ball with O-ring (10 pcs each)'),
('HI721004', 'r. Process - Pumps Spares', 'Pump spare part, Injection valve assembly'),
('HI721005', 'r. Process - Pumps Spares', 'Pump spare part, Foot valve assembly'),
('HI721006', 'r. Process - Pumps Spares', 'Pump spare part, Spring (4 pcs)'),
('HI721008', 'r. Process - Pumps Spares', 'Pump spare part, Ceramic weight (4 pcs)'),
('HI721101', 'r. Process - Pumps Spares', 'Pump spare part, Pump head, O-ring, screws (6 pcs) and washers (6 pcs)'),
('HI721102', 'r. Process - Pumps Spares', 'Pump spare part, Discharge valve assembly'),
('HI721103', 'r. Process - Pumps Spares', 'Pump spare part, Suction valve assembly'),
('HI721104', 'r. Process - Pumps Spares', 'Pump, small diaphragm'),
('HI721106', 'r. Process - Pumps Spares', 'Pump head assembly'),
('HI721107', 'r. Process - Pumps Spares', 'Pump Head with small diaphragm + Aluminium piston + disck'),
('FC096', 'z - Accessories', 'Handle and Stainless-Steel Blade for FC2023 pH Electrode Accessories'),
('FC097', 'z - Accessories', 'Stainless Steel Blade for Meat pH Testers, Compatible with HI9810452 and HI981045'),
('FC098', 'z - Accessories', 'Blade, stainless steel for meat pH electrode, 20 mm (0.8”)'),
('FC099', 'z - Accessories', 'Blade, stainless steel for meat pH electrode, 35 mm (1.4”)'),
('FC766TZ-0', 'z - Accessories', 'Spare tape for Sous Vides temperature probe (1 mt)'),
('HI1270', 'z - Accessories', 'Spare pH electrode with screw connector'),
('HI1280', 'z - Accessories', 'Spare electrode for general purpose and field applications'),
('HI1283', 'z - Accessories', 'Bar, grounding with 1 m (3.3’) cable'),
('HI1290', 'z - Accessories', 'Spare electrode for general purpose and field applications'),
('HI141001', 'z - Accessories', 'Transmitter, Infrared, for PC Connection, for HI141 series'),
('HI144002', 'z - Accessories', 'USB communication cradle for HI 144 T-logger'),
('HI2000BC', 'z - Accessories', 'Benchtop cradle for edge'),
('HI2000BCW', 'z - Accessories', 'Benchtop cradle for edge, white color'),
('HI2000WC', 'z - Accessories', 'Wall cradle for edge'),
('HI2000WCW', 'z - Accessories', 'Wall cradle for edge, white color'),
('HI3316D', 'z - Accessories', 'Resistivity probe with internal Temperature sensor, DIN connector and 1 m (3.3’) cable.'),
('HI510-01', 'z - Accessories', 'Panel-Mount Kit for HI510'),
('HI510-02', 'z - Accessories', 'Wall-Mount Kit for HI510'),
('HI510-03', 'z - Accessories', 'Pipe-Mount Kit for HI510'),
('HI6000-1', 'z - Accessories', 'pH/ORP module. Recommended probes: HI1131B (pH), HI7662-TW (Temperature). Works with all Hanna pH electrodes with BNC connector.'),
('HI6000180', 'z - Accessories', 'Compact Magnetic Mini-Stirrer for HI6000'),
('HI6000-2', 'z - Accessories', 'pH/ORP/ISE module. Recommended probes: HI1131B (pH), HI7662-TW (temperature), Hanna Ion Selective Electrodes.  Works with all Hanna pH electrodes with BNC connector.'),
('HI6000-3', 'z - Accessories', 'EC module. Recommended probes: HI7631233 (EC)'),
('HI6000-4', 'z - Accessories', 'Dissolved Oxygen module Recommended probes: HI7641133 (optical DO), HI764833 (polarographic DO)'),
('HI605453', 'z - Accessories', 'SS316 flow through cell for resistivity measurements'),
('HI70483T', 'z - Accessories', 'Peristaltic pump tubing for HI84XXX Minititrators (1 set)'),
('HI70498', 'z - Accessories', 'Bromine replacement reagent set for process bromine analyzer, 500 mL (2) + 5 sachets (DPD)'),
('HI70500', 'z - Accessories', 'Tube Set and Valve for Mini Titrators'),
('HI70602', 'z - Accessories', 'Relative humidity probe used with HI 9564, HI9565, DIN connector, 1 m (3.3’) cable'),
('HI710005', 'z - Accessories', 'Power adapter, 115 Vac to 12 Vdc, US plug'),
('HI710005/8', 'z - Accessories', 'Adapter, for HI42xx family, 115 VAC to 12 VDC'),
('HI7100051/8', 'z - Accessories', 'Power switching adapter 115VAC to 12VAC'),
('HI710006', 'z - Accessories', 'Power adapter, 230 Vac to 12 Vdc, European plug'),
('HI710006/8', 'z - Accessories', 'Adapter, for HI42xx family, 230 VAC to 12 VDC'),
('HI7100061/8', 'z - Accessories', 'Power Switching Adapter 230VAC to 12VAC'),
('HI710007', 'z - Accessories', 'Blue shockproof rubber boot (meter example: HI935005)'),
('HI710008', 'z - Accessories', 'Orange shockproof rubber boot (meter example: HI935005)'),
('HI710009', 'z - Accessories', 'Blue shockproof rubber boot (meter example: HI8010)'),
('HI710011', 'z - Accessories', 'Cap (sintered) for RH probes'),
('HI710012', 'z - Accessories', 'Power adapter, 230 Vac to 12 Vdc, UK plug'),
('HI710015', 'z - Accessories', 'Blue shockproof rubber boot (meter example: HI8424)'),
('HI710024', 'z - Accessories', 'Blue shockproof rubber boot (meter example: old HI991XXX)'),
('HI710025', 'z - Accessories', 'Green shockproof rubber boot (meter example: HI9814)'),
('HI710026', 'z - Accessories', 'Blue shockproof rubber boot for portable thermistor themometers (i.e. HI93501)'),
('HI710027', 'z - Accessories', 'Blue shockproof rubber boot for portable thermocouple thermometers (i.e. HI935001)'),
('HI710028', 'z - Accessories', 'Orange shockproof rubber boot for portable meters (2018 HI991XX meters)'),
('HI710029', 'z - Accessories', 'Blue shockproof rubber boot for portable meters (2018 HI991XX Foodcare meters)'),
('HI710030', 'z - Accessories', 'Green shockproof rubber boot for portable meters (2018 HI9814 GroLine meter)'),
('HI710031', 'z - Accessories', 'Carrying case (rugged) for general use. 340 x 230 x 90 mm (13.4 x 9.1 x 3.5’’)'),
('HI710032', 'z - Accessories', 'Paper rolls for benchtop meters (10 pcs)'),
('HI710033', 'z - Accessories', '1 pc ink cartridge for benchtop meters'),
('HI710034', 'z - Accessories', 'Orange shockproof rubber boot for portable meters (HI9819X meters)'),
('HI710035', 'z - Accessories', 'Blue shockproof rubber boot for portable meters (HII9816X Foodcare meters)'),
('HI710036', 'z - Accessories', 'Black rubber boot for HI9819X and HI98594'),
('HI710045', 'z - Accessories', 'Kit, HI9828 Accessory, Power supply cable'),
('HI710046', 'z - Accessories', 'Kit, HI9828 Accessory, Lighter cigarette cable'),
('HI71006/8', 'z - Accessories', 'Adapter, 230 VAC/12 VDC, 800 mA'),
('HI710122', 'z - Accessories', 'Protective case tray for HI8424 housing'),
('HI710134', 'z - Accessories', 'General rugged carrying case for HI98703 style casing'),
('HI710136', 'z - Accessories', 'General rugged carrying case for HI9125 style casing'),
('HI710139', 'z - Accessories', 'General rugged carrying case for HI93703 style casin'),
('HI7101412', 'z - Accessories', 'Blue carrying case for HI977XX portable ISM photometers with 2 CAL Check Standards Slots'),
('HI7101413', 'z - Accessories', 'Blue carrying case for HI977XX portable ISM photometers with 3 CAL Check Standards Slots'),
('HI7101414', 'z - Accessories', 'Blue carrying case for HI977XX portable ISM photometers with 4 CAL Check Standards Slots'),
('HI7101415', 'z - Accessories', 'Blue carrying case for HI977XX portable ISM photometers with 5 CAL Check Standards Slots'),
('HI7101417', 'z - Accessories', 'Blue carrying case for HI977XX portable ISM photometers with 7 CAL Check Standards Slots'),
('HI7101418', 'z - Accessories', 'Blue carrying case for HI97105C'),
('HI7101419', 'z - Accessories', 'Blue Carrying Case for HI97115C'),
('HI710142', 'z - Accessories', 'Black carrying case for HI991XX portable meters'),
('HI7101420', 'z - Accessories', 'Blue Carrying Case for HI971044R'),
('HI7101421', 'z - Accessories', 'Black Carrying Case for HI99121 Portable Instrument'),
('HI7101422', 'z - Accessories', 'Blue carrying case for HI97107C'),
('HI710143', 'z - Accessories', 'Green carrying case for HI9814 portable meter'),
('HI7102', 'z - Accessories', 'Calibration chamber for RH probes without sintered cap'),
('HI7111', 'z - Accessories', 'Salt, 15 g LiCl replacement for HI7111/P'),
('HI7111/P', 'z - Accessories', 'Salt (LiCl calibration)for HI7101 and HI7102 calibration chambers (low RH) (15 g bottle, 6 pcs)'),
('HI7121', 'z - Accessories', 'Salt, 33 g NaCl replacement for HI7121/P'),
('HI7121/P', 'z - Accessories', 'Salt (NaCl calibration)for HI7101 and HI7102 calibration chambers (high RH) (33 g bottle, 6 pcs)'),
('HI720161', 'z - Accessories', 'Replacement carrying case for HI98161, HI98162, HI98163, and HI98164'),
('HI720165', 'z - Accessories', 'Replacement carrying case for HI98165'),
('HI720169', 'z - Accessories', 'Replacement Carrying Case for HI98169'),
('HI720190', 'z - Accessories', 'Spare carrying case for HI98190'),
('HI720191', 'z - Accessories', 'Spare carrying case for HI98191'),
('HI720192', 'z - Accessories', 'Spare carrying case for HI98192'),
('HI720193', 'z - Accessories', 'Spare carrying case for HI98193'),
('HI720194', 'z - Accessories', 'Spare thermoformed carrying case for HI98194, HI98195, and HI98196'),
('HI720197', 'z - Accessories', 'Carrying case for HI98197 portable EC/TDS/Salinity/resitivity meter'),
('HI720198', 'z - Accessories', 'Spare carrying case for HI98198'),
('HI720199', 'z - Accessories', 'Spare carrying case for HI98199'),
('HI720746', 'z - Accessories', 'Spare Carrying Case for HI83746 and HI83749'),
('HI72083300', 'z - Accessories', 'Carrying case for HI833xx family'),
('HI720935', 'z - Accessories', 'Rugged thermoformed carrying case for HI93500X portable thermometers'),
('HI7209811', 'z - Accessories', 'Spare carrying case for HI981X-X'),
('HI721317', 'z - Accessories', 'Hard Carrying case'),
('HI721319', 'z - Accessories', 'Auger for ground penetration'),
('HI731225', 'z - Accessories', 'Cap for checker chlorine cuvette HI701'),
('HI73128', 'z - Accessories', 'Tool for electrode removal for new WP testers'),
('HI731311', 'z - Accessories', 'Vial, glass, with cap for HI83214 old version (5 pcs)'),
('HI731313', 'z - Accessories', 'Maintenance kit: rugged carrying case, HI93102-0 and HI93102-20 calibration solutions, HI93703-50 cuvette cleaning solution, cuvettes (2), and cuvette cleaning cloth'),
('HI731314', 'z - Accessories', 'Plastic Stopper Caps for 10 mL Glass Cuvettes ( 2 pcs.)'),
('HI731315', 'z - Accessories', 'Glass Cuvettes and Caps for Checker® HC Colorimeters (set of 2)'),
('HI731318', 'z - Accessories', 'Cuvette cleaning cloth (4 pcs)'),
('HI731319', 'z - Accessories', 'Magnetic Stirring Bar for HI180, HI190M, HI190MB and HI200M Stirrer Series 25 mm x 8.4 mm (10 pcs)'),
('HI731320', 'z - Accessories', 'Magnetic Stirring Bar for HI300 Stirrer Series, 50 mm x 8 mm (10 pcs)'),
('HI731321', 'z - Accessories', 'Cuvette (glass) for HI937xx portable meter, HI832xx series and Checkers (4 pcs)'),
('HI731324', 'z - Accessories', 'Bar, measuring for level controllers, 0.5 m (1.7’) measuring bar (5 pcs)'),
('HI731325', 'z - Accessories', 'Cap for cuvette for HI937X3 turbidity meters and HI937xx series (4 pcs)'),
('HI731325N', 'z - Accessories', 'Cap for cuvette for old style benchtop photometers C21X and HI832XX series (4 pcs)'),
('HI731325W', 'z - Accessories', 'Caps for cuvette for HI83200 series of photometers (4 pcs)'),
('HI731326', 'z - Accessories', 'Screwdriver for calibration, length 90 mm (3.5’’), to perform manual calibration with trimmers (20 pcs)'),
('HI731331', 'z - Accessories', 'Cuvette with plastic insert for portable photometers (4 pcs)'),
('HI731331N', 'z - Accessories', 'Cuvettes for turbidity meter (4 pcs)'),
('HI731335', 'z - Accessories', 'Caps for larger vials for HI95 and HI96 series photometers, 4 pcs'),
('HI731335N', 'z - Accessories', 'Caps for cuvette for HI837 series photometer and 987XX and 887XX turbidity meters (4 pcs)'),
('HI731336N', 'z - Accessories', 'Replacement cap for HI977XX photometers (4 pcs.)'),
('HI731339P', 'z - Accessories', 'Pipette for automatic dosage, 100 µL graduated pipette'),
('HI731340', 'z - Accessories', 'Pipette for automatic dosage, 200 µL graduated pipette'),
('HI731341', 'z - Accessories', 'Pipette for automatic dosage, 1000 µL graduated pipette'),
('HI731342', 'z - Accessories', 'Pipette for automatic dosage, 2000 µL graduated pipette'),
('HI731349P', 'z - Accessories', 'Pipette for automatic dosage, Tip for 100 µL graduated pipette (10 pcs)'),
('HI731350', 'z - Accessories', 'Pipette for automatic dosage, Tip for 200 µL graduated pipette (25 pcs)'),
('HI731351', 'z - Accessories', 'Pipette for automatic dosage, Tip for 1000 µL graduated pipette (25 pcs)'),
('HI731352', 'z - Accessories', 'Pipette for automatic dosage, Tip for 2000 µL graduated pipette (4 pcs)'),
('HI731359', 'z - Accessories', 'Glass cuvettes with plastic cap insert for HI759 Maple Syrup Digital Grader (25 pcs)'),
('HI731360', 'z - Accessories', 'Glass cuvette with cap (2 pcs.)'),
('HI731361', 'z - Accessories', 'Magnetic Stir Bar Retriever Accessory'),
('HI73311', 'z - Accessories', 'Spare probe for HI98311 & HI98312'),
('HI740024P', 'z - Accessories', 'Base for Checktemp®1 (10 pcs)'),
('HI740027P', 'z - Accessories', 'Batteries, kit of 1.5V AA batteries (12 pcs)'),
('HI740028P', 'z - Accessories', 'Batteries, kit of 1.5V AAA batteries (12 pcs)'),
('HI740029P', 'z - Accessories', 'Batteries for portable non-waterproof instruments, 9 V (10 pcs)'),
('HI740031', 'z - Accessories', 'Battery, spare for AmpHel® electrodes'),
('HI740032P', 'z - Accessories', 'Beaker cap for 20 mL plastic beaker (10 pcs)'),
('HI740033', 'z - Accessories', 'Battery for HI141 series, 3.6V AA Lithium (1 pc)'),
('HI740034P', 'z - Accessories', 'Beaker cap for 100 mL plastic beaker (10 pcs)'),
('HI740036P', 'z - Accessories', 'Beaker, plastic 100 mL (10 pcs)'),
('HI740037P', 'z - Accessories', 'Beaker, plastic 20 mL (10 pcs)'),
('HI740038', 'z - Accessories', '60 mL Glass bottle with cap'),
('HI740129', 'z - Accessories', 'Cover (transparent) for front of BL7916 and BL7917'),
('HI740142P', 'z - Accessories', 'Syringe, graduated, for accurately reagent dosing for CTK and photometers (1 mL) (10 pcs)'),
('HI740143', 'z - Accessories', 'Syringe, graduated, for accurately reagent dosing for CTK and photometers (1 mL) (6 pcs)'),
('HI740144P', 'z - Accessories', 'Syringe tip for HI740143 (10 pcs)'),
('HI740145', 'z - Accessories', 'Bracket for mounting for HI8710 housing (2 pcs)'),
('HI740146', 'z - Accessories', 'Bracket for mounting for BL 931700 housing (2 pcs)'),
('HI740155P', 'z - Accessories', 'Capillary Pipette for Electrode refilling (20 pcs)'),
('HI740157P', 'z - Accessories', 'Pipette for Electrode refilling (20 pcs)'),
('HI740159', 'z - Accessories', 'Tweezers (plastic)'),
('HI740200', 'z - Accessories', 'pH electrode storage cap with compression fitting (5 pcs)'),
('HI740216', 'z - Accessories', 'Rack for test tube cooling (25 holes)'),
('HI740217', 'z - Accessories', 'Safety Shield for HI839800'),
('HI740220', 'z - Accessories', 'Test tube (glass) with caps, 25 mL (2 pcs)'),
('HI740224', 'z - Accessories', 'Plastic beaker (170 mL,6 pcs)'),
('HI740225', 'z - Accessories', 'Syringe, graduated, for accurately reagent dosing for CTK and photometers (60 mL)'),
('HI740226', 'z - Accessories', 'Syringe, graduated, for accurately reagent dosing for CTK and photometers 5mL'),
('HI740227', 'z - Accessories', 'Filter Assembly Accessory'),
('HI740228', 'z - Accessories', 'HI781, HI83215 and HI83225 Accessory, Filter (25 pcs)'),
('HI740229', 'z - Accessories', 'Graduated Cylinder'),
('HI740230', 'z - Accessories', 'Deionized Water, 230 mL bottle'),
('HI740231', 'z - Accessories', '20 mL Glass cylinder with cap, 2 pcs'),
('HI740233', 'z - Accessories', 'Replacement paper filter Type 2'),
('HI740234', 'z - Accessories', 'Replacement lamp for EPA turbidimeter'),
('HI740236', 'z - Accessories', '5 mL Syringe for Mini Titrators'),
('HI740237', 'z - Accessories', '5 mL Graduated Syringe with Blue printing (1 pc.)'),
('HI740239', 'z - Accessories', 'pH electrode storage cap with compression fitting, 8 mm stem diameter (5 pcs.)'),
('HI740240', 'z - Accessories', 'pH electrode storage cap with compression fitting, 12 mm stem diameter (5 pcs.)'),
('HI740241', 'z - Accessories', 'pH electrode storage cap with compression fitting, titanium stem (5 pcs.)'),
('HI740242', 'z - Accessories', 'pH Electrode Storage Cap, with Compression Fitting, White (5 pcs)'),
('HI740243', 'z - Accessories', 'Electrode PVC Storage Caps (5 pcs)'),
('HI740244', 'z - Accessories', 'pH Protective Green Sleeves (3 pcs.)'),
('HI740245', 'z - Accessories', 'pH Protective White Sleeves (3 pcs.)'),
('HI740246', 'z - Accessories', 'ISE and HI7698494 pH Sensor Storage cap (5 pcs.)'),
('HI740247', 'z - Accessories', 'Vial Adapter for HI97106'),
('HI740270', 'z - Accessories', '10 mL syringe with Luer lock (1 pc.)'),
('HI740271', 'z - Accessories', 'Filter holder with Luer lock (1 pc.)'),
('HI740272', 'z - Accessories', '16 gauge blunt needle (6 pcs.)'),
('HI740273', 'z - Accessories', 'Marine Nitrate LR measurement kit (1 pc.)'),
('HI740274', 'z - Accessories', 'Syringe Replacement kit for HI783'),
('HI740275', 'z - Accessories', 'Protective Caps for HI7698394 Probe (5 pcs.)'),
('HI740318', 'z - Accessories', 'Carrying case for portable 96 series photometers'),
('HI74083300', 'z - Accessories', 'Replacement COD adpater for HI833XX benchtop colorimeters'),
('HI750146', 'z - Accessories', 'Holder for HI146 probe, wall mounting'),
('HI75110/15', 'z - Accessories', '120VAC to 15VDC power adapter, USA plug'),
('HI75110/220E', 'z - Accessories', 'Voltage adapter from 230 VAC to USB 5 VDC (European plug)'),
('HI75110/220U', 'z - Accessories', 'Voltage adapter from 115 VAC to USB 5 VDC (USA plug)'),
('HI75115U', 'z - Accessories', 'Voltage Adapter from 115 to 230 VAC input to 5 VDC output USB C (USA plug)'),
('HI75220/15', 'z - Accessories', '230VAC to 15VDC power adapter, European plug'),
('HI75230E', 'z - Accessories', 'Voltage Adapter from 115 to 230 VAC input to 5 VDC output USB C (European plug)'),
('HI762000C', 'z - Accessories', 'Calibration check key @ 0ºC, (±0.4ºC)'),
('HI762-004F', 'z - Accessories', 'Calibration check key @ -0.4ºF, (±0.8ºF)'),
('HI762032F', 'z - Accessories', 'Calibration check key @ 32ºF, (±0.8ºF)'),
('HI762070C', 'z - Accessories', 'Calibration check key @ 70ºC, (±0.4ºC)'),
('HI762158F', 'z - Accessories', 'Calibration check key @ 158ºF, (±0.8ºF)'),
('HI762-18C', 'z - Accessories', 'Calibration check key @ -18ºC, (±0.4ºC)'),
('HI7630', 'z - Accessories', 'EC/TDS probe, amperometric for HI993301, HI993302 with 2 m cable'),
('HI76301D', 'z - Accessories', '4-ring conductivity probe with DIN connector and 1 m (3.3’) cable for HI8633'),
('HI76301W', 'z - Accessories', '4-ring conductivity probe with 1 m (3.3’) cable'),
('HI76302/10', 'z - Accessories', '4-ring conductivity probe with 10 m (3.3’) cable'),
('HI76302W', 'z - Accessories', '4-ring conductivity probe with internal Temperature sensor, DIN connector and 1 m (3.3’) cable'),
('HI76303', 'z - Accessories', 'Platinum 4-ring conductivity probe with internal Temperature sensor, DIN connector and 1 m (3.3’) cable.'),
('HI76304', 'z - Accessories', 'Conductivity probe with internal Temperature sensor, DIN connector and 1 m (3.3’) cable for HI933100 measurement in soil slurry sample'),
('HI76305', 'z - Accessories', 'Stainless steel conductivity probe with internal Temperature sensor, DIN connector and 1 m (3.3’) cable for direct soil measurement, for HI933100'),
('HI76306', 'z - Accessories', 'EC/TDS probe with internal Temperature sensor, DIN connector and 1 m (3.3’) cable, for small casing portables'),
('HI763063', 'z - Accessories', 'EC/TDS probe with quick connect DIN connector for HI99300/HI99301'),
('HI76309', 'z - Accessories', 'Conductivity/TDS probe for HI9835 with 1 m cable'),
('HI76309/1.5', 'z - Accessories', '4-ring conductivity probe with internal Temperature sensor, DIN connector and 1.5 m (4.9’) cable.'),
('HI7631/2', 'z - Accessories', 'EC probe with 2 m cable and 1/2” thread'),
('HI7631/2/5', 'z - Accessories', 'EC probe with 5 m cable and 1/2” thread'),
('HI76310', 'z - Accessories', 'Platinum, 4-ring conductivity/TDS probe with 1 m (3.3’) cable'),
('HI76312', 'z - Accessories', 'Platinum, 4-ring conductivity/TDS probe with internal Temperature sensor and 1 m (3.3’) cable'),
('HI763123', 'z - Accessories', 'EC/resistivity probe for HI98197'),
('HI7631233', 'z - Accessories', 'EC/Resistivity Probe for HI6321'),
('HI763133', 'z - Accessories', 'Platinum, 4-ring conductivity/TDS probe w/ internal Temperature sensor, DIN connector and 1.5 m (4.9’) cable for HI98192'),
('HI7640-18A/P', 'z - Accessories', 'Spare DO Membrane Caps (5 pcs) for Galvanic DO Process Smart Probes'),
('HI764026', 'z - Accessories', 'Electrode Holder for HI2600 Family'),
('HI76404', 'z - Accessories', 'Electrode holder for pH 209 type benchtop meters'),
('HI76404A', 'z - Accessories', 'Electrode holder (blue) with attachment for HI833xx family'),
('HI76404B', 'z - Accessories', 'Electrode Holder for edge'),
('HI76404N', 'z - Accessories', 'Electrode holder (red) with attachment for HI4XXX benchtop meter'),
('HI76404W', 'z - Accessories', 'White electrode holder for HI2000 and HI5000 series'),
('HI76405', 'z - Accessories', 'Electrode holder with steel base'),
('HI764060', 'z - Accessories', 'HI764060 Electrode Holder for HI6000 Family'),
('HI765000C', 'z - Accessories', 'Calibration check key @ 0ºC, (±0.4ºC)'),
('HI765-004F', 'z - Accessories', 'CAL Check key @ -0.4ºF, (±0.8ºF)'),
('HI765032F', 'z - Accessories', 'Calibration check key @ 32ºF, (±0.8ºF)'),
('HI765070C', 'z - Accessories', 'Calibration check key @ 70ºC, (±0.4ºC)'),
('HI76510-05', 'z - Accessories', 'Digital Process Probes Detachable Cable, 5 m (16’5”)'),
('HI76510-10', 'z - Accessories', 'Digital Process Probes Detachable Cable, 10 m (32’9”)'),
('HI76510-15', 'z - Accessories', 'Digital Process Probes Detachable Cable, 15 m (49’2”)'),
('HI76510-25', 'z - Accessories', 'Digital Process Probes Detachable Cable, 25 m (82’)'),
('HI76510-50', 'z - Accessories', 'Digital Process Probes Detachable Cable, 50 m (164’)'),
('HI765158F', 'z - Accessories', 'Calibration check key @ 158ºF, (±0.8ºF)'),
('HI765-18C', 'z - Accessories', 'CAL Check key @ -18°C, (±0.4°C)'),
('HI76608', 'z - Accessories', 'Replacement Temperature probe for HI8614'),
('HI7662', 'z - Accessories', 'Replacement Temperature probe for portable'),
('HI7662-M', 'z - Accessories', 'Replacement Temperature Probe for HI845XX Minititrators'),
('HI7662-T', 'z - Accessories', 'Replacement Temperature probe for color benchtop'),
('HI7662-W', 'z - Accessories', 'Replacement temperature probe for HI5XXX research grade benchtops'),
('HI7669/2W', 'z - Accessories', 'Replacement Temperature probe for portable with phono connector'),
('HI7669AW', 'z - Accessories', 'Replacement Temperature probe for portable with jack connector'),
('HI7676602', 'z - Accessories', 'Flow Cell for HI7660-28XX Probe'),
('HI7676603', 'z - Accessories', 'Calibration Beaker for HI7660-28XX Low Range Turbidity Probe'),
('HI7676604', 'z - Accessories', 'Dry Standard for HI7660-28XX Low Range Turbidity Probe'),
('HI7676605', 'z - Accessories', 'Flow Tee for HI7660-28XX Low Range Turbidity Probe'),
('HI7676605-0', 'z - Accessories', 'O-Ring for HI7676605 Flow Tee'),
('HI7676605-1', 'z - Accessories', 'Adapter for HI7676605 Flow Tee'),
('HI7676606', 'z - Accessories', 'Flow Cell for HI7660-28XX Probe for Measurements > 40 NTU'),
('HI76983948', 'z - Accessories', 'Atmospheric Pressure Box For HI98394'),
('HI7785P/1', 'z - Accessories', 'Connection cable 5 mm diameter, with screw and BNC connectors, 1 m (3.3’)'),
('HI7785P/10', 'z - Accessories', 'Connection cable 5 mm diameter, with screw and BNC connectors, 10 m (33’)'),
('HI7785P/3', 'z - Accessories', 'Connection cable 5 mm diameter, with screw and BNC connectors, 3 m (9.9’)'),
('HI7785P/5', 'z - Accessories', 'Connection cable 5 mm diameter, with screw and BNC connectors, 5 m (16.5’)'),
('HI7785P/7', 'z - Accessories', 'Connection cable 5 mm diameter, with screw and BNC connectors, 7 m (23.1’)'),
('HI7787P/1', 'z - Accessories', 'Connection cable, 5 mm diameter, with screw and DIN connectors, 1 m (3.3’)'),
('HI7787P/10', 'z - Accessories', 'Connection cable, 5 mm diameter, with screw and DIN connectors, 10 m (33’)'),
('HI7787P/3', 'z - Accessories', 'Connection cable, 5 mm diameter, with screw and DIN connectors, 3 m (9.9’)'),
('HI7787P/5', 'z - Accessories', 'Connection cable, 5 mm diameter, with screw and DIN connectors, 5 m (16.5’)'),
('HI7787P/7', 'z - Accessories', 'Connection cable, 5 mm diameter, with screw and DIN connectors, 7 m (23.1’)'),
('HI7855/1', 'z - Accessories', 'Connection cable with screw and BNC connectors, 1 m (3.3’)'),
('HI7855/10', 'z - Accessories', 'Connection cable with screw and BNC connectors, 10 m (33’)'),
('HI7855/15', 'z - Accessories', 'Connection cable with screw and BNC connectors, 15 m (49.5’)'),
('HI7855/3', 'z - Accessories', 'Connection cable with screw and BNC connectors, 3 m (9.9’)'),
('HI7855/5', 'z - Accessories', 'Connection cable with screw and BNC connectors, 5 m (16.5’)'),
('HI7855/7', 'z - Accessories', 'Connection cable with screw and BNC connectors 7 m (23.1’)'),
('HI7857/1', 'z - Accessories', 'Connection cable, 3 mm diameter, with screw and DIN connectors, 1 m (3.3’)'),
('HI7857/10', 'z - Accessories', 'Connection cable, 3 mm diameter, with screw and DIN connectors, 10 m (33’)'),
('HI7857/3', 'z - Accessories', 'Connection cable, 3 mm diameter, with screw and DIN connectors, 3 m (9.9’)'),
('HI7857/5', 'z - Accessories', 'Connection cable, 3 mm diameter, with screw and DIN connectors, 5 m (16.5’)'),
('HI7857/7', 'z - Accessories', 'Connection cable, 3 mm diameter, with screw and DIN connectors, 7 m (23.1’)'),
('HI7858/1', 'z - Accessories', 'Connection cable with BNC and BNC connectors, 1 m 3.3’)'),
('HI7858/10', 'z - Accessories', 'Connection cable with BNC and BNC connectors, 10 m (33’)'),
('HI7858/5', 'z - Accessories', 'Connection cable with BNC and BNC connectors, 5 m (16.5’)'),
('HI83900-25', 'z - Accessories', 'Lysimeter, cleaning solution replacement kit for suction lysimeter, 500 mL'),
('HI83900-30', 'z - Accessories', 'Suction lysimeter for root level soil monitoring, for use with HI83225 and HI83215; 30 cm'),
('HI83900-60', 'z - Accessories', 'Suction lysimeter for root level soil monitoring, for use with HI83225 and HI83215; 60 cm'),
('HI83900-90', 'z - Accessories', 'Suction lysimeter for root level soil monitoring, for use with HI83225 and HI83215; 90 cm'),
('HI90140', 'z - Accessories', 'Transmitter, Infrared, for PC Connection, for HI140 series'),
('HI920005', 'z - Accessories', 'iButton Fast Tracker tags, 5 tag holders with tags'),
('HI920010', 'z - Accessories', 'Cable (serial) for PC connection (9 to 9-pin)'),
('HI920011', 'z - Accessories', 'Cable (serial) for PC connection (5 to 9-pin)'),
('HI920013', 'z - Accessories', 'Cable, USB PC connection (excluding HI9828, use HI7698281 instead)'),
('HI920014', 'z - Accessories', 'Mini USB cable connector'),
('HI920015', 'z - Accessories', 'USB to micro USB cable connector for HI20X0,HI200X, and HI9819X meters'),
('HI920016', 'z - Accessories', 'USB Type A to C Cable'),
('HI920018', 'z - Accessories', 'USB Type C to C White Cable, 1.5m'),
('HI920019', 'z - Accessories', 'USB Type C to C Black Cable, 1m'),
('HI92150', 'z - Accessories', 'RS232 to USB cable')
ON CONFLICT (codigo) DO NOTHING;